### ISSUE TITLE
Installation Script forces the use of wine over wine-staging

### ISSUE THREAD

**Issue by hasmar04** [cryinkfly/Autodesk-Fusion-360-for-Linux#119]
**Bug Description**
When installing Fusion 360, the script requires wine to be installed. On Manjaro, this conflicts with wine-staging, which I had installed, meaning to use this script I had to uninstall wine-staging. 

**To Reproduce**
1. Start script
2. Let it install required packages
3. Prompt appears to remove the conflicting package wine-staging

**Expected behavior**
The installer only requires a version of wine to be installed, be it wine or wine-staging. 

**Desktop:**
- Version number of Autodesk Fusion 360: 2.0.11405
- Graphics card model + Graphics card driver (Version number): Intel UHD Graphics 620
- Operating system (OpenSUSE Leap 15.3, Fedora 34, ...): Manjaro 21.1.6
- Desktop environment (XFCE 4.16, Gnome 40, ...): KDE Plasma 5.22.5
- DXVK- or OpenGL-Mode: DXVK

**Comment by cryinkfly** [comment]
Hey @hasmar04 👋,

in the next Update I hope that I can give you choise for skipping this issue so, that you have two options:

- 1: Install wine from the standard repository (system)
- 2: Install wine from the custom repository (installer)

I hope you can wait a little time. 😉🙂

**Comment by hasmar04** [comment]
But will that allow for the choice between wine and wine-staging in the official repositories?

**Comment by cryinkfly** [comment]
@hasmar04 Yes, I will offer different options, similar to the DXVK and openGL method. :+1:

**Comment by cryinkfly** [comment]
I have solved this problem now! See here: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/releases/tag/v5.5
