### ISSUE TITLE
Fusion 360 Crashes After Login *solved*

### ISSUE THREAD

**Issue by Lotharyx** [cryinkfly/Autodesk-Fusion-360-for-Linux#123]
After installing Fusion 360 under Wine, it gets as far as letting me log into my Fusion 360 account, and then seems to hang for a while before eventually producing Autodesk's crash reporting dialog.  Subsequent attempts to run the program skip over login (assuming it remembers my info) and just crash.

**To Reproduce**
Run the launcher.  I've been pasting the command into a terminal to see output, but it's a massive load of wine messages.

**Expected behavior**
I expect Fusion 360 to run normally.

**Screenshots**
Screenshot of Autodesk crash dialog, for whatever good it does

**Desktop (please complete the following information):**
- Fusion 360 version - don't know, can't get to its about dialog because of this issue
- NVIDIA GeForce GTX 750 Ti, driver version 440.64, CUDA version 10.2
- Debian 10
- XFCE4 4.16
- OpenGL-Mode

Please let me know what other info I need to provide. 

![autodesk_crash](https://user-images.githubusercontent.com/5629932/139943418-a498aa84-ad2c-456a-908a-5bb499a9baf0.png)

**Comment by cryinkfly** [comment]
@Lotharyx Hey , it will be good for me when you can create a log file. Then I can help you better. :+1: 

Here you get more information about creating a log file:
-  https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/wiki/Documentation#developers

For example: 

    xterm -hold -e "cd $HOME/.local/share/fusion360 && bash launcher.sh &> wine-error.log"

**Comment by HaWr1** [comment]
Hi,

i stumbled over the same problem, exactly as described by @Lotharyx. 

**Desktop (please complete the following information):**
- Fusion 360 version - don't know, can't get to its about dialog because of this issue
- NVIDIA Quadro P600, driver version 470.74
- Kubuntu 20.04
- KDE Plasma 5.18.5
- DXVK- or OpenGL-Mode: Installed Fusion360 some time ago. I cant remember what I picked.

Here is my error log:
[wine-error.log](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/files/7492355/wine-error.log)

**Comment by Lotharyx** [comment]
Thank you for your quick engagement!  I have been busy with other things but will try to get a log this week.

**Comment by Lotharyx** [comment]
The launcher.sh script in my ~/.local/share/fusion360 directory doesn't work, so this is the command I used to capture a log.  For some reason, a few lines still escaped to the console despite redirecting both stderr and stdout; I have included them below.

```
env WINEPREFIX="/home/brian/Fusion360" wine C:\\windows\\command\\start.exe /Unix /home/brian/Fusion360/dosdevices/c:/users/Public/Desktop/Autodesk\ Fusion\ 360.lnk > wine-error.log 2>&1
```
Lines that appeared in the terminal anyway:
```
0058:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0058:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
01c4:fixme:mpr:WNetGetUniversalNameW (L"C:\\users\\brian\\Application Data\\Autodesk\\ADPSDK\\bin\\ADPClientService.exe", 0x00000001, 0000000000000000, 000000000186ED00): stub
0194:fixme:mpr:WNetGetUniversalNameW (L"C:\\users\\brian\\Application Data\\Autodesk\\ADPSDK\\bin\\ADPClientService.exe", 0x00000001, 0000000000000000, 000000000021D0F0): stub
0194:fixme:mpr:WNetGetUniversalNameW (L"C:\\users\\brian\\Application Data\\Autodesk\\ADPSDK\\bin\\ADPClientService.exe", 0x00000001, 0000000000000000, 000000000021D0F0): stub
0194:fixme:mpr:WNetGetUniversalNameW (L"C:\\users\\brian\\Application Data\\Autodesk\\ADPSDK\\bin\\ADPClientService.exe", 0x00000001, 0000000000000000, 000000000021D0F0): stub
```
wine-error.log is attached.
[wine-error.log](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/files/7501367/wine-error.log)

I hope this is useful!

**Comment by cryinkfly** [comment]
@Lotharyx I see here:

`env WINEPREFIX="/home/brian/Fusion360" wine C:\\windows\\command\\start.exe /Unix /home/brian/Fusion360/dosdevices/c:/users/Public/Desktop/Autodesk\ Fusion\ 360.lnk > wine-error.log 2>&1
`
... that you use the old way to start Autodesk Fusion 360 on Linux. Can you tell me why? 🙂

Then when you look into this folder:

- https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/tree/main/files/extras/desktop-starter

... you can see the new files. :+1:

**Comment by cryinkfly** [comment]
@HaWr1 I looked at your bug report and I noticed one bug in particular:

- Unable to connect to 127.0.0.1:10080
 
Is it possible that your Linux distro is running on Windows? (https://github.com/microsoft/WSL/discussions/2471)

**Comment by Lotharyx** [comment]
The installer created a desktop launcher; that is the command from the launcher.  I tried launching the way you suggested above, with the "launcher.sh" script in ~/.local/share/fusion360, and it yields the following error:

```
find: ‘/home/brian/.wineprefixes/fusion360’: No such file or directory
wine: chdir to /home/brian/.wineprefixes/fusion360 : No such file or directory
```
I see I need to modify a couple things in that script to fix the paths.  So I did that...and it launched and ran successfully, albeit somewhat sluggishly.  I had rebooted, so I tried "the old way" again and it crashed again.  So the "new way" of starting the application makes a difference (although I am not sure I understand why).

So I guess my situation is fixed.

**Comment by cryinkfly** [comment]
@Lotharyx 

```
find: ‘/home/brian/.wineprefixes/fusion360’: No such file or directory
wine: chdir to /home/brian/.wineprefixes/fusion360 : No such file or directory
```

The problem is your path.

/$HOME/wineprefixes/fusion360 …

I think that you have maybe a old setup wizard on your system maybe?

But when it works now for you then it’s good. 👌

**Comment by Lotharyx** [comment]
Well here's a strange wrinkle:  I changed the desktop launcher to call that script, and it still crashes the same way when I use the desktop launcher, but runs ok when I start the script from a terminal window.  So I changed the launcher to "Run in terminal" and that somehow made it work.  I guess wine does something weird if it doesn't have a parent terminal window.

**Comment by HaWr1** [comment]
> @HaWr1 I looked at your bug report and I noticed one bug in particular:
> 
> * Unable to connect to 127.0.0.1:10080
> 
> Is it possible that your Linux distro is running on Windows? ([microsoft/WSL#2471](https://github.com/microsoft/WSL/discussions/2471))

No I am running on native Kubuntu.

In the meanwhile I did a fresh installation and applied @Lotharyx "run in terminal" approach. This also did the trick for me.

What is strange however: 
bash $HOME/.local/share/fusion360/launcher.sh --> everything works as expected.
bash $HOME/.local/share/fusion360/launcher.sh > ~/wine-error.log --> causes Fusion360 to crash on startup.
