### ISSUE TITLE
"GLXBadFBConfig"-Error on Startup - ZorinOS16 - Intel Core i7-3740QM 

### ISSUE THREAD

**Issue by LukasKraehling** [cryinkfly/Autodesk-Fusion-360-for-Linux#124]
### Problem/Bug:
F360 does not start on my system, I don't see any GUI and the console spits out following errors:
![F360-Startup-Error_ZorinOS16_i7-3740QM](https://user-images.githubusercontent.com/26366928/140070583-4655635e-0c8a-48c5-b5d9-96f187eddd4b.png)

The error happens on both the Vulkan- and OpenGL-Variant.

### My System:
**System:** Dell Latitude E6430
**OS:** ZorinOS16 (64-Bit)
**CPU:** Intel® Core™ i7-3740QM CPU @ 2.70GHz × 8 
**GPU:** Intel® HD Graphics 4000 (IVB GT2)
**RAM:** 8GB

**Comment by cryinkfly** [comment]
Hey @LukasKraehling 👋

Can you check in these folders (Example):

- $HOME/.wineprefixes/fusion360/drive_c/users/$USER/Application Data/Autodesk/Neutron Platform/Options
- $HOME/.wineprefixes/fusion360/drive_c/users/$USER/AppData/Roaming/Autodesk/Neutron Platform/Options

... the NMachineSpecificOptions.xml files if they are correctly configured! :+1: 

[DXVK](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/blob/main/files/DXVK.xml):

![dxvk](https://user-images.githubusercontent.com/79079633/140153727-70c8afa1-87b5-4b4e-aa79-55b6592aae33.png)

[openGL](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/blob/main/files/NMachineSpecificOptions.xml):

![opengl](https://user-images.githubusercontent.com/79079633/140154261-a2d2ddd4-27da-4d1a-bc80-fce4c33ff375.png)

You have a Intel GPU and so you must have the first configuration file. 🙂

**Comment by LukasKraehling** [comment]
![image](https://user-images.githubusercontent.com/26366928/140402814-7efeaeb3-7f5a-47ee-98a3-fa6a9abc95ec.png

Did not help, I tried both APIs before. I copied the DXVK config into the file, but no change.

**Comment by cryinkfly** [comment]
Oh okay, I see thta you have some problems with the GLXBadFBConfig! 😉

Please, check this post here: https://forums.linuxmint.com/viewtopic.php?t=356491

Because there it's described so that you must change or overwrite the MESA_GL_VERSION.

---

For example:
    
![MESA_GL_VERSION_OVERRIDE](https://user-images.githubusercontent.com/79079633/140409355-d9a716ba-bcd2-46e6-8002-c91e0fd9d986.png)

**Comment by LukasKraehling** [comment]
So, I really tried to get at least 4.4 running, but it seems like I can only go up to 4.2...
I think it could be related to Mesa 21.0.3 running on my system.
Any Ideas ?

**Comment by cryinkfly** [comment]
Okay. Can you switch to the newest version (Mesa 21.2.5)?

**Comment by LukasKraehling** [comment]
> Okay. Can you switch to the newest version (Mesa 21.2.5)?

Great ! I was able to upgrade to Mesa 21.2.5 and now F360 starts successfully ! I am still not able to push the MESA_GL_VERSION_OVERRIDE further than 4.2, but I don't need to anymore, so it's all good. :) Thx for the great support !
