### ISSUE TITLE
Gentoo installation reinstalls installed packages *solved*

### ISSUE THREAD

**Issue by thulle** [cryinkfly/Autodesk-Fusion-360-for-Linux#126]
When the installer script installs packages on gentoo with the lines:
 	function gentoo-linux {
	    sudo emerge -av virtual/wine ...
	}

It will reinstall any of those packages that are already installed.
Changing it to "sudo emerge -nav ..." where -n is:
       --noreplace, -n
              Skips the packages specified on the command-line that have already been in‐
              stalled. 

shortens the time to install.

**Comment by cryinkfly** [comment]
@thulle Thank you very much for this information. :+1:
