### ISSUE TITLE
Won't start again after first running *solved*

### ISSUE THREAD

**Issue by thekarinka** [cryinkfly/Autodesk-Fusion-360-for-Linux#129]
**Describe the bug**

When I install Fusion 360 on Ubuntu 21.10 I can run it only once, after one start and closing Fusion it is not possible to start Fusion again.

**To Reproduce**
1. Standard install on ubuntu 21.10
2. Start Fusion
3. Close Fusion
4. Try to start Fusion again - it crashes

**Expected behavior**
Fusion will start

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360: actual stable
- Graphics card model + Graphics card driver (Version number): Radeon
- Operating system Ubuntu 21.10
- Desktop environment Gnome 11
- DXVK- or OpenGL-Mode: OpenGL

**Additional context**

Output of `bash /home/USER/.local/share/fusion360/launcher.sh`
``launcher.sh: line 1: /home/USER/Fusion360: Is a directory``
(and it is true), same result when I try to run via desktop entry.

What else I can try to debug this problem?

Btw.: And thanks for great work! :)

**Comment by thekarinka** [comment]
I tried in Kde Plasma 5.11 and there it works without problem, it looks that it is problem only on Gnome.

**Comment by cryinkfly** [comment]
@thekarinka Thank you for your information. 👍
