### ISSUE TITLE
Can´t uninstall

### ISSUE THREAD

**Issue by mmithoefer** [cryinkfly/Autodesk-Fusion-360-for-Linux#130]
I have found the video of how to uninstall Fusion 360 in the repo. Although i don´t wan´t to remove just the extension but the whole programm. How do i go about that?

**Comment by cryinkfly** [comment]
Hey @mmithoefer 👋🏻,

if you can wait then you can see this and another things tomorrow by the [Tux-Day‘s 2021](https://www.tux-tage.de/programm/) where I have a Live-Presentation! 🙂

**Comment by cryinkfly** [comment]
@mmithoefer Here can you see how it works: https://youtu.be/KTSdsOuuEmY?t=2058

**Comment by mmithoefer** [comment]
Great. Thanks a lot
