### ISSUE TITLE
Can I use the RX 580 graphics card with this? *solved*

### ISSUE THREAD

**Issue by a1projects** [cryinkfly/Autodesk-Fusion-360-for-Linux#131]
Hi, I have been searching for a way to use cad software in linux. I am so excited to see this project exists! I saw there is support for the rx 470. I have an rx 580 and the latest amdgpu driver for ubuntu 21.10. Will I be able to run this on my system?

**Comment by mycelium-networks** [comment]
Also I saw you mentioned wine 5.0.0, 6.0.2 I believe is the current one out. Will it still work?

**Comment by cryinkfly** [comment]
I think 🤔 it works, but it will be better when you testing this and when it works then it’s important that you give us a feedback. 🙂

Important for you:

- https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/128

**Comment by wprojects** [comment]
It works!! It has never crashed on me. However it does freeze me screen up for 20-30 seconds when I resize the window or change tabs to another project
