### ISSUE TITLE
Can't Export STL to my computer

### ISSUE THREAD

**Issue by wprojects** [cryinkfly/Autodesk-Fusion-360-for-Linux#133]
I am running ubuntu 21.10 and the newest version of fusion 360, just installed it yesterday. I keep trying to export my stl files and I can see them in the menu when I try to export the files, but they are no where in my computer. I've searched everywhere, even root. I checked if maybe they were hidden files too. How do I get the stl file to show up? 

No matter where I export it, I can't find it. I've tried home, desktop and documents
![image](https://user-images.githubusercontent.com/57518634/141484112-2f84dbdc-f73e-48fd-891a-1ab12df67984.png)

**Comment by wprojects** [comment]
Update. Oddly enough, you have to select home/Desktop through the / directory. That worked!

**Comment by kavourbm** [comment]
So I was having this same issue, however, I do not have the '/' path option;
![image](https://user-images.githubusercontent.com/122492966/221922824-2f2c0ed7-b5b8-4bb4-81cf-cf28fc6d8782.png)
Therefore, unsure of what to do to save meshes. It appears that initially the 'Documents' path in this window and /home/$USER/drive_c/users/$USER/Documents seemed to match, however adding a file/folder to one doesn't change the other.

Manjaro KDE w/ DX9

**Comment by j4k0xb** [comment]
@kavourbm 
The files get saved here: `$HOME/.fusion360/wineprefixes/default/drive_c`

**Comment by cryinkfly** [comment]
The new path is: $HOME/.autodesk_fusion/wineprefixes/default/drive_c/users/...
