### ISSUE TITLE
Incorrect URL for launcher.sh, script can't proceed.

### ISSUE THREAD

**Issue by Aus-gez** [cryinkfly/Autodesk-Fusion-360-for-Linux#134]
## Bug description
Once the below steps (see To Reproduce) are followed, the script tries to download a file:
https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/raw/main/files/launcher.sh

This file doesn't exist at this location, so gets a 404 response, and causes one of two paths forward depending on the user input:
1. a seemingly infinite loop
2. Saving progress so far, and ending the script.
 
Is the correct file this one?
https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/blob/main/files/extras/desktop-starter/launcher.sh

## To Reproduce
1. Run the script using instructions from the readme. See below:
```sh
cd $HOME && mkdir -p "Fusion360" && cd "Fusion360" && wget -N https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/raw/main/files/scripts/stable-branch/fusion360-setup-wizard.sh && chmod +x fusion360-setup-wizard.sh && bash fusion360-setup-wizard.sh && exit
```
2. Select from the prompt windows:
   1. Repair installation...and let it run.
   2.  Select the location of a previous installation... and let it run.
3. See error in the terminal (see below for exact error). A prompt window appears titled: Autodesk Fusion 360 for Linux - Setup Wizard. There is an empty text box, and a tick box at the bottom labelled: 'I have changed the path of Autodesk Fusion 360!'. From there the user can click 'cancel'  which causes the window to pop up again asking the same question. Or the user can click "ok" after ticking the tick box. The user is asked if they want to save progress. If they choose Ok, they are asked to select the extension they want to install, I selected none, then the script ends. The console says "nothing selected". 

## Desktop
- Ubuntu 20.04
- OpenGL-Mode

## The exact error message

```
2021-11-14 22:11:13 (6.16 MB/s) - '/home/g/.local/share/applications/wine/Programs/Autodesk/Autodesk Fusion 360.desktop’ saved [354/354]

--2021-11-14 22:11:13--  https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/raw/main/files/extras/desktop-starter/launcher.sh
Resolving github.com (github.com)... 13.237.44.5
Connecting to github.com (github.com)|13.237.44.5|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/extras/desktop-starter/launcher.sh [following]
--2021-11-14 22:11:13--  https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/extras/desktop-starter/launcher.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1356 (1.3K) [text/plain]
Saving to: '/home/g/.local/share/fusion360/launcher.sh.1’

launcher.sh.1       100%[===================>]   1.32K  --.-KB/s    in 0s      

2021-11-14 22:11:14 (21.7 MB/s) - '/home/g/.local/share/fusion360/launcher.sh.1’ saved [1356/1356]

--2021-11-14 22:11:14--  https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/raw/main/files/launcher.sh
Resolving github.com (github.com)... 13.237.44.5
Connecting to github.com (github.com)|13.237.44.5|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-11-14 22:11:15 ERROR 404: Not Found.

```
## PS
Totally fantastic script! Thank you for all your work on this! :-)

**Comment by cryinkfly** [comment]
@Aus-gez Thank you for this information! :+1:

**Comment by Aus-gez** [comment]
Wow! Thanks for the speedy resolution!
