### ISSUE TITLE
Setup wizard stuck in a loop

### ISSUE THREAD

**Issue by GoTVm** [cryinkfly/Autodesk-Fusion-360-for-Linux#137]
**Describe the bug**
I used the all-in-one command. Once the setup wizard finishes the download, it starts the installation routine. It asks me which language I want Fusion to be installed in, then what graphic driver to use and then what distro I'm on. Once I select everything, it moves to terminal and, once it ends, it goes back to the beginning of the installation routine. Another thing I noticed is if I try to manually run the .sh file, it tells me there is an unexpected } somewhere. I don't know if that's supposed to happen, but I feel like it's worth mentioning.

**To Reproduce**
I tried installing it as both graphic driver options, since I have an Intel GPU, whereas as distro I chose both Debian 11 and Ubuntu 20.04, all without success.

**Expected behavior**
Proper installation.

**Desktop (please complete the following information):**
- Latest version of Autodesk Fusion 360
- Intel Graphics 4600 (12GB RAM), driver i915 (please correct me if this is not what driver version means)
- Elementary OS 6, based on Ubuntu 20.04.3
- Pantheon
- inxi -G says OpenGL, I tried both

**Comment by steveunixson** [comment]
same on ubuntu 20.04

**Comment by GoTVm** [comment]
I got it to install by using the development branch instead of the stable branch, the one with flatpak. I installed everything manually (flatpak-...sh first and fusion...sh last), all without sudo.
 I installed it using Arch/Manjaro as a distro, though I'm on elementary. Anything else but Arch sends the installer into a loop. Once installed, you should find it in your home/.wineprefixes folder.

Though it is installed, it won't open. It will stay on a white page forever and never load. I'll try to install it the same way I did it today (using Arch instead of Ubuntu) with the stable version.

**Comment by cryinkfly** [comment]
First of all, thank you for your feedback. :+1: 

But it still amazes me, since I only recently had the whole thing successfully installed under Linux Mint 20.2 and without any problems. 🙂

I'll take a look at everything. 🧐

**Comment by GoTVm** [comment]
I went back to square one: uninstalled everything to see if the stable-branch version works. I was getting a couple of issues with libraries when I launched Autodesk Fusion 360 (the terminal window that appears says I'm missing DXVA_video_decode_accelerator_win.cc, msvproc.dll and a couple more but I have no idea where to get them), and then it would go blank and crash after a while. It looks like a couple of other issues I found here, but none of them seem to help. 

Right now I'm investigating my graphics driver, since there are no Intel HD 4600 Graphics drivers to be downloaded.

**Comment by cryinkfly** [comment]
If you have installed the newest mesa version?

**Comment by GoTVm** [comment]
Just did it:
OpenGL version string: 3.0 Mesa 21.2.2

**Comment by cryinkfly** [comment]
So of course it could be that the servers of the winetricks packages were down again.

**Comment by GoTVm** [comment]
I've been trying for the past 14 hours, could they have been down for so long? I admit this is the first time I'm working with Wine seriously.

I'm currently trying to reinstall from the stable branch, using the all-in-one command, this time going with Debian 11 to see if it makes a change. I suspect choosing Arch might have made it work, but wasn't the best possible choice as I'm sure there are some underlying differences between Elementary OS and Arch.

**Comment by cryinkfly** [comment]
It has happened before.

Can you perhaps create a detailed log file for me by switching to the installation folder and executing the following command:

    bash fusion360-setup-wizard.sh &> wine.error.log

**Comment by GoTVm** [comment]
I just restarted the installation, if it doesn't work I'll create the log.

Even if I uninstalled it completely before reinstalling the stable version, it still asked me if I wanted to install some components, update or uninstall. I even made sure nothing was left from the previous installation. Is that normal?

**Comment by cryinkfly** [comment]
Yes, this normal. You must delete the path.log here: $HOME/.local/share/fusion360/logfiles/

**Comment by GoTVm** [comment]
Last installation didn't work (it prompted me to change the launcher script, but I don't know where it is since it doesn't appear if I search for Fusion 360), so I deleted log-path and it's currently running and dumping all info in the wine.error.log. I changed the default installation path to the Fusion360 folder the script creates.

**Comment by GoTVm** [comment]
Installation is complete again. It once again prompts me to change the launcher but doesn't specify how to. Wine also reported a streamer.exe crash twice. Before closing the last prompt I'll have to figure out how to change the launcher path or I won't be able to open it.

**Comment by cryinkfly** [comment]
I'll take a look at everything again and see if a few things may need to be changed.

![Bildschirmfoto_2021-11-21_10-54-36](https://user-images.githubusercontent.com/79079633/142757407-7cecbe8a-c24d-4893-a02f-96952bfc8363.png)

**Comment by GoTVm** [comment]
[wine.error.log](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/files/7576033/wine.error.log)
This is the wine.error.log. Hopefully it's useful. I'll try just one last clean install and then I'll wait

**Comment by cryinkfly** [comment]
So I noticed that you got an error when configuring DXVK / openGL! The installation of Autodesk Fusion 360, specifically the Fusion360installer.exe, does not start at all.

This bug is new! At the moment I don't know why, because at first glance my code seems to be okay.

However, I will now revise certain variable names. Perhaps that could lead to this error in one system or another.

I thank you for your help! :+1:

**Comment by GoTVm** [comment]
Well good to know I could be of help, in one way or another. I'll still try to find a solution in the meantime. Currently stuck on Wine telling me it cant find System32, for some reason.

Do you know how I could go about **completely** removing everything that has to do with the installation routine/script? So that I could start anew from a fresh base.

**Comment by cryinkfly** [comment]
Yes, the best thing to do is to delete the Wineprefix (folder) from Autodesk Fusion 360 and install Autodesk Fusion 360 step by step itself.

**Comment by GoTVm** [comment]
One thing I might suggest: could it be that the Ubuntu 20.04 installation routine is broken? All the other choices work, only Ubuntu 20.04 doesn't. Another commenter also reported that their Ubuntu 20.04 installation does the same thing. Maybe all of this is just because there is a mistake in the launcher that loops the Ubuntu 20.04 installation?

**Comment by cryinkfly** [comment]
That would be possible. But why does it then work under Linux Mint 20.2 that Ubuntu 20.04 uses.

**Comment by GoTVm** [comment]
After two more attempts I have officially given up. There is nothing more that I am capable of doing, I'll leave it in your expert hands. 

Last thing I can try is follow the latest tutorial you uploaded on YouTube and see if I'm doing anything wrong.

**Comment by cryinkfly** [comment]
I have changed a function: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/commit/2a056c4e0bb8e6b7bf50e0ed305db5366c42f188

**Comment by GoTVm** [comment]
Do I try to install from your all-in-one command now? I'm currently following your tutorial and I noticed you recommend "Latest wine version", so I'm installing Wine by hand now.

**Comment by cryinkfly** [comment]
YES :+1: 

> Do I try to install from your all-in-one command now?

Then with this with this new log file I get all informations about the processes and so on.

**Comment by GoTVm** [comment]
Sorry to always be the bearer of bad news, but while installing linux-libc-dev the installer halted and the only way to know was opening the log to see the [y/n] prompt. Maybe add -y as an argument to the function so it doesn't wait for user approval?

**Comment by GoTVm** [comment]
[setupact.log](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/files/7576285/setupact.log)
Setup log here.

Down here is everything Wine dumps on me while trying to open. Fixed launcher.sh missing, new errors appeared
![Screenshot from 2021-11-21 14-03-42](https://user-images.githubusercontent.com/66179613/142762968-65bf6c29-1f96-4292-aca4-3a6ae68efde7.png)
.

**Comment by tome9111991** [comment]
Hello i'm und Mint 20.04
on a Lenovo Z50 with intel HD graphics & Nvidia 840M
i have also loop 

used:
> I have changed a function: [2a056c4](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/commit/2a056c4e0bb8e6b7bf50e0ed305db5366c42f188)

but not help,

**Comment by GoTVm** [comment]
@tome9111991 Its not meant to help the installation, rather to help you see what the issue is. It creates a setup log and nothing more. I might be close to solving the issue but I don't understand where the Fusion360.exe file is located, therefore I'm waiting for cryinkfly's insight on that. In the meantime, you could try another distro that's close to yours (Debian if you're on Ubuntu and so on).

**Comment by cryinkfly** [comment]
The Fusion360.exe file is located here: $HOME/Fusion360/data/fusion360/Fusion360installer.exe

**Comment by GoTVm** [comment]
That's the file launcher.sh should launch, right? Because it currently tries to launch **.exe**, located in system32, as my screenshot shows.

**Comment by cryinkfly** [comment]
@GoTVm Your setupact.log is not complete?

**Comment by GoTVm** [comment]
That is all it gave me. It then asked me if I wanted standard installation or to change the path and then completed.

**Comment by cryinkfly** [comment]
Please wait 🙂. Then I change a lot of variables and functions. I hope to finish tomorrow. 🤔

**Comment by GoTVm** [comment]
Oh yea take your time, absolutely no pressure. I already have fusion on my other windows machine, so I'm not in a hurry. I'll try again and see if I can edit launcher.sh to point to the correct executable.

**Comment by GoTVm** [comment]
I found out two more issues with the script:
1) You can't dump the whole installation into the log, because it brings up some prompts that halt the whole installation process until you press y or enter, and you wont know until you go dig into 15000 lines of dumped logs;
2) Something about the script messes up wine and its repositories, making it impossible to install winehq-staging. Might want to look into that, I had to format my computer to get winehq-staging to work.

**Comment by steveunixson** [comment]
guys, i've managed to install it using an old branch (pseudo-ui one)
zeniny script looks good at the fist glance
need more time to investigate

**Comment by steveunixson** [comment]
@cryinkfly  maybe lets investigate into creating an appimage with wine and all the necessary scripts (possibly written in something other than bash, python? idk)
And for drivers, support packages, etc --> move that to distro specific scripts (or even figure out how to squeeze them into an appimage)
Idea is similar to [portwine](https://portwine-linux.ru/port-wargaming-game-center/) project 
Legal notice: WE DO NOT DOING TO REDISTIBUTE ORGINAL Fusion360!! It's just an installer that downloads original .exe

**Comment by cryinkfly** [comment]
## I have solved this bug now! 

> Setup wizard stuck in a loop

**Comment by GoTVm** [comment]
Why was the issue closed? The only way I managed to solve this issue is dualboot windows. It won't install in Elementary, neither will it install in Ubuntu 21.10. Did I miss something?

**Comment by steveunixson** [comment]
> Please remove all old files & wineprefixes!
@cryinkfly atleast include that into a script

**Comment by GoTVm** [comment]
I did remove all the files and wineprefixes, and I also agree that it should be automatically handled by the uninstall script. I'll whip out my old Ubuntu machine and see if it works there. It's quite old (i5 2nd gen, no GPU), do you think it would work?

**Comment by cryinkfly** [comment]
I have changed a lot of things in the setup file and also the command to install:

    mkdir -p "$HOME/.wineprefixes/fusion360/INSTALLDIR" && cd "$HOME/.wineprefixes/fusion360/INSTALLDIR" && wget -N https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/raw/main/files/scripts/stable-branch/fusion360-setup-wizard.sh && chmod +x fusion360-setup-wizard.sh && bash fusion360-setup-wizard.sh && exit

I have installed this in a virtual machine and it works:

https://user-images.githubusercontent.com/79079633/143010203-3e09beb0-34dd-4ed8-b4c8-ac88848dd2df.mp4

**Comment by GoTVm** [comment]
Right, forgot about the existence of virtual machines. I'll try it on a Ubuntu 21.10 virtual machine in a couple of hours. Did you by chance handle the wine issue? Your script probably messes with the wine repositories, so if you didn't install winehq-staging before ever running the script you won't be able to due to "broken packages".

**Comment by cryinkfly** [comment]
I am currently working on a dialog for Wine, where you can install wine also from the standard repository of your system.

**Comment by steveunixson** [comment]
@cryinkfly maybe let's download wine to user directory instead of installing wine-staging packages using apt?
and also don't you mind me forking your repo? I have a lot of ideas how to improve stability and user experience

**Comment by GoTVm** [comment]
Alright, good that you managed to fix one problem at least. For now, I'll install wine separately and test.

**Comment by cryinkfly** [comment]
@steveunixson I don't mind if you fork my repo? It is only important to me that everyone has the opportunity to use it for other projects and that I am mentioned (see license terms).

**Comment by cryinkfly** [comment]
@GoTVm But I have to say it was a bit tricky to change it. ^^

**Comment by cryinkfly** [comment]
@GoTVm If the problem occurs again for the purpose of looping, then it will be good when you open the case again here.

**Comment by GoTVm** [comment]
Sure will. I'll also keep track of the steps I take from a fresh install, so it can be replicated.

**Comment by GoTVm** [comment]
Just tried and sadly it didnt work. It didn't loop, but it also didn't install anything. I don't have the Autodesk folder in the drive_c folder, as you show in the video. I did this on a fresh Ubuntu install on a VM, following these steps:
- sudo apt update
- sudo apt upgrade
- install winehq-staging
- install zenity and xterm
- run the command

In the end, I had no Autodesk folder and Fusion didn't appear in the application menu.

**Comment by tome9111991** [comment]
i tested the new script 
i don't have issue

**Comment by GoTVm** [comment]
I must be doing something wrong then. It's weird that even on a fresh install I couldn't get it to install. I did everything that's listed, which is what I wrote in the previous comment. Can you confirm it's what you did too?

**Comment by tome9111991** [comment]
I just run `mkdir -p "$HOME/.wineprefixes/fusion360/INSTALLDIR" && cd "$HOME/.wineprefixes/fusion360/INSTALLDIR" && wget -N https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/raw/main/files/scripts/stable-branch/fusion360-setup-wizard.sh && chmod +x fusion360-setup-wizard.sh && bash fusion360-setup-wizard.sh && exit`

**Comment by GoTVm** [comment]
That didn't work, I tried many times over. I'm at my wits' end. I think I'm doing something wrong but have no way to certify what I'm doing, so for now I'm currently stuck.

**Comment by cryinkfly** [comment]
@GoTVm Wait ...

> **Intel Graphics 4600*** (12GB RAM), **driver i915** (please correct me if this is not what driver version means)

Can you please tell me again which version of Mesa is installed on your system with this command?

    glxinfo | grep "OpenGL version"

*Notice: Your Intel GPU may not be properly[ supported](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/wiki/Supported-Graphics-Cards).

**Comment by GoTVm** [comment]
Mesa version 21.2.2 on both machines. I still think the issue is that Fusion360installer.exe doesn't run. I never seem to find its installation folder, as you show in your video; also, I don't have Fusion360.exe.

**Comment by cryinkfly** [comment]
Please run this command:

    mkdir -p "$HOME/.wineprefixes/fusion360/INSTALLDIR" && cd "$HOME/.wineprefixes/fusion360/INSTALLDIR" && wget https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Admin%20Install.exe -O Fusion360installer.exe && mkdir -p data/fusion360 && mv Fusion360installer.exe data/fusion360/Fusion360installer.exe && && wget -N https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/raw/main/files/scripts/stable-branch/fusion360-setup-wizard.sh && chmod +x fusion360-setup-wizard.sh && bash fusion360-setup-wizard.sh && exit

**Comment by GoTVm** [comment]
I did and still there is no Fusion360.exe... Nowhere in the folders that you show in the video; the find command also doesn't find any .exe file.

**Comment by tome9111991** [comment]
> I did and still there is no Fusion360.exe... Nowhere in the folders that you show in the video; the find command also doesn't find any .exe file.

Maybe possible to record the screen when you run the command?

**Comment by cryinkfly** [comment]
Open this link: https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Admin%20Install.exe
