### ISSUE TITLE
App do not run

### ISSUE THREAD

**Issue by Caraffa-git** [cryinkfly/Autodesk-Fusion-360-for-Linux#138]
When i run app via konsole i get error: "wine: failed to open "C:\\\\users\\\\Public\\\\Desktop\\\\Autodesk\\": c0000135". I couldn't really find any info about that.

**Comment by cryinkfly** [comment]
Run this command:

    launcher="$(find $HOME/.wineprefixes/fusion360 -name Fusion360.exe -printf "%T+ %p" | sort -r 2>&1 | head -n 1 | sed -r 's/.+0000000000 (.+)/\1/')" && WINEPREFIX="$HOME/.wineprefixes/fusion360" wine "$launcher"

**Comment by Caraffa-git** [comment]
There is no .wineprefixes directory
```
find: ‘/home/rafaln/.wineprefixes/fusion360’: No such file or directory
wine: chdir to /home/rafaln/.wineprefixes/fusion360 : No such file or directory
```
