### ISSUE TITLE
Can't get fusion to launch.

### ISSUE THREAD

**Issue by builderdev212** [cryinkfly/Autodesk-Fusion-360-for-Linux#141]
I came across this nifty project while browsing through github, and I thought I would give it a try. I would like to preface this with the fact that I have no experience with wine. The installation command ran fine, and nothing errored out while it was trying to install. However, when I tried to run the program I was greeted with the image attached.
![fusion_error](https://user-images.githubusercontent.com/93960938/143517654-0f373476-e052-4bd0-82ab-e066687604ac.png)
I ran 
> xterm -hold -e "/home/builder212/.local/applications/wine/Programs/Autodesk/fusion360-launcher.sh"

to achieve this. The autogenerated menu entry looked like this:
> xterm -hold -e "./home/builder212/.local/applications/wine/Programs/Autodesk/fusion360-launcher.sh"

I'm certain this is most likely something I have configured incorrectly, but I'm not certain what that config issue could be. It is also possible that I missed another issue going over this exact issue, and if so my apologies. Any help would be appreciated.

**Comment by smirgol** [comment]
What operating system are you on? Maybe you're experiencing the same error as I did, where some things did not install properly.

**Comment by builderdev212** [comment]
I'm running on kubuntu 21.10. It is most certainly possible that I didn't install something beforehand as well. My wine installation could be an issue, but I have yet to figure out why.

**Comment by smirgol** [comment]
Ah yes, then you have run into the same issue as me. I've created a ticket for that issue: [Ticket](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/142#issue-1064361167).

Basically you need to edit the install script `fusion360-setup-wizard.sh`, search for `function ubuntu21_10` and right before the closing bracket insert `cd $HOME/.wineprefixes/fusion360/INSTALLDIR/`. It should look like this in the end:

```
function ubuntu21_10 {
    # Note: See the description in the function ubuntu21!
    sudo apt-get update
    sudo apt-get upgrade
    sudo dpkg --add-architecture i386
    mkdir -p /tmp/360 && cd /tmp/360
    wget https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_21.04/Release.key
    wget https://dl.winehq.org/wine-builds/winehq.key
    gpg --no-default-keyring --keyring ./temp-keyring.gpg --import Release.key
    gpg --no-default-keyring --keyring ./temp-keyring.gpg --export --output opensuse-wine.gpg && rm temp-keyring.gpg
    gpg --no-default-keyring --keyring ./temp-keyring.gpg --import winehq.key
    gpg --no-default-keyring --keyring ./temp-keyring.gpg --export --output winehq.gpg && rm temp-keyring.gpg
    sudo mv *.gpg /etc/apt/trusted.gpg.d/ && cd /tmp && sudo rm -rf 360
    echo "deb [signed-by=/etc/apt/trusted.gpg.d/opensuse-wine.gpg] https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_21.10/ ./" | sudo tee -a /etc/apt/sources.list.d/opensuse-wine.list
    sudo add-apt-repository -r 'deb https://dl.winehq.org/wine-builds/ubuntu/ impish main'
    cd $HOME/.wineprefixes/fusion360/INSTALLDIR/
}
```
The last line is the fix. Save and reinstall, it should then work.

**Comment by builderdev212** [comment]
Thank you very much for the help! Your fix to the script did work, and it installed fusion without a hitch, though it did show some warnings that I don't believe were important. Fusion now loads with the script you gave, but it returns this error whenever I try opening the side menu.
![error2](https://user-images.githubusercontent.com/93960938/143657747-77cf1e38-38cd-454e-8a51-ac5145037bbb.png)
Once again, thank you very much for help on how to fix this, as I was very much in the dark before :P

**Comment by smirgol** [comment]
Yeah I have that too. It still kind of works when I click that message away a couple of times, though.

Also, Fusion crashes when I try to create a new save and use the drop-down to select a different project folder under "Position". Just give your project a name and hit save without selecting a different project folder.

Besides that, it tends to crash once in a while but works pretty good otherwise. Just save often and you should be good. :)

**Comment by builderdev212** [comment]
Hm, well you're right, it appears that it does go away and work after it happening a few times. Thanks for all the help! Most certainly couldn't have done it would you. :D
