### ISSUE TITLE
program AdCefWebBrowser_dpiAware.exe has encountered a serious problem

### ISSUE THREAD

**Issue by vikingsraven** [cryinkfly/Autodesk-Fusion-360-for-Linux#144]
Fusion 360 was working fine, been working away from home got back, wine did an update and now i get this on boot up!
### program AdCefWebBrowser_dpiAware.exe has encountered a serious problem
Fusion then opens but wont display the left side bar showing projects.

Program Error Details below
`Unhandled exception: page fault on write access to 0x000000000e9c0040 in 64-bit code (0x00000000680b2e66).
Register dump:
 rip:00000000680b2e66 rsp:000000000da3f368 rbp:0000000000000191 eflags:00010202 (  R- --  I   - - - )
 rax:00000000ff000000 rbx:00000000ffffffff rcx:0000000000000004 rdx:00000000000000ff
 rsi:00007f4c145ada84 rdi:000000000e9c0044  r8:0000000000000192  r9:000000000e9c0040 r10:00007f4c145ada80
 r11:000000000e9c0040 r12:000000006810f000 r13:00007f4c1e79b240 r14:0000000000000000 r15:0000000000000001
Stack dump:
0x000000000da3f368:  00000000145ada80 000000000e9c0040
0x000000000da3f378:  000000000da3f4b0 00000000000003f7
0x000000000da3f388:  000000001e79b82d 0000000000000192
0x000000000da3f398:  0000000000000000 00000000148a9590
0x000000000da3f3a8:  000000000da3f4b0 000000006810f000
0x000000000da3f3b8:  00000000145a9450 000000001e79b7d0
0x000000000da3f3c8:  0000000000000000 0000000000000000
0x000000000da3f3d8:  000000001e7a5841 0000000000000000
0x000000000da3f3e8:  0000000000000000 000000000000004f
0x000000000da3f3f8:  0000000000000005 0000000000000000
0x000000000da3f408:  0000000000000000 0000000000000000
0x000000000da3f418:  0000000014583020 0000000000000000
Backtrace:
=>0 0x00000000680b2e66 (0x0000000000000191)
0x00000000680b2e66: movl	%ebx,0xfffffffffffffffc(%rdi)
Modules:
Module	Address					Debug info	Name (199 modules)
PE	           10000-           13000	Deferred        api-ms-win-core-errorhandling-l1-1-0
PE	          250000-          265000	Deferred        acipcx64
PE	          270000-          843000	Deferred        mfc140u
PE	          850000-          944000	Deferred        ucrtbase
PE	          950000-          953000	Deferred        api-ms-win-core-file-l1-2-0
PE	          960000-          963000	Deferred        api-ms-win-core-profile-l1-1-0
PE	          970000-          987000	Deferred        vcruntime140
PE	          990000-          994000	Deferred        api-ms-win-crt-runtime-l1-1-0
PE	          9a0000-          9a3000	Deferred        api-ms-win-crt-heap-l1-1-0
PE	          9b0000-          9b4000	Deferred        api-ms-win-crt-stdio-l1-1-0
PE	          9c0000-          9c5000	Deferred        api-ms-win-crt-math-l1-1-0
PE	          9d0000-          9d3000	Deferred        api-ms-win-crt-time-l1-1-0
PE	          9e0000-         135e000	Deferred        user32
PE	         1360000-         15ae000	Deferred        setupapi
PE	         15b0000-         1b6d000	Deferred        ole32
PE	         1b70000-         2093000	Deferred        oleaut32
PE	         20a0000-         213d000	Deferred        msvcp140
PE	         2140000-         2143000	Deferred        api-ms-win-crt-locale-l1-1-0
PE	         2150000-         8050000	Deferred        libcef
PE	         8050000-         9046000	Deferred        shell32
PE	         9050000-         959b000	Deferred        comctl32
PE	         95a0000-         9753000	Deferred        winmm
PE	         9760000-         978a000	Deferred        userenv
PE	         97a0000-         9833000	Deferred        chrome_elf
PE	         9840000-         9893000	Deferred        credui
PE	         98a0000-         9c0d000	Deferred        crypt32
PE	         9c10000-         9cc3000	Deferred        secur32
PE	         9cd0000-         a040000	Deferred        urlmon
PE	         a040000-         a08d000	Deferred        jsproxy
PE	         a090000-         a3a8000	Deferred        d3d11
PE	         ca00000-         cc88000	Deferred        mf
PE	         cc90000-         ceb3000	Deferred        mfplat
PE	         cec0000-         d311000	Deferred        d3dcompiler_47
PE	         d320000-         d6eb000	Deferred        libglesv2
PE	         d6f0000-         d70b000	Deferred        libegl
PE	        61300000-        6138e000	Deferred        iphlpapi
PE	        61480000-        61483000	Deferred        api-ms-win-core-processthreads-l1-1-0
PE	        61540000-        6166c000	Deferred        advapi32
PE	        61740000-        619c3000	Deferred        wininet
PE	        61d00000-        61d04000	Deferred        api-ms-win-crt-convert-l1-1-0
PE	        61fc0000-        61fc3000	Deferred        api-ms-win-core-interlocked-l1-1-0
PE	        62080000-        62083000	Deferred        api-ms-win-core-libraryloader-l1-1-0
PE	        62640000-        62643000	Deferred        api-ms-win-core-processenvironment-l1-1-0
PE	        62740000-        62743000	Deferred        api-ms-win-core-synch-l1-1-0
PE	        62780000-        62783000	Deferred        api-ms-win-core-util-l1-1-0
PE	        62980000-        6298f000	Deferred        api-ms-win-core-localization-l1-2-1
PE	        62b40000-        62b43000	Deferred        api-ms-win-crt-environment-l1-1-0
PE	        62cc0000-        62cde000	Deferred        ncrypt
PE	        62dc0000-        63081000	Deferred        rpcrt4
PE	        63280000-        632a0000	Deferred        version
PE	        635c0000-        636df000	Deferred        oleacc
PE	        639c0000-        63a14000	Deferred        shcore
PE	        63c00000-        63c03000	Deferred        api-ms-win-core-debug-l1-1-0
PE	        63e80000-        63e83000	Deferred        api-ms-win-core-processthreads-l1-1-1
PE	        64800000-        64803000	Deferred        api-ms-win-core-localization-l1-2-0
PE	        64840000-        64991000	Deferred        shlwapi
PE	        64d00000-        64d03000	Deferred        api-ms-win-core-sysinfo-l1-1-0
PE	        65380000-        653af000	Deferred        wtsapi32
PE	        65b40000-        65b43000	Deferred        api-ms-win-crt-filesystem-l1-1-0
PE	        65d40000-        65d69000	Deferred        kerberos
PE	        66040000-        6608f000	Deferred        bcrypt
PE	        661c0000-        662bb000	Deferred        winspool
PE	        66440000-        66443000	Deferred        api-ms-win-core-file-l2-1-0
PE	        664c0000-        664f2000	Deferred        hid
PE	        66540000-        66576000	Deferred        rtworkq
PE	        66900000-        6695d000	Deferred        win32u
PE	        67600000-        67603000	Deferred        api-ms-win-core-string-l1-1-0
PE	        67640000-        67652000	Deferred        psapi
PE	        67780000-        67783000	Deferred        api-ms-win-core-datetime-l1-1-0
PE	        67a00000-        67a03000	Deferred        api-ms-win-core-handle-l1-1-0
PE	        67a80000-        67c2a000	Deferred        d3d9
PE	        68100000-        68103000	Deferred        api-ms-win-core-timezone-l1-1-0
PE	        68300000-        6849d000	Deferred        combase
PE	        68500000-        685c1000	Deferred        uxtheme
PE	        686c0000-        68761000	Deferred        netapi32
PE	        68c00000-        68c24000	Deferred        aclui
PE	        69400000-        69532000	Deferred        winhttp
PE	        69740000-        697c8000	Deferred        propsys
PE	        69e40000-        69eb8000	Deferred        msacm32
PE	        6a080000-        6a39b000	Deferred        msvcrt
PE	        6a840000-        6a84f000	Deferred        usp10
PE	        6aa80000-        6aa8e000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	        6b300000-        6b30e000	Deferred        api-ms-win-core-localization-obsolete-l1-2-0
PE	        6b7c0000-        6b7e0000	Deferred        dhcpcsvc
PE	        6b980000-        6b983000	Deferred        api-ms-win-core-console-l1-1-0
PE	        6ba00000-        6bad0000	Deferred        sechost
PE	        6bc40000-        6bf98000	Deferred        dwrite
PE	        6c540000-        6c6cc000	Deferred        cryptui
PE	        6c7c0000-        6ca1f000	Deferred        gdi32
PE	        6cbc0000-        6cbc3000	Deferred        api-ms-win-core-namedpipe-l1-1-0
PE	        6d580000-        6d619000	Deferred        ws2_32
PE	        6d680000-        6d6c8000	Deferred        msv1_0
PE	        6db80000-        6db9e000	Deferred        wevtapi
PE	        6dc80000-        6dc83000	Deferred        api-ms-win-core-synch-l1-2-0
PE	        6dfc0000-        6dfc3000	Deferred        api-ms-win-core-rtlsupport-l1-1-0
PE	        6e2c0000-        6e309000	Deferred        dnsapi
PE	        6e640000-        6e644000	Deferred        api-ms-win-core-file-l1-1-0
PE	        6e9c0000-        6e9c3000	Deferred        api-ms-win-core-memory-l1-1-0
PE	        6ea40000-        6ea60000	Deferred        dwmapi
PE	        6eb40000-        6eb43000	Deferred        api-ms-win-crt-utility-l1-1-0
PE	        6f280000-        6f2a1000	Deferred        nsi
PE	        6f2c0000-        6f39b000	Deferred        wintrust
PE	        6f400000-        6f405000	Deferred        api-ms-win-crt-multibyte-l1-1-0
PE	        6f880000-        6fb6a000	Deferred        dbghelp
PE	        6fd00000-        6fd04000	Deferred        api-ms-win-crt-string-l1-1-0
PE	        6fd80000-        6fd8e000	Deferred        api-ms-win-core-datetime-l1-1-1
PE	        703c0000-        703c3000	Deferred        api-ms-win-core-heap-l1-1-0
PE	        70740000-        707a7000	Deferred        mpr
PE	        70b00000-        70dab000	Deferred        comdlg32
PE	        71000000-        7105d000	Deferred        imm32
PE	        710c0000-        71128000	Deferred        dxva2
ELF	        7a800000-        7aa15000	Deferred        opengl32<elf>
  \-PE	        7a850000-        7aa15000	\               opengl32
PE	        7b000000-        7b3d5000	Deferred        kernelbase
PE	        7b600000-        7b967000	Deferred        kernel32
PE	        7bc00000-        7bf5d000	Deferred        ntdll
ELF	        7d000000-        7d005000	Deferred        <wine-loader>
PE	       140000000-       140012000	Deferred        adcefwebbrowser_dpiaware
PE	       180000000-       18007e000	Deferred        adcefwebkit
ELF	    7f4c1dd39000-    7f4c1fdf4000	Deferred        libnvidia-glcore.so.470.82.00
ELF	    7f4c1fdf9000-    7f4c1fffe000	Deferred        libnvidia-tls.so.470.82.00
ELF	    7f4c24139000-    7f4c2414d000	Deferred        libdrm.so.2
ELF	    7f4c24151000-    7f4c243f4000	Deferred        libnvidia-glsi.so.470.82.00
ELF	    7f4c243f9000-    7f4c24736000	Deferred        libglx_nvidia.so.0
ELF	    7f4c24739000-    7f4c2476d000	Deferred        libglx.so.0
ELF	    7f4c24771000-    7f4c24829000	Deferred        libgldispatch.so.0
ELF	    7f4c248d1000-    7f4c24959000	Deferred        libgl.so.1
ELF	    7f4c24961000-    7f4c2497e000	Deferred        libxcb-glx.so.0
ELF	    7f4c24981000-    7f4c249a4000	Deferred        libgpg-error.so.0
ELF	    7f4c249a9000-    7f4c24ac7000	Deferred        libgcrypt.so.20
ELF	    7f4c24ac9000-    7f4c24aea000	Deferred        liblz4.so.1
ELF	    7f4c24af1000-    7f4c24b1a000	Deferred        liblzma.so.5
ELF	    7f4c24b21000-    7f4c24b2d000	Deferred        libffi.so.7
ELF	    7f4c24b31000-    7f4c24be0000	Deferred        libsystemd.so.0
ELF	    7f4c24be1000-    7f4c24be8000	Deferred        libkeyutils.so.1
ELF	    7f4c24be9000-    7f4c24c6d000	Deferred        libgmp.so.10
ELF	    7f4c24c71000-    7f4c24ca8000	Deferred        libhogweed.so.5
ELF	    7f4c24ca9000-    7f4c24ce3000	Deferred        libnettle.so.7
ELF	    7f4c24ce9000-    7f4c24cff000	Deferred        libtasn1.so.6
ELF	    7f4c24d01000-    7f4c24e83000	Deferred        libunistring.so.2
ELF	    7f4c24e89000-    7f4c24eaa000	Deferred        libidn2.so.0
ELF	    7f4c24eb1000-    7f4c24fe7000	Deferred        libp11-kit.so.0
ELF	    7f4c24fe9000-    7f4c2503a000	Deferred        libdbus-1.so.3
ELF	    7f4c25041000-    7f4c25050000	Deferred        libkrb5support.so.0
ELF	    7f4c25051000-    7f4c25058000	Deferred        libcom_err.so.2
ELF	    7f4c25059000-    7f4c2508a000	Deferred        libk5crypto.so.3
ELF	    7f4c25091000-    7f4c2516e000	Deferred        libkrb5.so.3
ELF	    7f4c25171000-    7f4c25347000	Deferred        libgnutls.so.30
ELF	    7f4c25349000-    7f4c2535c000	Deferred        libavahi-client.so.3
ELF	    7f4c25361000-    7f4c2536f000	Deferred        libavahi-common.so.3
ELF	    7f4c25371000-    7f4c253be000	Deferred        libgssapi_krb5.so.2
ELF	    7f4c253c1000-    7f4c2545c000	Deferred        libcups.so.2
ELF	    7f4c25461000-    7f4c25469000	Deferred        libxfixes.so.3
ELF	    7f4c25469000-    7f4c25476000	Deferred        libxcursor.so.1
ELF	    7f4c25479000-    7f4c2548b000	Deferred        libxi.so.6
ELF	    7f4c25491000-    7f4c25496000	Deferred        libxcomposite.so.1
ELF	    7f4c25499000-    7f4c256a3000	Deferred        libxrender.so.1
ELF	    7f4c256b9000-    7f4c256be000	Deferred        msv1_0.so
ELF	    7f4c256c1000-    7f4c256ca000	Deferred        kerberos.so
ELF	    7f4c256d1000-    7f4c256eb000	Deferred        libbsd.so.0
ELF	    7f4c256f1000-    7f4c256f9000	Deferred        libxdmcp.so.6
ELF	    7f4c256f9000-    7f4c256ff000	Deferred        libxau.so.6
ELF	    7f4c25701000-    7f4c2572b000	Deferred        libxcb.so.1
ELF	    7f4c25731000-    7f4c2586e000	Deferred        libx11.so.6
ELF	    7f4c25871000-    7f4c25886000	Deferred        libxext.so.6
ELF	    7f4c25891000-    7f4c2589e000	Deferred        libxrandr.so.2
ELF	    7f4c258a1000-    7f4c258a8000	Deferred        libxxf86vm.so.1
ELF	    7f4c258a9000-    7f4c258ae000	Deferred        libxinerama.so.1
ELF	    7f4c258b1000-    7f4c25971000	Deferred        winex11<elf>
  \-PE	    7f4c258c0000-    7f4c25971000	\               winex11
ELF	    7f4c25ba1000-    7f4c25bcf000	Deferred        libexpat.so.1
ELF	    7f4c25bd1000-    7f4c25c18000	Deferred        libfontconfig.so.1
ELF	    7f4c25c41000-    7f4c25c5d000	Deferred        libz.so.1
ELF	    7f4c25c61000-    7f4c25c99000	Deferred        libpng16.so.16
ELF	    7f4c25c99000-    7f4c25d58000	Deferred        libfreetype.so.6
ELF	    7f4c25d71000-    7f4c25d7a000	Deferred        libuuid.so.1
ELF	    7f4c25d81000-    7f4c25dcb000	Deferred        dxgi<elf>
  \-PE	    7f4c25d90000-    7f4c25dcb000	\               dxgi
ELF	    7f4c25ed1000-    7f4c260ac000	Deferred        wined3d<elf>
  \-PE	    7f4c25f00000-    7f4c260ac000	\               wined3d
ELF	    7f4c260b1000-    7f4c260cb000	Deferred        secur32.so
ELF	    7f4c260d1000-    7f4c260e9000	Deferred        dwrite.so
ELF	    7f4c260e9000-    7f4c26238000	Deferred        libm.so.6
ELF	    7f4c26241000-    7f4c2625d000	Deferred        libresolv.so.2
ELF	    7f4c26261000-    7f4c2633a000	Deferred        win32u.so
ELF	    7f4c26441000-    7f4c265b8000	Dwarf           libwine.so.1
ELF	    7f4c26c29000-    7f4c26c44000	Deferred        libgcc_s.so.1
ELF	    7f4c26c49000-    7f4c26c4e000	Deferred        dnsapi.so
ELF	    7f4c26c51000-    7f4c26c57000	Deferred        netapi32.so
ELF	    7f4c26c59000-    7f4c26c63000	Deferred        bcrypt.so
ELF	    7f4c26c69000-    7f4c26c70000	Deferred        crypt32.so
ELF	    7f4c26c71000-    7f4c26d34000	Deferred        ntdll.so
ELF	    7f4c26d39000-    7f4c26f2b000	Deferred        libc.so.6
ELF	    7f4c26f31000-    7f4c26f37000	Deferred        libdl.so.2
ELF	    7f4c26f39000-    7f4c26f5c000	Deferred        libpthread.so.0
ELF	    7f4c26f69000-    7f4c26f6f000	Deferred        winspool.so
ELF	    7f4c26f71000-    7f4c26f77000	Deferred        ws2_32.so
ELF	    7f4c26f79000-    7f4c26f84000	Deferred        librt.so.1
ELF	    7f4c26f89000-    7f4c26fb9000	Deferred        ld-linux-x86-64.so.2
Threads:
process  tid      prio (all id:s are in hex)
00000020 start.exe
	00000024    0
00000038 services.exe
	["C:\windows\system32\services.exe"]
	0000003c    0
	00000040    0
	00000070    0
	000000ac    0
	000000c4    0
	000000dc    0
00000060 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000064    0
	00000074    0
	00000078    0
	0000007c    0
	00000088    0
	0000008c    0
	00000090    0
00000068 explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	0000006c    0
	00000094    0
	00000098    0
000000a4 plugplay.exe
	[C:\windows\system32\plugplay.exe]
	000000a8    0
	000000b0    0
	000000b4    0
	000000b8    0
	000001c8    0
	000001cc    0
	000003b0    0
	000003b4    0
000000bc svchost.exe
	[C:\windows\system32\svchost.exe -k LocalServiceNetworkRestricted]
	000000c0    0
	000000c8    0
	000000cc    0
000000d4 rpcss.exe
	[C:\windows\system32\rpcss.exe]
	000000d8    0
	000000e0    0
	000000e4    0
	000000e8    0
	000000ec    0
	000000f0    0
	00000558    0
000000f8 conhost.exe
	["C:\windows\system32\conhost.exe" --unix --width 80 --height 24 --server 0xc]
	000000fc    0
00000100 Fusion360.exe
	["C:\Program Files\Autodesk\webdeploy\production\96174d2c4918a1a613b00371fd422e0f30e1d187\Fusion360.exe" ]
	00000104    0
	0000010c    0
	00000110    0
	00000114   15
	00000120    0
	00000138    0
	0000013c    0
	00000140    0
	00000144    0
	0000014c    0
	00000150    0
	00000154    0
	0000015c    0
	00000160    0
	00000164    0
	00000168    0
	00000170   -2
	00000174    0
	00000178    0
	0000017c    0
	00000180    0
	00000194    0
	00000198    0
	000001ac    0
	000001b0    1
	000001b4    0
	000001b8    0
	000001bc    0
	000001c0    0
	000001c4    0
	000001d4    1
	000001e0   -1
	000001e4   -1
	000001e8   -1
	000001ec   -1
	000001f0   -1
	00000218    0
	0000021c    0
	00000220    0
	00000224    0
	0000022c    0
	00000230    0
	00000234    0
	00000240    0
	00000248    0
	00000264    0
	00000268    0
	0000026c    0
	0000028c    0
	000002d8    0
	000002e0    0
	000002e4    0
	000002e8    0
	000002ec    0
	000002f0    0
	000002f4    0
	000002f8    0
	000002fc    0
	00000300    0
	00000304    0
	00000308    0
	0000032c    0
	00000390    0
	00000398    0
	000003cc    0
	000003d8    0
	0000042c    0
	00000484    0
	00000488    0
	0000048c    0
	00000490    0
	00000494    0
	00000498    0
	0000049c    0
	000004a0    0
	000004a4    0
	000004e8    0
	00000584    0
	000005bc    0
	000005c0    0
	00000620    0
	00000628    0
	00000630    0
	00000634    0
	00000650    0
	00000658    0
	0000065c    0
	000006a4    0
	000006e8   -2
	0000078c    0
00000118 adexmtsv.exe
	["C:/Program Files/Autodesk/webdeploy/production/96174d2c4918a1a613b00371fd422e0f30e1d187/adexmtsv.exe" "C:/ProgramData/Autodesk/Common/Material Library/20081401/adexmtsv_prod.cfg" -p "/tmp/20081401mark"]
	0000011c    0
	00000124    0
	00000128    0
	00000608    0
00000188 ADPClientService.exe
	[C:\users\mark\AppData\Roaming\Autodesk\ADPSDK\bin\ADPClientService.exe -f C:\users\mark\AppData\Roaming\Autodesk\ADPSDK\JSON]
	0000018c    0
	000001d0    0
00000330 AdCefWebBrowser_dpiAware.exe
	[C:/Program Files/Autodesk/webdeploy/production/96174d2c4918a1a613b00371fd422e0f30e1d187/Win64/AdCefWebBrowser_dpiAware.exe --disable-d3d11  --log-severity=disabled --lang=en  -remote-debugging-port=1234  --product-version="Neutron/2.0.11415" --no-proxy-server --cache-path="C:/users/mark/Temp/Autodesk/BrowserCache/2.0.11415"]
	00000334    0
	00000338    0
	00000344    0
	00000348    0
	0000034c    0
	00000354    0
	00000358    0
	0000035c    0
	00000360   -2
	00000364   -2
	00000368    0
	0000036c    0
	00000370    0
	00000374    0
	00000378    0
	0000037c    0
	00000380    0
	00000384    0
	00000388    0
	0000038c    0
	00000394    0
	0000039c    0
	000003a0    0
	000003a4    0
	000003b8    0
	000003bc    0
	000003c0    0
	000003c4    0
	000003c8    0
	000003d4    0
	000003e0    0
	000003e4    0
	000006a0    0
000003a8 (D) C:\Program Files\Autodesk\webdeploy\production\96174d2c4918a1a613b00371fd422e0f30e1d187\Win64\AdCefWebBrowser_dpiAware.exe
	["C:\Program Files\Autodesk\webdeploy\production\96174d2c4918a1a613b00371fd422e0f30e1d187\Win64\AdCefWebBrowser_dpiAware.exe" --type=gpu-process --no-sandbox --disable-d3d11 --lang=en --log-file="C:/users/mark/Temp/Autodesk/BrowserCache/2.0.11415\debug.log" --log-severity=disable --product-version="Neutron/2.0.11415 Chrome/59.0.3071" --disable-direct-composition --supports-dual-gpus=false --gpu-driver-bug-workarounds=7,10,11,19,20,21,24,43,76 --disable-gl-extensions="GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent" --gpu-vendor-id=0x10de --gpu-device-id=0x1380 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date=11-27-2021 --lang=en --log-file="C:/users/mark/Temp/Autodesk/BrowserCache/2.0.11415\debug.log" --log-severity=disable --product-version="Neutron/2.0.11415 Chrome/59.0.3071" --service-request-channel-token=F15D8F300C78E30893DF30FA7649DD5C --mojo-platform-channel-handle=740 /prefetch:2]
	000003ac    0
	000003f0    0
	000003f4    0
	000003f8    0 <==
	0000041c    0
	00000420    0
	00000428    0
	00000444    0
	00000450    0
	00000538    0
000003e8 AdCefWebBrowser_dpiAware.exe
	["C:\Program Files\Autodesk\webdeploy\production\96174d2c4918a1a613b00371fd422e0f30e1d187\Win64\AdCefWebBrowser_dpiAware.exe" --type=renderer --force-device-scale-factor=1 --no-sandbox --primordial-pipe-token=6C3E1D269CAE2A6E80B22742B619FB83 --lang=en-US --lang=en --log-file="C:/users/mark/Temp/Autodesk/BrowserCache/2.0.11415\debug.log" --log-severity=disable --product-version="Neutron/2.0.11415 Chrome/59.0.3071" --disable-extensions --enable-pinch --device-scale-factor=1 --num-raster-threads=2 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;0,16,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;1,16,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;2,16,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;3,16,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553;4,16,3553 --service-request-channel-token=6C3E1D269CAE2A6E80B22742B619FB83 --renderer-client-id=3 --mojo-platform-channel-handle=1056 /prefetch:1]
	000003ec    0
	000003fc    0
	00000400    0
	00000404    0
	0000040c    0
	00000410    0
	00000414    0
	00000418    0
	00000430    0
	00000434    0
	00000440   -2
	000006ac    0
00000438 QtWebEngineProcess.exe
	["C:\Program Files\Autodesk\webdeploy\production\96174d2c4918a1a613b00371fd422e0f30e1d187\QtWebEngineProcess.exe" --type=utility --enable-features=AllowContentInitiatedDataUrlNavigations,TracingServiceInProcess --disable-features=BackgroundFetch,ConsolidatedMovementXY,DnsOverHttpsUpgrade,FormControlsRefresh,MojoVideoCapture,PictureInPicture,SmsReceiver,UseSkiaRenderer,WebPayments,WebUSB --lang=en-US --service-sandbox-type=network --use-gl=desktop --application-name=Fusion360 --webengine-schemes=qrc:sLV --mojo-platform-channel-handle=4604 /prefetch:8]
	0000043c    0
	00000458    0
	0000045c    0
	00000464   -2
	00000468    0
	0000046c    0
	00000470    0
	00000478    0
0000047c QtWebEngineProcess.exe
	["C:\Program Files\Autodesk\webdeploy\production\96174d2c4918a1a613b00371fd422e0f30e1d187\QtWebEngineProcess.exe" --type=renderer --disable-speech-api --enable-threaded-compositing --enable-features=AllowContentInitiatedDataUrlNavigations,TracingServiceInProcess --disable-features=BackgroundFetch,ConsolidatedMovementXY,DnsOverHttpsUpgrade,FormControlsRefresh,MojoVideoCapture,PictureInPicture,SmsReceiver,UseSkiaRenderer,WebPayments,WebUSB --disable-databases --lang=en-US --webengine-schemes=qrc:sLV --device-scale-factor=1 --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=4 --mojo-platform-channel-handle=4664 /prefetch:1]
	00000480    0
	000004b8    0
	000004bc    0
	000004c0   -2
	000004c4    1
	000004c8    0
	000004cc    0
	000004d0    0
	000004d4    1
	000004d8    0
	000004dc    0
	000004e0    0
	000004e4   -2
	000006f4    0
000004f0 QtWebEngineProcess.exe
	["C:\Program Files\Autodesk\webdeploy\production\96174d2c4918a1a613b00371fd422e0f30e1d187\QtWebEngineProcess.exe" --type=renderer --disable-speech-api --enable-threaded-compositing --enable-features=AllowContentInitiatedDataUrlNavigations,TracingServiceInProcess --disable-features=BackgroundFetch,ConsolidatedMovementXY,DnsOverHttpsUpgrade,FormControlsRefresh,MojoVideoCapture,PictureInPicture,SmsReceiver,UseSkiaRenderer,WebPayments,WebUSB --disable-databases --lang=en-US --webengine-schemes=qrc:sLV --device-scale-factor=1 --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=5 --mojo-platform-channel-handle=5016 /prefetch:1]
	000004f4    0
	000004f8    0
	00000500   -2
	00000504    1
	00000508    0
	0000050c    0
	00000510    0
	00000514    1
	00000518    0
	0000051c    0
	00000520    0
	00000524   -2
	000006f8    0
0000053c explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	00000540    0
	00000550    0
	00000554    0
00000598 QtWebEngineProcess.exe
	["C:\Program Files\Autodesk\webdeploy\production\96174d2c4918a1a613b00371fd422e0f30e1d187\QtWebEngineProcess.exe" --type=renderer --disable-speech-api --enable-threaded-compositing --enable-features=AllowContentInitiatedDataUrlNavigations,TracingServiceInProcess --disable-features=BackgroundFetch,ConsolidatedMovementXY,DnsOverHttpsUpgrade,FormControlsRefresh,MojoVideoCapture,PictureInPicture,SmsReceiver,UseSkiaRenderer,WebPayments,WebUSB --disable-databases --lang=en-US --webengine-schemes=qrc:sLV --device-scale-factor=1 --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=6 --mojo-platform-channel-handle=5360 /prefetch:1]
	0000059c    0
	000005d8    0
	000005dc    0
	000005e0   -2
	000005e4    1
	000005e8    0
	000005ec    0
	000005f0    0
	000005f4    1
	000005f8    0
	000005fc    0
	00000600    0
	00000604   -2
00000660 QtWebEngineProcess.exe
	["C:\Program Files\Autodesk\webdeploy\production\96174d2c4918a1a613b00371fd422e0f30e1d187\QtWebEngineProcess.exe" --type=renderer --disable-speech-api --enable-threaded-compositing --enable-features=AllowContentInitiatedDataUrlNavigations,TracingServiceInProcess --disable-features=BackgroundFetch,ConsolidatedMovementXY,DnsOverHttpsUpgrade,FormControlsRefresh,MojoVideoCapture,PictureInPicture,SmsReceiver,UseSkiaRenderer,WebPayments,WebUSB --disable-databases --lang=en-US --webengine-schemes=qrc:sLV --device-scale-factor=1 --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=7 --mojo-platform-channel-handle=5708 /prefetch:1]
	00000664    0
	00000708    0
	0000070c    0
	00000710   -2
	00000714    1
	00000718    0
	0000071c    0
	00000720    0
	00000724    1
	00000728    0
	0000072c    0
	00000730    0
	00000734   -2
System information:
    Wine build: wine-6.22 (Staging)
    Platform: x86_64
    Version: Windows 8
    Host system: Linux
    Host version: 5.4.0-90-generic
`

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360 2.0.11415
- Graphics card model + NVidia GTX 750 ti driver 470
- Operating system Linux Mint 20.0 Cinnamon
- Desktop environment (XFCE 4.16, Gnome 40, ...)
- OpenGL-Mode

**Additional context**

**Comment by cryinkfly** [comment]
@vikingsraven I have the same issue with the new wine version but I can skip the errors with closing the window of them.

**Comment by vikingsraven** [comment]
@cryinkfly yeah did that and it came up , needed to ignore 4 times. It also has stopped me from saving files, the screen greys out and i don't get a file manager option, nor for the export.
i have to close then it lets me save.
by the way , thanks for doing this. i cant even imagine where to start!

**Comment by cryinkfly** [comment]
This issue is solved with the newest wine version! :+1: 

![Bildschirmfoto_2021-12-19_12-42-56](https://user-images.githubusercontent.com/79079633/146673681-5e2a7cc7-909f-45e6-be4b-c0351a727d39.png)
