### ISSUE TITLE
Installation keeps on looping *solved*

### ISSUE THREAD

**Issue by TheTRCG** [cryinkfly/Autodesk-Fusion-360-for-Linux#147]
**Describe the bug**
Installation has keeps on looping and does not finish. Keeps on opening install prompt

**Expected behavior**
Install L

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360
- Ryzen 2700U Vega 8 IGPU
- Ubuntu 20.04 LTS
- KDE Plasma
- OpenGL

**Additional context**
Wine works fine on my machine for running regular EXEs like games, not sure what's happening here

**Comment by cryinkfly** [comment]
@TheTRCG Please install Autodesk Fusion 360 with this command, where you get a log file (wine.error.log):

    mkdir -p "$HOME/.wineprefixes/fusion360/INSTALLDIR" && cd "$HOME/.wineprefixes/fusion360/INSTALLDIR" && wget -N https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/raw/main/files/scripts/stable-branch/fusion360-setup-wizard.sh && chmod +x fusion360-setup-wizard.sh && bash fusion360-setup-wizard.sh &> wine.error.log

**Comment by TheTRCG** [comment]
```
mkdir -p "$HOME/.wineprefixes/fusion360/INSTALLDIR" && cd "$HOME/.wineprefixes/fusion360/INSTALLDIR" && wget -N https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/raw/main/files/scripts/stable-branch/fusion360-setup-wizard.sh && chmod +x fusion360-setup-wizard.sh && bash fusion360-setup-wizard.sh &> wine.error.log
--2021-12-02 22:27:39--  https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/raw/main/files/scripts/stable-branch/fusion360-setup-wizard.sh
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/scripts/stable-branch/fusion360-setup-wizard.sh [following]
--2021-12-02 22:27:39--  https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/scripts/stable-branch/fusion360-setup-wizard.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 47302 (46K) [text/plain]
Saving to: 'fusion360-setup-wizard.sh'

fusion360-setup-wizard.sh     100%[=================================================>]  46.19K  --.-KB/s    in 0.04s   

Last-modified header missing -- time-stamps turned off.
2021-12-02 22:27:40 (1.05 MB/s) - 'fusion360-setup-wizard.sh' saved [47302/47302]
```
@cryinkfly 
After this it asks for my sudo password. And then keeps on looping.
No wine.error.log file is generated as far as I can tell, at least in the directory I ran the command,
however some strange behaviour when running the same command again in a different terminal with the previous one still open, there was a third option in the choice of wine menu, already installed option. Which I selected and got a prompt telling me the .wineprefixes/Fusion360 was being updated. But then continued to loop the same.
Sorry for the poorly formatted reply I'm just about to go to bed and wanted to do this so you could see. 
Thank you, have a good day

**Comment by cryinkfly** [comment]
@TheTRCG Okay, I'll have a look. Good night and see you soon. :-)

**Comment by TheTRCG** [comment]
@cryinkfly Howdy, sorry for the late reply,
just wondering is the script on lutris for fusion 360 installation the same as your installation script?

**Comment by TheTRCG** [comment]
@cryinkfly is it possible to use Fusion hobbyist accounts with this installation?
For some reason the Lutris install didn't work but trying your script again made it work, very very strange

**Comment by cryinkfly** [comment]
@TheTRCG

> Howdy, sorry for the late reply,
just wondering is the script on lutris for fusion 360 installation the same as your installation script?

No, it has nothing to do with the Lutris variant.

> is it possible to use Fusion hobbyist accounts with this installation?

Yes, you can use my script to run the hobby version of Autodesk Fusion 360.
Because all required data and authorizations (license) are set up with the registration in the Autodesk program.

**Comment by TheTRCG** [comment]
@cryinkfly 
Another update, I uninstalled wine and everything I could and reinstalled with your script.
Using a trial version it works pretty well, however when trying to use my free hobbyist account it doesn't recognize my email as a valid email which is a bit strange. 
But since it does work sort of I guess the issue has been solved by uninstalling and reinstalling wine staging and not wine stable

**Comment by cryinkfly** [comment]
@TheTRCG  So do I understand you correctly that it works for you now?

**Comment by TheTRCG** [comment]
@cryinkfly yes however when signing in using the hobbyist version it loads perpetually, works fine with a trial version though. Not sure what's up there. 
Required me to uninstall wine stable and install wine staging

**Comment by cryinkfly** [comment]
@TheTRCG So it shows me again that the stable version of wine is not working properly!

**Comment by TheTRCG** [comment]
@cryinkfly yup guess so which is pretty unfortunate to have.
Regardless thanks for your help! And for your script!
