### ISSUE TITLE
Cannot start on Manjaro - Getting past login screen but it then crashes and produces a backtrace.txt error log

### ISSUE THREAD

**Issue by RandomLegend** [cryinkfly/Autodesk-Fusion-360-for-Linux#148]
I used the install script, chose wine staging but got a warning in the terminal that the wine staging the script wants to install and the one on my system are not compatible. It asks if i want to uninstall my current wine staging and install the new one.
I declined that to keep my current one as this machine is also my gaming computer and the games i run work perfectly fine so i didnt want to disturbe that. I have the newest wine staging version.

After that everything appears to be working fine and i get to the log in screen which works aswell. But after that i get a crash from wine and it produces [backtrace.txt](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/files/7636438/backtrace.txt) this error log.

Hopefully this helps.

Thanks for the help!

**Comment by cryinkfly** [comment]
@Smart-Helper  I understand you correctly, you did the installation without the script?

**Comment by Smart-Helper** [comment]
No i did it with the script, but i declined the installation of the wine-staging version proposed by the cript because it was conflicting with my current installation

**Comment by cryinkfly** [comment]
I have changed the setup wizard so that you get a new option for skipping the installation of wine. 🙂

**Comment by Smart-Helper** [comment]
Thank you for the fast change!
However i still get a crash after login. This is what it looks like:
![image](https://user-images.githubusercontent.com/38812603/144513856-ccc95864-7899-4350-a664-5c6189135863.png)

This produces another 
[backtrace.txt](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/files/7645487/backtrace.txt)

**Comment by Smart-Helper** [comment]
And for the software requirements:
![image](https://user-images.githubusercontent.com/38812603/144514348-1d2dc2ef-959f-46b8-8d24-d38eeb81b642.png)

**Comment by Smart-Helper** [comment]
Oh btw i have a RTX3070 which isnt on your supported hardware list.

However i used your installation script on my previous Ubuntu 20.04 installation which had the exact same hardware setup as this one. And there it worked like a charm.

So as of right now im struggling with Manjaro in particular

**Comment by cryinkfly** [comment]
Please check this link:

- https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/146

**Comment by Smart-Helper** [comment]
@cryinkfly 

So, in my emails i had a link to https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/146
and here i see: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/144

So regarding #146 : Closing the error window does not solve things for me. I have no option to ignore things.
Regarding: #144 and the solution on WineHQ you posted goes over my head to be honest :-D Im no linux-expert and now poweruser. I dont feel comfortable with overwriting or reinstalling wine from source. I have all my games running perfectly fine and i dont want to mess with that. On my previous ubuntu version i also had wine 6.XX (i guess i twas 6.19) installed and it worked perfetly fine.
So is that issue 6.21 related?

**Comment by cryinkfly** [comment]
It can be, because the issue with #144 comes with this new wine version. 🤔😪

**Comment by smirgol** [comment]
I have this issue on Ubuntu as well now. Last week, it all went pretty smoothly. But when I fired up Fusion today, I get the same screen as Smart-Helper. I cannot click the error message away in this case, like I can do once the program is actually running and I am opening the left menu bar. :(
The strange thing is, I then killed the process and started Fusion again, got the same error message, but it still loaded the program and I then could click away that error message. *scratcheshead*

My wine version is `wine-6.22 (Staging)`, if that helps.

**Comment by Smart-Helper** [comment]
Would it help to use PlayOnLinux in any way? Afaik there you can install applications with seperate Wine versions.

So one could install Fusion with Wine 6.16 for example.

On the other hand wine release 6.23 yesterday. Maybe this could fix some issues. But i currently dont have time to tinker with that. So if anyone tests this out it would be awesome to let me know if it worked in any way

**Comment by cryinkfly** [comment]
So, with the newest version of wine Autodesk Fusion 360 works faster and also some bugs are solved! :+1:

**Comment by Smart-Helper** [comment]
Alright, i will try to install it right now. Im already on staging 6.23 btw so i can test this one too.

Hope it works! Gotta get some 3D prints up and running and i dont want to boot into windows :-D

**Comment by cryinkfly** [comment]
Here you can also see that the [the Photo-realistic visualization with ray tracing](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/releases/tag/v5.9) works! :+1:

**Comment by Smart-Helper** [comment]
looks awesome!

so, after install it now hangs on the splashscreen as stated in #151 
I dont get an error message as my original problem here, but it doesnt do anything. I could log in and verify via SMS code but after that its stuck there.

I already disabled my firewall and any port / domain blocking software and it doesnt continue.
Its on staging 6.23 now.

**Comment by cryinkfly** [comment]
Why you have only the 6.23 version? I use the 7.0 version of wine.

**Comment by Smart-Helper** [comment]
probably because i am on manjaro and they hold back package updates for up to 2 weeks to check for stability issues.

i just have to wait for wine 7 on manjaro because i dont want to mess up my installation by bruteforcing 7.0

**Comment by Smart-Helper** [comment]
Okay, so i just removed everything fusion360 from my system and tried it again after i found a post on reddit from another manjaro user that it works for him.

I then allowed your script to install the wine version it wanted, therefore removing my current wine version.

So the installation went through, no issue here. But now i am stuck in the splashscreen. Although i dont get that error i got initially.
![image](https://user-images.githubusercontent.com/38812603/147822624-89865ebb-b155-470d-a73b-95ca11bd8ed8.png)

**Comment by Smart-Helper** [comment]
Okay, update.

When i start fusion from the desktop icon THEN it hangs on the screen.
When i start it from the application menu shortcut, it launches correctly.

Then it all works nearly perfect! Smaaaaaaall issue however, OpenGL works but its jittery and laggy. DirectX9 works smooth but i cannot see the lines of my scetches. I see the blue coloration but not the lines, function wise everything works
DirectX11 doesnt start to the drawing board but all the menus work

**Comment by cryinkfly** [comment]
@Smart-Helper 

> When i start fusion from the desktop icon THEN it hangs on the screen.
When i start it from the application menu shortcut, it launches correctly.

I think you must check this .desktop file of Autodesk Fusion 360.
