### ISSUE TITLE
Docker image with ready-to use installation *solved*

### ISSUE THREAD

**Issue by ein-shved** [cryinkfly/Autodesk-Fusion-360-for-Linux#149]
Is there was any attempt to build Docker image based on this installer? Just simple distribution like Debian or Alpine with passed through installation process withing Dockerfile. This potentially can widen amount of supported distributions and prevent compatibility issues.

**Comment by cryinkfly** [comment]
@ein-shved So to answer your question briefly: Yes, I've thought about it. But at the moment I didn't have time for it, because I still wanted to finish my new computer. ^^

**Comment by cryinkfly** [comment]
@ein-shved I've now started creating! :+1:

**Comment by OJFord** [comment]
Sorry @cryinkfly, where is it? The readme indicates it's in the 'development-branch' files only, but I can't see it there (nor created by install.py) either?

Cheers.
