### ISSUE TITLE
Can't launch. "fusion360.exe" is not responding. *solved*

### ISSUE THREAD

**Issue by water-rhatt** [cryinkfly/Autodesk-Fusion-360-for-Linux#150]
I don't know how to even begin to troubleshoot. All seemed to install smoothly from the install script, but when I try launching Fusion 360 I get this:
 Any ideas of where to begin?

![Screenshot from 2021-12-04 18-06-54](https://user-images.githubusercontent.com/59306499/144730772-338792cf-874f-4f31-b7ea-4c3ee0613c7e.png)
s:

**Comment by cryinkfly** [comment]
You must wait.  🙂 This issue exists only systems with the Gnome desktop environment.
