### ISSUE TITLE
Fusion 360 Crashing After Startup

### ISSUE THREAD

**Issue by FlyingFaller** [cryinkfly/Autodesk-Fusion-360-for-Linux#151]
Hi I am new to linux so I really have no idea what I am doing. The only windows program I need to daily drive atm is Fusion so here we are. Tried a number of things (different scripts, different wine versions, lutris) but I've had the most success using the latest install script on this repository. 

I can get Fusion to install (although coming from windows the number of errors that thing throws is uh interesting lol) and I can launch and log in as intended. After logging in Fusion sits on the splash screen for a few minutes before quietly quitting. 

Using Linux Mint 20.2 (Ubuntu 20.04 I think)
Intel® Core™ i7-6500U
Mesa Intel® HD Graphics 520 (SKL GT2)

Not sure how much anyone can help me given my level of novice but I appreciate any advice.

**Comment by andrasbiro** [comment]
I had the same, and to my surprise, it worked from CLI. I didn't investigate too deep why the launcher doesn't work, it seems to start the exact same command.

The command you should call:
env WINEPREFIX="/home/<yourusername>/.wineprefixes/fusion360" wine C:\\users\\Public\\Desktop\\Autodesk\ Fusion\ 360.lnk

**Comment by dkijkuit** [comment]
Same here, it just hangs for a while and then disappears

![image](https://user-images.githubusercontent.com/16475465/144877372-b65acdfb-703c-461c-bfb3-54d7eeb24a34.png)

**Comment by FlyingFaller** [comment]
> 

I tired that and some variations fit to my file structure and no dice. If I understand what this is doing it just runs the desktop launcher so I don't really understand why this would work anyways but thanks for the thought. 

![Screenshot at 2021-12-06 12-19-23](https://user-images.githubusercontent.com/34020516/144900864-c07986cd-2538-4845-9ac4-b79f0b779827.png)

**Comment by cryinkfly** [comment]
@FlyingFaller Which wine version do you use?

**Comment by FlyingFaller** [comment]
> @FlyingFaller Which wine version do you use?

It looks like 6.0.2 is installed right now. However, I think it was installed though Mint's software manager which is crap and may have done something wildly unexpected.

**Comment by cryinkfly** [comment]
@FlyingFaller Okay, that finally proves that this Wine Version 6.x does not work with Autodesk Fusion 360!

- #146 
- #147 
- #151

**Comment by FlyingFaller** [comment]
So is your current recommendation to use Wine Staging or have you made changes to the install script to circumvent the issue?

Thanks for the help so far!

**Comment by cryinkfly** [comment]
@FlyingFaller Since I have now heard from my own tests, as well as from other users, that there are problems with the "stable" versions of Wine, I therefore always recommend using the latest version in the future! :+1: 

In addition, more and more functions and improvements are added to the newer versions, some of which also eliminate such errors. 🐞

I therefore ask you to try the staging variant. 🙂

**Comment by dkijkuit** [comment]
That's to bad there's no easy way to install the staging version on Ubuntu 20.04 because of the libc 2.33 dependency:
`wine-staging : Depends: libc6 (>= 2.33) but 2.31-0ubuntu9.2 is to be installed`

**Comment by cryinkfly** [comment]
Can you send me a screenshot of your repositorys, please?

**Comment by dkijkuit** [comment]
`deb https://dl.winehq.org/wine-builds/ubuntu/ hirsute main
deb http://archive.ubuntu.com/ubuntu focal universe
deb [arch=amd64,i386] https://repo.steampowered.com/steam/ stable steam
deb-src [arch=amd64,i386] https://repo.steampowered.com/steam/ stable steam
deb [arch=amd64,i386] https://repo.steampowered.com/steam/ stable steam
deb-src [arch=amd64,i386] https://repo.steampowered.com/steam/ stable steam
deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ focal main
deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ focal main
deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu disco main
deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod focal main
deb http://ppa.launchpad.net/lutris-team/lutris/ubuntu focal main
deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu disco main
deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
deb https://linux.teamviewer.com/deb stable main
deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod focal main
deb https://linux.teamviewer.com/deb stable main
deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main
deb http://ppa.launchpad.net/lutris-team/lutris/ubuntu focal main
deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main
deb http://nl.archive.ubuntu.com/ubuntu/ focal main restricted
deb http://nl.archive.ubuntu.com/ubuntu/ focal-updates main restricted
deb http://nl.archive.ubuntu.com/ubuntu/ focal universe
deb http://nl.archive.ubuntu.com/ubuntu/ focal-updates universe
deb http://nl.archive.ubuntu.com/ubuntu/ focal multiverse
deb http://nl.archive.ubuntu.com/ubuntu/ focal-updates multiverse
deb http://nl.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu focal-security main restricted
deb http://security.ubuntu.com/ubuntu focal-security universe
deb http://security.ubuntu.com/ubuntu focal-security multiverse
deb https://dl.winehq.org/wine-builds/ubuntu/ focal main
deb https://dl.winehq.org/wine-builds/ubuntu/ hirsute main`

**Comment by cryinkfly** [comment]
Okay, I already see some problems!

For example, you have different Wine repositories on your system:

> deb https://dl.winehq.org/wine-builds/ubuntu/ focal main
deb https://dl.winehq.org/wine-builds/ubuntu/ hirsute main```

And that then leads to the fact that your package manager cannot properly select the packages.

Please delete these two repositories and add them here:

     wget -q https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_20.04/Release.key -O Release.key -O- | sudo apt-key add -
    sudo apt-add-repository 'deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_20.04/ ./'

Then this will fix the problem:

>  wine-staging : Depends: libc6 (>= 2.33) but 2.31-0ubuntu9.2 is to be installed

**Comment by dkijkuit** [comment]
That totally worked, I was able to install the staging version and now it fires up! Thank you 👍

**Comment by M-Usamah** [comment]
I am running wine version 9 and it is crashing during setup

**Comment by wiktormalyska** [comment]
i have wine 8.19 (staging) and it cannot even pop up fusion window. Fedora 39
