### ISSUE TITLE
Fedora 35?

### ISSUE THREAD

**Issue by danielfarley** [cryinkfly/Autodesk-Fusion-360-for-Linux#152]
readme says it supports fedora 34, have tried to run on fedora 35...  was unable to get it work.         What would need to be changed to support fedora 35? 

Thanks

**Comment by cryinkfly** [comment]
You can now install Autodesk Fusion 360 with my script: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/commit/be82f08ca3ad066a89ed5891a8ba800457bfcf7d :+1:
