### ISSUE TITLE
Fusion360 hangs after splash screen

### ISSUE THREAD

**Issue by IOcase** [cryinkfly/Autodesk-Fusion-360-for-Linux#154]
**Describe the bug**
I get past the splash screen but I see nothing but a white screen on the main application window and fusion never finishes launching.

**To Reproduce**
0. Running Ubuntu 20.04 LTS. Fusion360 installed with the installer script command in the readme
1. Either launch through desktop icon or through the icon after pressing the super button
2. Wait for launcher script to finish
3. Lots of errors print out (I'll include a link to a pastebin with the output)
4. Application hangs

**Expected behavior**
The app should launch

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360: Unsure. Can't get to the application to check
- Graphics card model + Graphics card driver (Version number): NVIDIA RTX 2070 Super running proprietary NVIDIA 470
- Operating system: Ubuntu 20.04 LTS
- Desktop environment: Gnome 3.36.8
-  OpenGL-Mode

Log output: [pastebin](https://pastebin.com/XndqS68y)

**Comment by fritzphantom** [comment]
I have exactly the same problem on arch linux, here is a screenshot:
![image](https://user-images.githubusercontent.com/61949537/145876293-a82efb46-4f40-4d57-87e8-60b49975d97f.png)

Interestingly, it seems like I can still draw behind the splash screen, e.g. when pressing "r" i can create a rectangle and see the dimensions while drawing on top of the splashscreen.

**Comment by tome9111991** [comment]
In fusion360 you have to change to directx9

**Comment by cryinkfly** [comment]
Is the problem still there?

**Comment by cumulus21** [comment]
I have the same issue as IOcase. The errors in my xterm output are the same as shown in their pastebin. I am also running Ubuntu 20.04.

I think in another issue/bug, I read that it might be necessary to run wine-staging, but that Ubuntu 20.04 might then be missing other needed dependencies... any recommendations? Thank you.

**Comment by RiScJ** [comment]
> In fusion360 you have to change to directx9

@tome9111991 Thanks, this fixed the issue for me -- my problem was identical to that shown in @fritzphantom 's screenshot.

**Comment by KShivum** [comment]
I'm relatively new to linux, but it seems I'm having the same issue. I tried reinstalling it the DX version, but no luck, same issue

**Comment by cfallon61** [comment]
I seem to be having a similar issue, though i dont event get past the logo opening. After taking the screenshot fusion crashed (which is new. Usually it just hangs indefinitely like this)
![Screenshot_20220110_190036](https://user-images.githubusercontent.com/31864254/148873961-31f2b5fd-47c2-40a4-bfa2-268094a42834.png)

**Comment by cryinkfly** [comment]
Another way can be this one: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/124
