### ISSUE TITLE
Hangs after login and eventually gives "Error Report"

### ISSUE THREAD

**Issue by water-rhatt** [cryinkfly/Autodesk-Fusion-360-for-Linux#158]
**Describe the bug**
I know this has been brought up before, but I too am able to log into Fusion, and after a long delay I receive a Fusion 360 Error report saying that it has shut down due to a "software error".  I tried:

 `env WINEPREFIX="/home/randolph/.wine" wine C:\windows\command\start.exe /Unix /home/randolph/.wine/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Autodesk/Autodesk\ Fusion\ 360.lnk &> wine.error.log`,
but that didn't seem to do anything. I just got a new terminal prompt. If it created a log file, I can't find it anywhere.

I also looked for a `launch.sh` file in the `~/.wineprefix/Fusion360` folder, but that file doesn't exist. 

I tried cutting and pasting from the .desktop launcher: `Exec=env WINEPREFIX="/home/randolph/.wineprefixes/fusion360" wine C:\\\\users\\\\Public\\\\Desktop\\\\Autodesk\\ Fusion\\ 360.lnk` into terminal, but again it did nothing.

I'm open to suggestions on how to get this running.

**To Reproduce**
1. Run Install Script
2. Double Click on Desktop Launcher

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- ??
- Intel Iris Xe
- Kubuntu 21.10 Impish
- KDE Plasma 5.22.5
- DXVK- or OpenGL-Mode (tried both, same result)

**Additional context**

**Comment by cryinkfly** [comment]
Run this command:

xterm -hold -e "$HOME/.local/share/applications/wine/Programs/Autodesk/fusion360-launcher.sh"

**Comment by water-rhatt** [comment]
YES! That does seem to work (at least well enough for my purposes on this machine). Is there some way of changing the .desktop file so that it runs that script? It would be nice to have a way to launch without remembering or typing that line in.

**Comment by cryinkfly** [comment]
Yes, here you can find this file: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/tree/main/files/extras/desktop-starter
