### ISSUE TITLE
Can't upload files *solved*

### ISSUE THREAD

**Issue by Andreiva13** [cryinkfly/Autodesk-Fusion-360-for-Linux#163]
Hello, 
When trying to upload a file the upload pop-up comes up with a bluish window over it that prevents any interaction with stuff under it, including the "Cancel" and "Upload" buttons, requiring a program restart.
The overlay window is the same size as the original fusion one but the fusion one can still be moved around and resized without the state of the overlay changing.
![image](https://user-images.githubusercontent.com/43719525/147874922-25df4e4d-f547-4187-a613-0ef433851861.png)

**Comment by Andreiva13** [comment]
Same behavior using both OpenGL and DirectX9

**Comment by cryinkfly** [comment]
1.) Option: You must minimize the program or click on icon (Show desktop) and then you can upload your files.
2.) Option: You work with Tab- and Enter-Key.

*Notice: This effect usually only occurs when a file is first uploaded.

**Comment by Andreiva13** [comment]
Thanks!

**Comment by cryinkfly** [comment]
Here can you see this also when you will saving a rendered file: https://youtu.be/KTSdsOuuEmY?t=3242
