### ISSUE TITLE
Fusion 360 in workspace - Linux Mint 20.2 *solved*

### ISSUE THREAD

**Issue by tome9111991** [cryinkfly/Autodesk-Fusion-360-for-Linux#165]
Hello
i got a new laptop with AMD Ryzen 5 5500u run with Mint 20.2.
i cant use F360 because i see only the fusion360 logo in workspace:
![Bildschirmfoto_2022-01-05_13-58-06](https://user-images.githubusercontent.com/57866234/148222248-f66dd1ba-cf9b-4c49-904b-d2f0d6701198.png)

I have change to Directx9.
have alo tried with D11 and OpenGL.
but still same issue.

Maybe any idea?

**Comment by tome9111991** [comment]
I have update to kernel 5.11 (kernel 5.4 default with Mint 20.2)
with Directx9 & OpenGL works now.

**Comment by cryinkfly** [comment]
@tome9111991 Good job. :+1:
