### ISSUE TITLE
Bug in Electronic Design (Schematic).

### ISSUE THREAD

**Issue by IsaacDias2020** [cryinkfly/Autodesk-Fusion-360-for-Linux#166]
When in Electronic Design (New Schematic) option, when i choose Add Part, nothing happens (no window option to add part, shows up).

- Version number of Autodesk Fusion 360: 2.0.11685
- Graphics card model: AMD RX 550
- Operating system: Zorin 16 Pro
- Gnome 3.38
- Open GL - Mode.

Screenshot:
![Captura de tela de 2022-01-06 10-41-43](https://user-images.githubusercontent.com/68559782/148393587-3abce2a3-911f-4860-bacc-cffa964e881e.png)

**Comment by cryinkfly** [comment]
@IsaacDias2020 Okay, I check this out. Thank you for your report. :+1:

**Comment by Eric8tF** [comment]
Hi,
I had the same issue, just click on the Fusion360 icon than the 'add component' window floats to the top. It was just the first time now it's working like a charm.

**Comment by IsaacDias2020** [comment]
> Hi, I had the same issue, just click on the Fusion360 icon than the 'add component' window floats to the top. It was just the first time now it's working like a charm.

Thanks.

**Comment by cryinkfly** [comment]
So @IsaacDias2020 , I have tested this again on my system with the stable version of wine (7.0) and it works:

https://user-images.githubusercontent.com/79079633/150631612-6d2f418b-54e3-4722-b9f6-fe4648696abc.mp4

**Comment by IsaacDias2020** [comment]
Thanks.👍

Enviado do Mailspring ***@***.***/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQVFMQ0hKU1FUTDNPQU5KSUNFSlNSTEY3NjZUSFBFVkJOSEhFQ1NOU0U0QHJlcGx5LmdpdGh1Yi5jb20%3D), o melhor aplicativo de e-mail gratuito para o trabalho
