### ISSUE TITLE
Stuck at this screen

### ISSUE THREAD

**Issue by scordd** [cryinkfly/Autodesk-Fusion-360-for-Linux#171]
![Screenshot from 2022-01-20 13-27-05](https://user-images.githubusercontent.com/70288480/150424870-ff7cb0ce-feeb-445c-86b7-42f13cabc155.png)

**Comment by scordd** [comment]
New to Wine, sorry if this seems like an ignorant issue!

**Comment by cryinkfly** [comment]
Hey @scordd ... Here is the solution for your problem: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/124 :+1:
