### ISSUE TITLE
Certain parts of UI appear on top of other application windows.

### ISSUE THREAD

**Issue by mglebinski** [cryinkfly/Autodesk-Fusion-360-for-Linux#174]
**Describe the bug**
When switching from Autodesk to another app (such as Firefox), certain parts of the UI such as the content browser appear on top of said app.

**Desktop:**
- Autodesk Fusion 360 Version 2.0.12157
- Intel UHD 620
- Gnome 40.4.0
- DXVK

**Comment by cryinkfly** [comment]
Please check this link: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/9
