### ISSUE TITLE
"Bad EXE Format" - Script fails to install when WINEARCH and WINEPREFIX are set to win32

### ISSUE THREAD

**Issue by marzukia** [cryinkfly/Autodesk-Fusion-360-for-Linux#177]
This is just a note to any future readers that if they run into the rather perplexing error of "Bad format EXE" while executing a script that this is due to the fact that your `WINEARCH` and `WINEPREFIX` variables may be set incorrectly.

Another program I had historically installed caused these to be different hence the issue.

Maybe this can be added to the FAQ for any future readers who may run into same issue.

**Comment by cryinkfly** [comment]
Thank you very much for this tip! :+1: 
I will add this to the documentation.

Here is a link for all users who want to know more about the topic: https://wiki.winehq.org/FAQ#Wineprefixes
