### ISSUE TITLE
Wine:/Debian/xUbuntu_20.10 Resource Not Available

### ISSUE THREAD

**Issue by realumhelp** [cryinkfly/Autodesk-Fusion-360-for-Linux#178]
**Describe the bug**
When installing against Ubuntu 20.10 it seems like the Wine repo no longer exists for 20.10. The only available versions seem to be:

-   xUbuntu_18.04/
-   xUbuntu_20.04/ 
-   xUbuntu_21.04/  
-   xUbuntu_21.10/

**To Reproduce**
Install against Ubuntu 20.10.

**Expected behavior**
Expected to download and/or update Wine:
```
Ign:20 https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_20.10 ./ InRelease
Err:21 https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_20.10 ./ Release
  404  Not Found [IP: 195.135.221.134 443]
Reading package lists... Done
E: The repository 'https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_20.10 ./ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Screenshots**
![Screenshot from 2022-01-26 08-39-09](https://user-images.githubusercontent.com/10177737/151173144-c5988377-0617-4a49-9823-da210f461ee6.png)

**Comment by realumhelp** [comment]
It looks like Ubuntu 20.10 is end of life in July 2021 so Wine probably dropped the repo.

**Comment by cryinkfly** [comment]
@realumhelp Thank you very much for help. :+1:

**Comment by realumhelp** [comment]
No problem that was crazy fast response time! I guess this shows how often I update my system... haha
