### ISSUE TITLE
Some checkboxes are not usable

### ISSUE THREAD

**Issue by ghostcontrollers** [cryinkfly/Autodesk-Fusion-360-for-Linux#179]
**Describe the bug**
- Some checkboxes are not selectable/deselectable

**To Reproduce**
- Start Fusion 360
- Open any design
- Try to change some work features from the bottom menu

**Expected behavior**
- Boxes should be checkable/uncheckable

**Desktop**
- Version number of Autodesk Fusion 360:  2.0.12160
- Graphics card model + Graphics card driver (Version number): NVIDIA RTX3080 Mobile, Driver 495.46
- Operating system: Manjaro Cinnamon 21.2.2
- Desktop environment: Cinnamon 5.x
- OpenGL: has above behaviour 
- DirectX9: has above behaviour 
- DirectX11:  Boxes are working normal, but persistent Fusion360-Splashscreen does not allow to use the software

**Screenshots**
![Fusion360_1](https://user-images.githubusercontent.com/73472568/151313629-867885f0-81aa-4574-9e43-5e6327ebc280.png)

**Comment by cryinkfly** [comment]
You are right! :+1: 
I have checked this also on my system and I search for a solution.

**Comment by monte-monte** [comment]
When using virtual desktop those checkboxes become usable as do other menu items that have problems with being clicked.
