### ISSUE TITLE
Cannot update Fusion 36-

### ISSUE THREAD

**Issue by wprojects** [cryinkfly/Autodesk-Fusion-360-for-Linux#183]
I had posted an earlier thread below and it was marked as solved but has never been solved. I love using fusion and linux but cannot open any files my friends send me or files I send to myself from another computer on an updated version. It may be simple to you and maybe I'm a dummy but I have tried over and over to do this update every way I know and it never shows it's updated and will not let me use my files. I am sorry to both you about it but I'm sure I'm not the only idiot out here that can't figure this out. Thank you for supporting linux and doing this, it has changed my world. 
https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/164

Can someone post a video showing the steps because when I tried to follow it keeps failing to update and I really need to be able to access the files from my friends and other computers

**Comment by cryinkfly** [comment]
I make a video in the next week. :-)

**Comment by wprojects** [comment]
Ok That would be great. I really appreciate it

**Comment by wprojects** [comment]
@cryinkfly Have you gotten that video made yet? Sorry to bother you about it, I'm just crippled atm I can't build on my rig lol

**Comment by wprojects** [comment]
@cryinkfly Any time next week? 🙏 Thank you for your dev work to even make it possible I am very thankful I just really really need to be able to work on my models on my rig again!

**Comment by cryinkfly** [comment]
@wprojects Here you can see how Autodesk Fusion 360 update will work soon: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/blob/main/files/scripts/development-branch/update.sh

But I think the best solution for you is when you delete the wineprefix folder fusion360 (/$HOME/.wineprefixes/fusion360) on your system and then you  repeat the installation.

**Comment by wprojects** [comment]
That link is dead @cryinkfly. Ok I can give that a try

**Comment by cryinkfly** [comment]
Please, use my new setup wizard! :+1:
