### ISSUE TITLE
Unable to export meshes

### ISSUE THREAD

**Issue by lewisjared** [cryinkfly/Autodesk-Fusion-360-for-Linux#184]
**Describe the bug**
First of all thanks so much for this project. It is a lifesaver!

Recently I have been unable to export bodies as meshes for 3d printing. Every time I attempt to export a body the following error arises:

```
Error: Autodesk Translation Services failed to translate the current document to 3mf file!
Error: Translator failed to export data
```

The issue began in the last few days and has persisted across a fresh update and install of Fusion 360. There is a [knowledge base article](https://knowledge.autodesk.com/support/fusion-360/troubleshooting/caas/sfdcarticles/sfdcarticles/Unable-to-save-as-STL.html) for the error message, but the suggested workaround doesn't work.  I have tried restarting Fusion and also a number of different export settings and models, but the issue persists. I have been able to export as mesh previously.

**To Reproduce**
1. Create a simple body
2. Right click on component in browser
3. Save as mesh

![Peek 2022-02-05 11-08](https://user-images.githubusercontent.com/1332673/152619268-161d57a0-eaa8-4c77-b572-6885a2f979a7.gif)

**Expected behavior**
Body is exported as a 3MF or STL file

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360
2.0.12164 and a previous unknown version
- Graphics card model + Graphics card driver (Version number)
GeForce RTX 2070 SUPER
- Operating system (OpenSUSE Leap 15.3, Fedora 34, ...)
Ubuntu 20.04
- Desktop environment (XFCE 4.16, Gnome 40, ...)
Gnome 3.36.8
- DXVK- or OpenGL-Mode
OpenGL mode

**Additional context**
Log file for opening a simple part, attempting to export and then closing

[AppLogFile20220205T111412.log](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/files/8006945/AppLogFile20220205T111412.log)

**Comment by cryinkfly** [comment]
@lewisjared Thank you very much for this information! :+1: 

I will check this in the next time.

**Comment by lewisjared** [comment]
This seems to have been resolved. It potentially could have been a server processing issue rather than a client-side bug
