### ISSUE TITLE
Won't Start *solved*

### ISSUE THREAD

**Issue by PhantomLel** [cryinkfly/Autodesk-Fusion-360-for-Linux#189]
I am on Ubuntu and I ran the installer. Everything seemed to have went fine but when I run `xterm -hold -e "$HOME/.local/share/applications/wine/Programs/Autodesk/fusion360-launcher.sh"` it pops up the window with this error

> wine: Call from 0x7b02dae6 to unimplemented function msvcp140.dll.?table@?$ctype@D@std@@QEBAPEBFXZ, aborting
002b:err:module:LdrInitializeThunk "ContentService.dll" failed to initialize, aborting
002b:err:module:LdrInitializeThunk Initializing dlls for L"C:\\Program Files\\Autodesk\\webdeploy\\production\\65899d0f0113f775e86f30ece2eeaf89fc855cb7\\Fusion360.exe" failed, status 80000100

**Comment by cryinkfly** [comment]
Please check these links here: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/4 & https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/43
