### ISSUE TITLE
Fusion 360 doesn't start - caught exception in protein

### ISSUE THREAD

**Issue by NotLugozzi** [cryinkfly/Autodesk-Fusion-360-for-Linux#191]
**Describe the bug**
Fusion 360 doesn't start no matter what i tried

**To Reproduce**
1. Install fusion
2. Run fusion
3. See error

**Expected behavior**
Fusion should start

**logs**
`002c:fixme:winediag:LdrInitializeThunk wine-staging 7.2 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0108:fixme:vcruntime:__telemetry_main_invoke_trigger (00000000037C0000)
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F4C0 63 ) semi-stub
0108:fixme:msvcp:locale__Locimp__Makexloc (000000000011F4C0 63 000000001DFBFA60 0000000000000000) semi-stub
0108:fixme:msvcp:locale__Locimp__Makewloc (000000000011F4C0 63 000000001DFBFA60 0000000000000000) semi-stub
0108:fixme:msvcp:locale__Locimp__Makeushloc (000000000011F4C0 63 000000001DFBFA60 0000000000000000) semi-stub
0108:fixme:vcruntime:__telemetry_main_invoke_trigger (000000000CEB0000)
0108:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 000000000011F1B4, 000000000011F1D0 000000000011F1B0
0108:fixme:nls:get_dummy_preferred_ui_language (0x38 000000000011F1B4 000000000011F1D0 000000000011F1B0) returning a dummy value (current locale)
0108:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F410 63 C) semi-stub
0108:fixme:msvcp:locale__Locimp__Makexloc (000000000011F410 63 000000001E64AD90 0000000000000000) semi-stub
0108:fixme:msvcp:locale__Locimp__Makewloc (000000000011F410 63 000000001E64AD90 0000000000000000) semi-stub
0108:fixme:msvcp:locale__Locimp__Makeushloc (000000000011F410 63 000000001E64AD90 0000000000000000) semi-stub
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F3F0 1 C) semi-stub
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011EC88 1 C) semi-stub
0108:fixme:vcruntime:__telemetry_main_invoke_trigger (0000000019D50000)
0108:fixme:vcruntime:__telemetry_main_invoke_trigger (000000001AAA0000)
0108:fixme:vcruntime:__telemetry_main_invoke_trigger (000000001ABF0000)
0108:fixme:vcruntime:__telemetry_main_invoke_trigger (000000001A3F0000)
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011ED30 1 C) semi-stub
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011EC40 1 C) semi-stub
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011EF60 1 C) semi-stub
0108:fixme:nls:get_dummy_preferred_ui_language (0x8 000000000011E270 0000000000000000 000000000011E274) returning a dummy value (current locale)
0108:fixme:nls:get_dummy_preferred_ui_language (0x8 000000000011E270 000000001E6AEA30 000000000011E274) returning a dummy value (current locale)
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011DFF0 1 C) semi-stub
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E1C0 1 C) semi-stub
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011DF90 1 C) semi-stub
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011DEF0 1 C) semi-stub
0108:fixme:file:NtLockFile I/O completion on lock not implemented yet
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011EF40 1 C) semi-stub
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F040 1 C) semi-stub
0108:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000001D1C5CF0, 43) stub
0108:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000001D509520, 43) stub
0108:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000001D28A532, 43) stub
0058:fixme:nsi:ipv6_forward_enumerate_all not implemented
0058:fixme:nsi:ipv6_forward_enumerate_all not implemented
0058:fixme:nsi:ipv6_forward_enumerate_all not implemented
0058:fixme:nsi:ipv6_forward_enumerate_all not implemented
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F1C0 1 C) semi-stub
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F340 1 C) semi-stub
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011EF50 1 C) semi-stub
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F240 1 C) semi-stub
0110:fixme:sync:SetWaitableTimerEx (0000000000000124, 000000002013FA60, 0, 0000000000000000, 0000000000000000, 0000000000000000, 149) semi-stub
0058:fixme:nsi:ipv6_forward_enumerate_all not implemented
0058:fixme:nsi:ipv6_forward_enumerate_all not implemented
0058:fixme:nsi:ipv6_forward_enumerate_all not implemented
0058:fixme:nsi:ipv6_forward_enumerate_all not implemented
010c:fixme:netprofm:connection_point_Advise 00000000002066C0, 000000001EDE8CF0, 000000001EDE8D00 - semi-stub
0108:fixme:win:RegisterPowerSettingNotification (000000000002006A,{02731015-4510-4526-99e6-e5a17ebd1aea},0): stub
0108:fixme:wgl:X11DRV_wglGetPixelFormatAttribivARB unsupported 2008 WGL Attribute
"Z:/home/takeshi/.wineprefixes/fusion360/INSTALLDIR/drive_c/Program Files/Autodesk/webdeploy/production/50d1a2b00ac928c7781cbca6551e586
a5384d498/plugins"
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E550 1 C) semi-stub
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E280 1 C) semi-stub
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E590 1 C) semi-stub
0118:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000002068FB50 1 C) semi-stub
0118:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000002068FAD0 1 C) semi-stub
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011EA80 63 C) semi-stub
0108:fixme:msvcp:locale__Locimp__Makexloc (000000000011EA80 63 000000001F176C20 0000000000000000) semi-stub
0108:fixme:msvcp:locale__Locimp__Makewloc (000000000011EA80 63 000000001F176C20 0000000000000000) semi-stub
0108:fixme:msvcp:locale__Locimp__Makeushloc (000000000011EA80 63 000000001F176C20 0000000000000000) semi-stub
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E500 1 C) semi-stub
0108:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011DED0 1 C) semi-stub
0120:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011FBF8 1 C) semi-stub
0120:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011FBD0 1 C) semi-stub
0120:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F390 1 C) semi-stub
0120:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F0C0 1 C) semi-stub
[2022-02-21 17:59:12.054139] [0x00000120] [fatal]   Exception caught in main: d:\stage\workspace\protein\release\2020.10.r2022\protein\
src\libs\xirang\common\file_archive.cpp(95)MaterialLibrary/Material Library/adexmtsv_prod.cfg`

**Desktop (please complete the following information):**
- Amd Radeon R5  + amdgpu drivers version  21.0.0-1
- OS: Pop!OS 21.10 with kernel 5.15.23
- Desktop environment: Gnome 40.4.0
- OpenGL-Mode

**Comment by cryinkfly** [comment]
Please, check my newest setup wizard! 🙂 ... and select DXVK. OpenGL is the Fallback-Version now!
