### ISSUE TITLE
Application could not be started

### ISSUE THREAD

**Issue by logicguy1** [cryinkfly/Autodesk-Fusion-360-for-Linux#193]
**Describe the bug**
After running the installatoin script, autodesk does not want to be launched

**To Reproduce**
1. Run the steps as described in the readme file and get a successfull install
2. Run `[drill@archlaptop Autodesk]$ xterm -hold -e "/home/drill/.local/share/applications/wine/Programs/Autodesk/fusion360-launcher.sh"`
3. See error

**Expected behavior**
Im explecting it to launc in a manner to where i can intereact with it

**Screenshots**
https://cdn.discordapp.com/attachments/937093221190864896/946013862078083132/IMG_2979.jpg
https://cdn.discordapp.com/attachments/937093221190864896/946013862652690482/IMG_2978.jpg

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360 Not sure how to get that, its not running
- Graphics card model + Graphics card driver (Version number) I use a nvidia card and have the latest version
- Operating system (OpenSUSE Leap 15.3, Fedora 34, ...) Archlinux, btw
- Desktop environment (XFCE 4.16, Gnome 40, ...) Qtile
- DXVK- or OpenGL-Mode not sure what that is

**Additional context**

**Comment by cryinkfly** [comment]
Please, use my newest setup wizard! 🙂
