### ISSUE TITLE
DLLs missing and Fusion not starting up

### ISSUE THREAD

**Issue by Rohit-Rangaraj** [cryinkfly/Autodesk-Fusion-360-for-Linux#195]
**Describe the bug**
I started the application for the first time, and I just had many DLLs missing errors thrown at me.

**To Reproduce**
1. Install the application by following the instructions
2. Startup the application

**Expected behavior**
A working instance of the Fusion app.

**Desktop:**
- Version number of Autodesk Fusion 360: 2.0.12376
- Graphics card model + Graphics card driver (Version number): AMD RX580 + mesa from Arch Repos
- Operating system (OpenSUSE Leap 15.3, Fedora 34, ...): Arch Linux
- Desktop environment (XFCE 4.16, Gnome 40, ...): Openbox

**Additional context**

Got the output while trying to execute ```F360DIR="$HOME/.wineprefixes/fusion360/"
env WINEPREFIX="${F360DIR}" wine C:\\windows\\command\\start.exe /Unix "${F360DIR}/drive_c/ProgramData/Microsoft/Windows/Start Menu/Programs/Autodesk/Autodesk Fusion 360.lnk"``` from (https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/44#issuecomment-898090000).

I've pasted the output on the clipboard site as Github did not allow me to paste such a big output.

https://online-clipboard.online/online-clipboard/

Please use code `9865` to retrieve the text.

**Comment by cryinkfly** [comment]
@Rohit-Rangaraj 

> Got the output while trying to execute F360DIR="$HOME/.wineprefixes/fusion360/" env WINEPREFIX="${F360DIR}" wine C:\\windows\\command\\start.exe /Unix "${F360DIR}/drive_c/ProgramData/Microsoft/Windows/Start Menu/Programs/Autodesk/Autodesk Fusion 360.lnk" from (https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/44#issuecomment-898090000).

## Please use my [.desktop files](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/tree/main/files/builds/stable-branch/.desktop) and the [launcher.sh](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/tree/main/files/builds/stable-branch/bin)! 🙂

**Comment by chabad360** [comment]
Yea, I'm having the same issue, and I'm using the launcher script too:

https://gist.github.com/chabad360/e9cace26c87ae23ad8812dd90a52f628

**Comment by Rohit-Rangaraj** [comment]
@cryinkfly Any updates on this?

**Comment by op3** [comment]
This seems to be a wine bug, see https://bugs.archlinux.org/task/73994.

**Comment by Rohit-Rangaraj** [comment]
@op3 How do I fix it? Should I do a clean install again?

**Comment by chabad360** [comment]
I've downgraded to wine-staging 7.2 and I'm in the process of doing a clean install, it seems to be actually working this time (so far).

**Comment by cryinkfly** [comment]
> I've downgraded to wine-staging 7.2 and I've done a clean install, that seems to have done the trick.

Yes, there seem to be serious problems with the latest wine version at the moment!

That's why I opened a case for this: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/202

**Comment by cryinkfly** [comment]
So I looked it up and ran more tests!
So it is actually due to the Wine Version 7.3!!!

But there is a newer version released this week...Wine version 7.4 and with it this bug got rid of!!!!!

Here:  https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/202#issuecomment-1066049410

**Comment by Rohit-Rangaraj** [comment]
@cryinkfly Now it is throwing me this error. 
`wine: could not open working directory L"unix\\home\\rohit\\.config\\fusion-360\\bin\\", starting in the Windows directory.
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.`

**Comment by gromain** [comment]
@Rohit-Rangaraj this looks like an issue with the desktop file or something related.
Can you try in a terminal to launch Fusion with `bash $HOME/.config/fusion-360/bin/launcher.sh` to see if this works at least.

**Comment by Rohit-Rangaraj** [comment]
@gromain I tried that and got the following error.
````--2022-03-25 01:06:46--  https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/update-config.txt
SSL_INIT
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-03-25 01:06:47 ERROR 404: Not Found.

Do nothing!
wine: could not open working directory L"unix\\home\\rohit\\", starting in the Windows directory.
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.```
