### ISSUE TITLE
Fusion shows bodys and sketches without outlines, just blue surfaces.

### ISSUE THREAD

**Issue by KaptainKugelkopf** [cryinkfly/Autodesk-Fusion-360-for-Linux#196]
**Describe the bug**
The Program shows the bodys/sketches without outlines, just bluish really transparent surfaces. 

**To Reproduce**
Open Fusion 360 

**Expected behavior**
Normal display of the models

**Screenshots**
**![Screenshot_20220305_152441](https://user-images.githubusercontent.com/101006468/156887729-404c22ad-cd92-4f04-b862-7a494425c6b7.png)**

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360: 
2.0.12392
- Graphics card: GeForce GTX 1070 Driver: NVIDIA Corporation GP104 
- Operating system: Kubuntu 20.04
- Desktop environment: KDE 5.18.8
- DXVK- or OpenGL-Mode: Not sure? How do i find out?

**Additional context**
For mor info/context please ask, happy to provide!

**Comment by bishboshin** [comment]
Hello, I believe, I have a similar issue. Could you, please, write here what helped to solve the issue? Thanks in advance.

**Comment by KaptainKugelkopf** [comment]
I think it was just a Problem with the timeline.
Pulled to the left, or turned some parts off

**Comment by bishboshin** [comment]
Ah, ok! So, that's not the problem of the wine port performance, but just a generic Fusion 360 thing, right? It would be the same if you run it natively under Windows, I guess...
I saw similar issues every now and then and thought, that they are glitches, but maybe, that's not the case, indeed.
Thanks.
