### ISSUE TITLE
Issue with the new updater

### ISSUE THREAD

**Issue by wprojects** [cryinkfly/Autodesk-Fusion-360-for-Linux#199]
@cryinkfly I have tried to run the new update.sh file and it keeps telling me It's getting an error with no log on the ui window. I have just downloaded the new project and ran this straight from my downloads folder. Any idea on what the issue is or how I can fix it? 

Thanks! 

![image](https://user-images.githubusercontent.com/57518634/157112963-291f5a46-b617-485d-bd6f-0f7c74527339.png)

**Comment by cryinkfly** [comment]
The [update.sh](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/blob/main/files/builds/stable-branch/bin/update.sh) file is started automatically via the [launcher.sh](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/blob/main/files/builds/stable-branch/bin/launcher.sh) file!

This means that if you start the program from your system menu, then everything will be done for you:

![Bildschirmfoto_2022-03-11_17-00-50](https://user-images.githubusercontent.com/79079633/157903147-d7e4769d-5773-454b-b0c0-0e7f0dd6e57a.png)

Also, check out this short video: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/releases/tag/v7.1

**Comment by wprojects** [comment]
@cryinkfly I checked the video and also I don't have the fusion-360 folder in my .config folder so I couldn't delete that file you mentioned. I ran launcher.sh and it doesn't update anything it just launches fusion and it still says the software isn't up to date

**Comment by cryinkfly** [comment]
Please look to this post: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/205

**Comment by wprojects** [comment]
@cryinkfly I am still getting that it has not updated. 

What I've done, I downloaded the fusion 360 again to the latest version just to make sure [https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/releases/tag/v7.1](url). I extract the files to my Documents folder, 

Then I go to this path:
/Documents/Autodesk-Fusion-360-for-Linux-7.1/files/builds/stable-branch/bin 

Once I'm there I do a chmod +x to launcher.sh and then run sudo./launcher.sh. There is never anything that asks me to update or anything, it just loads fusion like normal. 
Following post #205 steps, I went to the root of the folder and ran cat version.txt and got this below.  

![image](https://user-images.githubusercontent.com/57518634/160237304-7c17024d-1462-4d77-8fff-f916c2ae5b6c.png)
 
When I tried to look at the path, I can't even get into that directory so I'm not sure where you guys are getting this from 
![image](https://user-images.githubusercontent.com/57518634/160237402-eecccb39-ba67-47fa-96ca-9afe7d7907f1.png)


![image](https://user-images.githubusercontent.com/57518634/160237475-08f9a9e4-5d5e-4307-84fb-b220467645bc.png)

Is the problem that I don't have it installed in home? I checked my launcher.sh and I have the same lines as you. Any other suggestions on things to try? Like I said, launcher.sh does not check for any update or do anything at all other than just load fusion 360

**Comment by cryinkfly** [comment]
@wprojects 
> Is the problem that I don't have it installed in home?

Yes it's a very big problem! ⛔️

Because by installing Autodesk Fusion 360 using this command:

    mkdir -p "$HOME/.config/fusion-360/bin" && cd "$HOME/.config/fusion-360/bin" && wget -N https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/install.sh && chmod +x install.sh && bash install.sh && exit

... all folders and their paths are created automatically. ⚙️

For this reason your variant will not work because the paths etc. are wrong! 😉
