### ISSUE TITLE
Constant updates

### ISSUE THREAD

**Issue by Vermoot** [cryinkfly/Autodesk-Fusion-360-for-Linux#205]
It seems almost every time I start Fusion there's a new update, and I'm talking multiple times a day here.

Are Fusion 360 updates really that frequent?

**Comment by Vermoot** [comment]
```
Autodesk/Autodesk Fusion 360/API on  main [!]
❯ cat version.txt
2.0.12392%
```

When starting Fusion I can see the "Online version" and "System version" lines like in the video, but the "Online Version" line is blank. I'm guessing the launcher is comparing my system's version with an empty online version and deciding I need an update?

**Comment by cryinkfly** [comment]
Okay I see that you get a version number with **%** and this is the reason why you get this issue!
So I must change my function that we can solved this. :+1:

**Comment by cryinkfly** [comment]
>I'm guessing the launcher is comparing my system's version with an empty online version and deciding I need an update?

Can you check this file:

    $HOME/.config/fusion-360/bin/launcher.sh

![Bildschirmfoto_2022-03-23_15-52-39](https://user-images.githubusercontent.com/79079633/159727734-9340be76-3aea-4bcd-9f33-901e3079643a.png)

**Comment by Vermoot** [comment]
Awesome, glad I could help!
