### ISSUE TITLE
Splashscreen Stays after launch

### ISSUE THREAD

**Issue by Rushmore75** [cryinkfly/Autodesk-Fusion-360-for-Linux#209]
The splash screen stays up after the start-up finishes and just stays in the viewport

- 2.0.12665
- Ryzen Integrated (Radeon) llvmpipe (LLVM 12.0.1, 256 bits)
- Ubuntu 21.10
- Gnome 40.4.0
- DXVK
![Screenshot from 2022-03-30 08-21-06](https://user-images.githubusercontent.com/76796612/160757117-ebec0e7f-5407-41ab-80d8-ba5f1462d04c.png)

**Comment by cryinkfly** [comment]
@Rushmore75 Please, check this post here: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/79
