### ISSUE TITLE
Constant Updates

### ISSUE THREAD

**Issue by Gerlesh** [cryinkfly/Autodesk-Fusion-360-for-Linux#211]
**Describe the bug**
Fusion 360 updates every time it is launched, regardless of how recent it was last updated. If I don't update it, I cannot open most files.

**To Reproduce**
1. Open Fusion 360 from the provided desktop files.

**Expected behavior**
Only update when an update has not been installe

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360: 2.0.12670
- Graphics card model + Graphics card driver (Version number): NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] 
- Operating system (OpenSUSE Leap 15.3, Fedora 34, ...): Pop!_OS 21.10
- Desktop environment (XFCE 4.16, Gnome 40, ...): Gnome 40.4.0
- DXVK- or OpenGL-Mode: DXVK

Not fixed by other issue report

**Comment by cryinkfly** [comment]
Please issue the following command from the terminal to update the launcher file so that this problem no longer occurs:

    cd "$HOME/.config/fusion-360/bin" && wget -N https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/launcher.sh
