### ISSUE TITLE
Various graphical glitches

### ISSUE THREAD

**Issue by bishboshin** [cryinkfly/Autodesk-Fusion-360-for-Linux#212]
**Describe the bug**
Graphical glitches:
- browser panel has black transparent background
- menu items shown with glitches
- no coordinates grid background behind the model

**To Reproduce**
1. Start the Fusion 360
2. See the glitches

**Expected behavior**
no graphical glitches

**Screenshots**
![2022-04-04_21:45:51](https://user-images.githubusercontent.com/90864040/161630685-59cd36eb-3b43-4478-95c5-9d7b1f68931c.png)
![2022-04-04_21:45:13](https://user-images.githubusercontent.com/90864040/161630700-154f3790-6683-4d87-8d5f-ec23e089ded0.png)
![2022-04-04_21:44:58](https://user-images.githubusercontent.com/90864040/161630704-b29fe51d-e6a3-4aa0-b823-dc07aa6b7fdc.png)

**Laptop Asus UX533FD:**
- Autodesk Fusion 360 2.0.12376
- Intel UHD Graphics 620 (integrated, driver 22.0.0) and NVIDIA GeForce GTX 1050 Max-Q (driver 510.54.0) (same result on both GPUs)
- Arch Linux x86_64 kernel 5.17.1-arch1-1
- Qtile tiling window manager
- DXVK(followed instructions: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/79) and OpenGL-Mode - same result

**Additional context**

Console output:
Intel: https://gist.github.com/bishboshin/c280e4afdfababa513cb1c50e154a477
Nvidia: https://gist.github.com/bishboshin/1c3bdbc0e02e1e91550591e8045a6b91

Edited: added console output for two GPUs: intel and nvidia

**Comment by cryinkfly** [comment]
Please check this post here: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/213 🙂

**Comment by bishboshin** [comment]
Added the console output for two GPUs to the top post.
"sudo sysctl dev.i915.perf_stream_paranoid=0"
makes the "MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0" message go away, but the glitches stay, unfortunately.

**Comment by bishboshin** [comment]
I figured out the reason of one graphical glitch: it was just a picom making dark background of all the floating objects. After killing the picom Fusion window started to look better:
![Unsaved Image 2](https://user-images.githubusercontent.com/90864040/162812302-e1614951-4e7c-42b2-871d-7e6298df064e.jpg)
![Unsaved Image 1](https://user-images.githubusercontent.com/90864040/162812304-7988883c-098d-4b84-ae07-d4561953e234.jpg)
However, some glitches persist. I tried to install Fusion 360 from lutris repo - same performance. I also have the [#9](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/9) but it does not bother me as much as the glitchy sprites. =(

**Comment by cryinkfly** [comment]
Okay I was just experimenting with the rendering of Wine itself and figured out that there might be a bug there!

This problem now occurs when I set this with the help of winetricks:

> renderer=vulkan

![Bildschirmfoto_2022-04-13_14-50-33](https://user-images.githubusercontent.com/79079633/163184100-86bee4aa-4825-4df7-ac4c-1ab5329e4e5b.png)

**Comment by bishbosh-magic** [comment]
Update: everything is solved by installing a proton package and disabling shadows in picom as follows:
```
...
shadow-exclude = [
    "name = 'fusion360.exe'",
    "class_g = 'fusion360.exe'",
...
```
not sure which one of these worked, but it worked.
Regarding the proton: For this particular application, off course, it's bloated. It might be not the most elegant solution, but it works as it installs many things needed for optimal wine performance.
I still have some minor glitches, but that's already a different topic =) To be continued...
This topic can be marked as "SOLVED" at this point.

**Comment by bishbosh-magic** [comment]
Update: everything is solved by installing a proton package and disabling shadows in picom as follows:
```
...
shadow-exclude = [
    "name = 'fusion360.exe'",
    "class_g = 'fusion360.exe'",
...
```
not sure which one of these lines worked, but it worked. =)
Regarding the proton: For this particular application, off course, it's bloated. It might be not the most elegant solution, but it works, as it installs many things needed for optimal wine performance.
I still have some minor glitches, but that's already a different topic =) To be continued...
This topic can be marked as "SOLVED" at this point.

P.S.: I'm the author, but I forgot to which e-mail I have registered another account o_O

**Comment by bishboshin** [comment]
Update: everything is solved by installing a proton package and disabling shadows in picom as follows:
```
...
shadow-exclude = [
    "name = 'fusion360.exe'",
    "class_g = 'fusion360.exe'",
...
```
not sure which one of these lines worked, but it worked. =)
Regarding the proton: For this particular application, off course, it's bloated. It might be not the most elegant solution, but it works, as it installs many things needed for optimal wine performance.
I still have some minor glitches, but that's already a different topic =) To be continued...
This topic can be marked as "SOLVED" at this point.

**Comment by bishboshin** [comment]
Update: everything is solved by installing a proton package and disabling shadows in picom as follows:
```
...
shadow-exclude = [
    "name = 'fusion360.exe'",
    "class_g = 'fusion360.exe'",
...
```
not sure which one of these lines worked, but it worked. =)
Regarding the proton: For this particular application, off course, it's bloated. It might be not the most elegant solution, but it works, as it installs many things needed for optimal wine performance.
I still have some minor glitches, but that's already a different topic =) To be continued...
This topic can be marked as "SOLVED" at this point.

**Comment by cryinkfly** [comment]
@bishboshin Can you can describe the steps, please?

**Comment by bishboshin** [comment]
> @bishboshin Can you can describe the steps, please?

Well, I did two things: 1. installed the proton package, 2. disabled picom for the Fusion 360.
1. The proton package is available in AUR for Arch-based systems: https://aur.archlinux.org/packages/proton
In my case, I used the yay-helper to install it: `yay -S proton`
This helped to get rid of this kind of glitches:
![image](https://user-images.githubusercontent.com/90864040/187300083-bbbfe8c9-fd42-4234-b9c6-91d4f67b835a.png)
To my opinion, installing proton is far from being an elegant solution. Because proton is installing a lot of stuff. It's a very big package. Probably, it is possible to tweak some Wine settings or installing some smaller packages instead of installing the bloated proton package, but it worked for me for now. Probably, when I need to install it another time, I will try to figure out what worked exactly. Maybe it was just one of the libraries from the proton dependencies, that caused things to work properly. I'm not sure at this point.
2. Unwanted shadows like here:
![image](https://user-images.githubusercontent.com/90864040/187301088-572a0a5a-adf8-487c-b3e3-0d9f10a2922f.png)
Were fixed by making an exception for picom, which I use in my setup for some fancy transactions in my qtile windows manager. It's also described on the Arch wiki page how to do that. In my case, I needed to add some lines to the ~/.config/picom.conf file:
```
...
shadow-exclude = [
    "name = 'fusion360.exe'",
    "class_g = 'fusion360.exe'",
...
```
you can see the class and the name of the Fusion 360 window by running xprop and clicking on it's window when it is running. The output is a bit cryptic, but you only need to look for the variables called "...NAME..." or "...CLASS...". In my case it was "fusion360.exe" as described above.

**Comment by bishboshin** [comment]
> I have found these posts here:
> 
>     * https://superuser.com/questions/1554422/disable-font-smoothing-in-wine
> 
>     * https://www.wine-reviews.net/2009/03/how-to-enable-font-anti-aliasing-in.html

It can easily be, that during the proton installation, these settings are set in the proper way and that causes the problem to go away. Next time I will try these two first.

**Comment by AkashicSeer** [comment]
I'm using fusion360 on Windows 10 and noticing bugs too. Some like what is mentioned here and now random GUI issues. Floating "text commands" and "comments" menu that won't go away, no obvious way to close it just have to move it. Now the history timeline is POOF GONE. Now when I try to open fusion360 it opens a browser tab and has me sign in then says "opening product" Then I have to close the browser tab and click the fusion 360 icon. You mean that couldn't be part of the program opening, you have to open a browser now? Sweep doesn't seem to work correctly when trying to create a lip inside an object like a box, it now says it may intersect itself or some silly message and won't do it. When did that change? I've used it many times to create lips inside hollow objects. 

Why would I pay $70 a month for this? I don't get it. Or is it more now?
