### ISSUE TITLE
Fusion 360 asks to update and then does nothing

### ISSUE THREAD

**Issue by dukenukemx** [cryinkfly/Autodesk-Fusion-360-for-Linux#224]
I tried running your script on my Linux Mint 20 machine and when it's done installing and I try running Fusion 360 it asks to update and then I say no and then nothing else happens.  This is as far as I go before it quits.
![fusion 360](https://user-images.githubusercontent.com/31163475/166128216-4e32df3f-9d74-483b-b730-6681dbb8241c.png)

**Comment by dukenukemx** [comment]
Here's what I screen shotted before the terminal window closed.  
![fusion 360 terminal](https://user-images.githubusercontent.com/31163475/166128272-d8648f50-6716-47dc-a456-7fcbc09821b0.png)

**Comment by madygulov** [comment]
Same problem. 
Installation completed without error but it looks like Fusion has not been installed completely. There is no links in windows menu and `Fusion360.exe` is not found anywhere in the homedir. 

Ubuntu 20.04. 
Wine-7.7
```
> find ~ -name Fusion360.exe
>                          
```

UPD: It appeared after running
```
> env WINEPREFIX=/home/$USER/.wineprefixes/fusion360 wine /home/$USER/.wineprefixes/fusion360/dosdevices/c:/users/$USER/Downloads/Fusion360installer.exe
```

Now `Fusion360.exe` exists and can be launched with command
```
env WINEPREFIX=/home/$USER/.wineprefixes/fusion360 wine /home/$USER/.wineprefixes/fusion360/dosdevices/c:/Program\ Files/Autodesk/webdeploy/production/22651d53e422c0183a6147899471ab1dca9a3f80/Fusion360.exe
```

UPD2: not working as expected — white window. But it's can be due to video or something like that.

**Comment by cryinkfly** [comment]
@madygulov 

> UPD2: not working as expected — white window. But it's can be due to video or something like that.

That could very well be possible, but it could also be that something hasn't been configured correctly. Are you using DXVK or OpenGL?

**Comment by dukenukemx** [comment]
> @madygulov
> 
> > UPD2: not working as expected — white window. But it's can be due to video or something like that.
> 
> That could very well be possible, but it could also be that something hasn't been configured correctly. Are you using DXVK or OpenGL?
I tried the same command as @madygulov suggested and I also get a white screen.  When I run the Fusion 360 installer as is with my WineStaging installation I also get the white screen.  I did select DXVK with your script but I've also installed DXVK on my WIneStaging install via Winetricks.  Same white screen.  This should be the login screen.  Doing a bit of searching and this white screen is a common problem for anyone installing Fusion360.  

I'm using a Vega 56 with Kisak PPA for drivers.  Don't know if Madygulov is also using Kisak drivers.  I'm also using Xanmod kernel as well.  I'll link both.
https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa
https://xanmod.org/

**Comment by madygulov** [comment]
> @madygulov
> 
> > UPD2: not working as expected — white window. But it's can be due to video or something like that.
> 
> That could very well be possible, but it could also be that something hasn't been configured correctly. Are you using DXVK or OpenGL?

The white screen does not looks like graphics error. As far as I remember, it responds to mouse clicks, there is context menu which looks like its embedded web page, and there is one space symbol which can be selected.

**Comment by madygulov** [comment]
I have no idea which drivers i have. The point was that Fusion is not installing without fails. 
ps: Sorry for stealing topic.

**Comment by cryinkfly** [comment]
Please check this here: 
- https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/79
- https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/8

**Comment by dacobi** [comment]
I'm also getting the /fusion360/drive_c/users/.../AppData/Roaming/Autodesk/Autodesk Fusion 360/API/version.txt': No such file or directory

After installation.
Tried both with DirectX and OpenGL

**Comment by dukenukemx** [comment]
Has anyone found a solution yet?

**Comment by dacobi** [comment]
> Has anyone found a solution yet?

I managed to get it working but not quite sure how.

I ran the installer manually like madygulov did, except I used "Fusion 360 Client Downloader.exe"
This only gave a white screen but I waited a long time until there were no longer any output form Wine in the console.
After this I had Fusion360.exe and FusionLauncher.exe and while Fusion360.exe started with Wine the Launcher complained about missing FusionLauncher.exe.ini, so I copied this and modified from an install in VirtualBox/Win10

Now FusionLauncher.exe worked and the launcher.sh also starts Fusion. Somehow starting it with Wine has created the API/version.txt

Only thing not working is Desktop icon.

**Comment by BaronVonSatchel** [comment]
I am having the same issue on Linux Mint 20.2 Cinnamon. No version.txt, manually running Fusion360installer.exe gives a white screen like others experienced. For me, I can't even close the installer normally, I have to kill it via System Monitor. It does not appear to be downloading in the background, since there is no output from wine and my network shows usage in the tens of bytes/s. Tried DXVK and OpenGL, the output is the same.

**Comment by dukenukemx** [comment]
>

**Comment by dukenukemx** [comment]
> > Has anyone found a solution yet?
> 
> I managed to get it working but not quite sure how.
> 
> I ran the installer manually like madygulov did, except I used "Fusion 360 Client Downloader.exe" This only gave a white screen but I waited a long time until there were no longer any output form Wine in the console. After this I had Fusion360.exe and FusionLauncher.exe and while Fusion360.exe started with Wine the Launcher complained about missing FusionLauncher.exe.ini, so I copied this and modified from an install in VirtualBox/Win10
> 
> Now FusionLauncher.exe worked and the launcher.sh also starts Fusion. Somehow starting it with Wine has created the API/version.txt
> 
> Only thing not working is Desktop icon.
I'm willing to bet there's an issue with DXVK and rendering the white screen properly.  This had worked before right, for others?  Do Nvidia users have this issue?  AMD now turns on ACO by default so does this have an effect?  I think the first step is to figure out when this installer worked and what brand GPU people are using.  Intel could be in the same situation with AMD since they both use open source drivers while Nvidia doesn't.  Well... they haven't until last week.

**Comment by BaronVonSatchel** [comment]
I am on Nvidia proprietary drivers, so it is not GPU manufacturer specific

**Comment by MrAdam1983** [comment]
I just started a discussion about this but this maybe a more fitting location.  it looks to me that the version file is either downloading to the wrong location or the script is looking for it in the wrong location. 

From the script as it downloads.

wget -N -P $HOME/.config/fusion-360/bin https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/build-version.txt
online_build_version=cat $HOME/.config/fusion-360/bin/build-version.txt | awk 'NR == 1' online_build_insider_version=cat $HOME/.config/fusion-360/bin/build-version.txt | awk 'NR == 2'
echo "Online Build-Version: $online_build_version"

then it looks for the version file in a different location with a different file name.....right?

system_build_version=`cat $HOME/.wineprefixes/fusion360/drive_c/users/$USER/AppData/Roaming/Autodesk/Autodesk\ Fusion\ 360/API/version.txt

Either way, the file in the second location does not exist. I saw a discussion where it was said to create the file but I don't follow the syntax.

I am missing the location

Autodesk\ Fusion\

which is easy enough to create, but then exactly how is the file supposed to be formatted and created?

360/API/version.txt

Or should that be a full location and a file name such as:

Autodesk\ Fusion360\API\Version.txt

I have run through this several times and it seems to me (as mostly a noob) that it is looking for the same file by 2 different names in 2 different locations
[launcher.txt](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/files/8748022/launcher.txt)
.

**Comment by cryinkfly** [comment]
Please look here: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/232#issuecomment-1144487489
