### ISSUE TITLE
Install YAD on my computer *solved*

### ISSUE THREAD

**Issue by cryinkfly** [cryinkfly/Autodesk-Fusion-360-for-Linux#233]
#### Debian based systems:

    sudo apt-get update && sudo apt-get install software-properties-common yad

#### Red Hat based systems:

    sudo dnf update && sudo dnf install yad

#### Arch based systems:

    sudo pacman -Sy --needed yad

#### openSUSE based systems:

    su -c 'zypper up && zypper install yad'

#### Void based systems:

    sudo xbps-install -Sy yad

#### Solus based systems:

    sudo eopkg install yad

#### Gentoo based systems:

    sudo emerge -av gnome-extra/yad

**Comment by BluCobalt** [comment]
Quick note for Gentoo users: `yad` is only available in guru; if you don't have guru in your `eselect repository list -i` run a quick `eselect repository enable guru` and `emerge --sync` before you try installing it.
