### ISSUE TITLE
Install script error

### ISSUE THREAD

**Issue by cykloCNC** [cryinkfly/Autodesk-Fusion-360-for-Linux#241]
Hi there,
great work with running Fusion360 on linux. Thanks for all the work!
But is seem with every script update,there are more problems:

fusion wont start properly via menu launcher ( if present at all) in menu. using xterm from command line solves this:
xterm -hold -e "$HOME/.fusion360/bin/launcher.sh"

**LinuxMint19.3:** ( all default,newest fusion and install, RTX 2070, older and updated NVidia drivers)

wrong wineprefix and launcher path after clean install. "WP_BOX" insnt working. i had to change 

LAUNCHER="$(find $WP_BOX -name Fusion360.exe -printf "%T+ %p\n" | sort -r 2>&1 | head -n 1 | sed -r 's/.+0000000000 (.+)/\1/')" && WINEPREFIX="$WP_BOX" wine "$LAUNCHER"

to 
LAUNCHER="$(find $HOME/.fusion360/wineprefixes/default -name Fusion360.exe -printf "%T+ %p\n" | sort -r 2>&1 | head -n 1 | sed -r 's/.+0000000000 (.+)/\1/')" && WINEPREFIX="$HOME/.fusion360/wineprefixes/default" wine "$LAUNCHER"

DXVK- unusable, to many graphical issues/lags/black stripes - was "ok" in previous installs
OpenGL- very good in previous installs, no black stripes on new dialogs or resize, now same problem as here https://user-images.githubusercontent.com/90864040/161630704-b29fe51d-e6a3-4aa0-b823-dc07aa6b7fdc.png 
i have this problem too in OpenGL Debian10 Intel graphic,discussion here lead to intel problem, but now i have this on NVidia 2070 Super too in DXVK or OpenGL

**Debian 10:** (delault, changed folders, DXVK,OpenGL)
on my CNC machine with intergated Intel GPU. fusion inst running for a month now:( new install script crashes/close after choosing directory without any log/warning. (previous install has missing files, i think it was NET.frame related)

My question is: do you store older setting from installs? In my experience wine v.7+-  and your installs with default OpenGL was good and stable

Question 2: can i support you anyhow? i can do testing on Debian10 and LinuxMint19.3 and i would be happy to help.
Thank you

**Comment by cryinkfly** [comment]
@cykloCNC 

> My question is: do you store older setting from installs? In my experience wine v.7+- and your installs with default OpenGL was good and stable

Yes, I save certain settings, but the problem is that with every new Wine version, there are some changes that make some functions work better and some work worse.

And for this reason I'm currently looking at various solutions from the gaming world in order to be able to create a usable solution from them. (Steam Proton, ...)

> Question 2: can i support you anyhow? i can do testing on Debian10 and LinuxMint19.3 and i would be happy to help.
Thank you

Yes, there are different ways to [support](https://github.com/cryinkfly/cryinkfly/blob/main/SPONSORSHIP.md#become-a-supporter) me in my work. You have already used one of these ways! :+1:

**Comment by cykloCNC** [comment]
> Yes, I save certain settings, but the problem is that with every new Wine version, there are some changes that make some functions work better and some work worse.

As a milestone i can point install script before "autoupdate" , that runs great on Debian 10 (linuxCNC), openGL. I think it was wine 6.8.
Could it be possible to modify your scripts with these "old" settings to run new versions of Fusion?

On my CNC machine i can run only linux because of controll unit, thus Fusion on linux is only way to generate simple CAM programs.

Can you provide "old" settings or modify your scripts? I have no problem with some kind of revenue. Thanks a lot.

**Comment by cryinkfly** [comment]
So, I change step by step my [documentation](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/wiki/Documentation) for all users they will install Autodesk Fusion 360 on Linux without my setup wizard or will get more information.

**Comment by cykloCNC** [comment]
You are the best! Thanks for sharing of detailed install info. Finally i have fusion again running on Debian buster cnc machine. Running on wine stable 7.0. unfortunately i was unable to start fusion in openGL ( DX9 poor performance). Did you make any changes to openGL config files since wine 6.8+? thanks for answer

wine 7.0 - no problems as described here https://user-images.githubusercontent.com/90864040/161630704-b29fe51d-e6a3-4aa0-b823-dc07aa6b7fdc.png

**Comment by cryinkfly** [comment]
I haven't made any other changes. However, a lot has changed since the April update of Fusion 360.
