### ISSUE TITLE
Lots of failures during install.

### ISSUE THREAD

**Issue by factorioplayer** [cryinkfly/Autodesk-Fusion-360-for-Linux#246]
I don't know what to make of this. There's lots and lots of lines that read
`wine: could not open working directory L"unix\\home\\one\\.fusion360\\bin\\", starting in the Windows directory.` Some of it seemed to be installing/registering fonts. Much of it seemed to be significantly more important.
The installer finishes with
`The installation is completed!
FALSE`
And trying to launch F360 which reads
> Configuration file 'C:\Program Files\Autodesk\webdeploy\production\some-string-of-numbers-and-letters\FusionLauncher.exe' is missing or incomplete. Please re-install...'

I'm not sure what else to paste in here. The terminal output far exceeds the 10,000 lines my window holds, and those "could not open working directory" messages were all over the whole thing. I've attached the setup log from ~/.fusion360/logs, but it doesn't look like there's a whole lot there. But what do I know?
[setupact.log](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/files/8930946/setupact.log)
.

**Comment by Diazblo** [comment]
(Assuming you selected default wineprefix) Can you check if Fusion360.exe exists in ~/.fusion360/wineprefix/drive_c/Program Files/Autodesk/webdeploy/production/3dd5f1c145923035964be467e698157c79d9caeb/

**Comment by JakeT23cool** [comment]
I have the same issue: using arch, def wineprefix and following all listed instructions. The directory 3dd5f1c145923035964be467e698157c79d9caeb does not exist for me but 5504...f523 and 6a0c...17c3 do.
Any help will be appreciated :)

**Comment by JakeT23cool** [comment]
same as [issue](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/240)

**Comment by cryinkfly** [comment]
Please check this: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/248

**Comment by shawly** [comment]
The message `wine: could not open working directory L"unix\\home\\one\\.fusion360\\bin\\", starting in the Windows directory.` appears because wine can not open directories outside of it's wineprefix, it's more or less just a warning and it will default to the c_drive/windows folder instead.

You can technically get rid of this message if you first `cd ~/.fusion360/wineprefixes/default/drive_c` and then execute `~/.fusion360/bin/install.sh`.

@cryinkfly might make sense to change the working directory for all wine commands to `wineprefixes/default/drive_c` or `wineprefixes/default/drive_c/users/$USER` so the warning will stop.

**Comment by mackinlay53** [comment]
1. I had the same issue when trying to install and got the message `wine: could not open working directory L"unix\\home\\one\\.fusion360\\bin\\`, starting in the Windows directory."  **MANY THANKS** to @shawly for his fix, i had been beating myself to a pulp trying and failing to work this out.  I did find his workaround to be all I needed to get things going!

2. I had another issue, @cryinkfly please take note, the SP_OS_SELECT in the "locale.xx.sh" file is missing an entry for "Linux Mint 21.x", although the actions in "install.sh" are there for "Linux Mint 21.x" you can't execute them without the OS being listed and selected in the OS selection drop-down list.

3. Finally, another issue for @cryinkfly, in my case I ran into the apt-key deprecation issue.  I found my hack below to be adequate for my case and enabled Fusion360 to fully install this morning.  There may be a more elegant solution needed to generalize for all cases.

**ORIGINAL CODE** 
`wget -q https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_22.04/Release.key -O Release.key -O- | sudo #apt-key add -`

**WORKING REPLACEMENT** 
`wget -q https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_22.04/Release.key -O- | sudo tee  /usr/share/keyrings/Ubuntu22p04-Release-archive.key.gpg` 


**ADDED NOTE**
I modified two scripts to solve my issues, and placed them on my Desktop.  During the execution of the following command line these files replace the original installed files.

`cd $HOME && rm -r  $HOME/.fusion360 && mkdir $HOME/.fusion360 && mkdir $HOME/.fusion360/wineprefixes && mkdir $HOME/.fusion360/wineprefixes/default && mkdir $HOME/.fusion360/wineprefixes/default/drive_c && mkdir -p "$HOME/.fusion360/bin" && cd "$HOME/.fusion360/bin" && wget -N https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/install.sh && chmod +x install.sh && cd $HOME/.fusion360/wineprefixes/default/drive_c && cp ~/Desktop/locale-en.sh $HOME/.fusion360/bin/locale-en.sh  && cp ~/Desktop/install.sh $HOME/.fusion360/bin/install.sh   && $HOME/.fusion360/bin/install.sh `
 
Thanks to everyone on this script.  I'm **thrilled** to be running Fusion360 this morning on Linux Mint 21.

...Patrick
