### ISSUE TITLE
FusionLauncher.exe.ini is missing or incomplete

### ISSUE THREAD

**Issue by robcrossland** [cryinkfly/Autodesk-Fusion-360-for-Linux#249]
**Describe the bug**
Launching the application gives a fatal error relating to an incomplete file and suggesting the application needs to be reinstalled.

**To Reproduce**
Carry out a completely default installation without extensions. Launch the application and await the error message.

**Expected behavior**
Application should launch completely ready for work to begin.

**Screenshots**
![image](https://user-images.githubusercontent.com/6988501/175834714-91449d0a-6251-4af6-aa3d-263195827131.png)

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360: latest
- Graphics card model + Graphics card driver (Version number): Mesa Intel Iris Graphics 5100 (HSW GT3) v: 4.6 Mesa 22.1.1
- Operating system: OpenSUSE Tumbleweed Linux 5.18.4-1-default
- Desktop environment: Plasma
- DXVK- or OpenGL-Mode: DXVK

**Additional context**
I originally thought this was related to the 'splash screen' being black, however attempts on different hardware where the screen renders properly has the same end result.

**Comment by savanton** [comment]
Same error here. 
Ubuntu 22.04, Gnome, Nvidia.

**Comment by cryinkfly** [comment]
Please look here: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/248
