### ISSUE TITLE
Installer hangs on installing fonts

### ISSUE THREAD

**Issue by pixartist** [cryinkfly/Autodesk-Fusion-360-for-Linux#253]
**Describe the bug**
The installer will hang after installing  Navilu.ttf

**To Reproduce**
1. Install on ubuntu 22.04

**Expected behavior**
Installer will finish

**Screenshots**
![image](https://user-images.githubusercontent.com/628738/177037512-25eba2e5-b8fa-4dcd-8583-fe59d12b9e58.png)

**Desktop (please complete the following information):**
- Picked by installer
- Irrelevant (rtx 3080)
- Ubuntu 22.04 LTS
- Gnome 42.2
- DXVK

**Additional context**
Last installer msg: ´´´0688:fixme:font:get_nearest_charset returning DEFAULT_CHARSET face->fs.fsCsb[0] = 00000000 file = L"\\??\\unix\\usr\\share\\fonts\\truetype\\Navilu\\Navilu.ttf"´´´

**Comment by cryinkfly** [comment]
https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/263
