### ISSUE TITLE
The script uses "sleep N" instead of "wait"

### ISSUE THREAD

**Issue by mikkorantalainen** [cryinkfly/Autodesk-Fusion-360-for-Linux#256]
For example:

https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/blob/7ce47fb79edc2027e8e228e0d577277a4c3c11a4/files/builds/stable-branch/bin/install.sh#L1051

The script uses "sleep 5" to supposedly wait for the process running in the background. Use shell built-in `wait` instead to continue waiting if the background process is not ready after 5 seconds AND to skip waiting if background process is ready faster.

The script contains other sleep commands, too, and I assume those have similar reasons and should be fixed, too.

**Comment by cryinkfly** [comment]
You mean this one here: https://www.networkworld.com/article/3632395/sleeping-and-waiting-on-linux.html
