### ISSUE TITLE
Error while executing the script in Arch Linux

### ISSUE THREAD

**Issue by nilfernandezfernandez** [cryinkfly/Autodesk-Fusion-360-for-Linux#264]
wine: could not open working directory L"unix\\home\\nil\\.fusion360\\bin\\", starting in the Windows directory.

I have multiple errors like this.

**Comment by MrAdam1983** [comment]
you will need to provide more information: 
At what point during the process does this occur? during installation? during first startup?

What OS are you running?

**Comment by gromain** [comment]
Same issue, happens during installation, right at the beginning.

**Comment by AlistairKeiller** [comment]
Same issue here

**Comment by OJFord** [comment]
I see similar in installation, but after fixing #273 it seemed to proceed and install ok anyway (seemingly) despite these errors - dialogs popping up to install extensions I'd selected that I hadn't seen before - but then on launch:
```
wine: could not open working directory L"unix\\home\\$USER\\.fusion360\\", starting in the Windows directory.
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.
```

> What OS are you running?

Linux (Arch), as OP.

**Comment by OJFord** [comment]
Ah,
> wine: could not open working directory

is resolved (if it's even a problem) by running from within `wineprefixes/default/drive_c`.

The rest seems to be the actual error though.

**Comment by OJFord** [comment]
Works after removing everything (because uninstall was broken too) and running `../../../bin/install.sh` from the `drive_c` directory. (i.e. manually `mkdir -p wineprefixes/default/drive_c` first.)

**Comment by Agent123983** [comment]
@OJFord Do you have more details on how you fixed this? I can't seem to recreate.

**Comment by epicfacethe3rd** [comment]
I seem to be running into this issue on kubuntu 23.10 myself. @OJFord could you expain what you're talking about in a bit more detail? i'm not sure if I follow

**Comment by OJFord** [comment]
I don't recall any more details, but fwiw I gave up on trying to run Fusion on Linux, not for this issue specifically, but just the general flakiness of getting it to run at all and then not performing well anyway.
