### ISSUE TITLE
Update found Ok/Cancel actions are the wrong way around *solved*

### ISSUE THREAD

**Issue by OJFord** [cryinkfly/Autodesk-Fusion-360-for-Linux#274]
**Describe the bug**
On launch, it checks for an update. After the first connecting dialog is dismissed by 'ok', if an update has been found a new dialog informs you of that, and presents two options: 'gtk-cancel' and 'gtk-ok'.

'gtk-ok' dismisses the dialog, and a new one opens saying 'update skipped, please update soon'.

On a whim, this time I tried 'gtk-cancel'. Sure enough, it does the update 😅.

**To Reproduce**
1. Wait for update
2. Launch
3. Select Ok, observe no update
4. Quit & re-launch
5. Select Cancel this time, observe update

**Expected behavior**
Ok should update, cancel should not.

**Comment by cryinkfly** [comment]
Okay, I check this in the next time. :+1:
