### ISSUE TITLE
Can't Open Projects saved on current Windows Release of Fusion 360 due to Fusion 360 on Linux being out of date and not updating

### ISSUE THREAD

**Issue by ChaosBlades** [cryinkfly/Autodesk-Fusion-360-for-Linux#275]
**Describe the bug**
I am trying to open projects and they all report I need a newer version of Fusion 360. Fusion 360 does not ever update so I did a fresh install by deleting my Bottle and setting it back up. Still it reports my project was saved on a newer version of Fusion 360 and can't open. Fusion 360 still never tries to update.

**To Reproduce**
1. Install Fusion 360 on Windows.
2. Save a project
3. Load Fusion 360 via Bottles
4. Try to load the project you saved
5. See error

**Expected behavior**
Fusion 360 to stay up to date.

**Screenshots**
![Screenshot from 2022-09-29 03-25-51](https://user-images.githubusercontent.com/7530545/192967289-de03097f-e849-4ffb-a8bb-20eb9abcc188.png)

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360......................................Linux 2.0.13881 Windows 2.0.14337
- Graphics card model + Graphics card driver (Version number)....6900XT  Mesa 22.3.0-devel
- Operating system (OpenSUSE Leap 15.3, Fedora 34, )...............Pop!_OS 22.04 LTS x86_64
- Desktop environment (XFCE 4.16, Gnome 40, )..........................GNOME 42.3.1
- DXVK- or OpenGL-Mode..............................................................Whatever is Bottles default

**Comment by sinbadsalmon** [comment]
See [solution here](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/292#issuecomment-1706989835)
