### ISSUE TITLE
Detecting unsupported Operating System

### ISSUE THREAD

**Issue by Patschke** [cryinkfly/Autodesk-Fusion-360-for-Linux#278]
**Describe the bug**
I tried to update fusion by downloading the latest installer and running it again (due to #275 being an issue that prevented me from opening my files). Afterwards I end up with this message: 

![screen](https://user-images.githubusercontent.com/17853362/198217438-bfd39697-0e6f-414e-a780-ead987807d1f.png)

**To Reproduce**
I've tried to update via downloading the latest Fusion installer and running the install part of https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/wiki/Documentation#installation-of-autodesk-fusion-360 (`WINEPREFIX=$HOME/.fusion360/wineprefixes/default wine $HOME/.fusion360/wineprefixes/default/drive_c/users/$USER/Downloads/Fusion360installer.exe`)

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360: Can't tell - it won't launch
- Operating system: Arch Linux
- Desktop environment: i3

**Comment by cryinkfly** [comment]
Which Windows Version is configured in this box?

**Comment by Tony763** [comment]
Hi @Patschke, try to run  `WINEPREFIX=$HOME/.fusion360/wineprefixes/default wine winecfg` and set windows version to `Windows 10`.

![image](https://user-images.githubusercontent.com/5598750/219578602-9c94da06-5e81-46f5-a494-d03a47a7bcd0.png)

![image](https://user-images.githubusercontent.com/5598750/219578321-f5e143cf-aead-4018-bb41-6d3727143951.png)

**Comment by Patschke** [comment]
Not sure if this actually was what resolved this issue for me, or if some updates of other stuff took place in between - I did not try again before doing this. However, I'm now able to run Fusion again using my setup. So thanks for the help!
