### ISSUE TITLE
launcher error

### ISSUE THREAD

**Issue by Wailshire** [cryinkfly/Autodesk-Fusion-360-for-Linux#284]
hello, i get an error when i try to run de launcher.sh inside de bin folder, is seems like it is a syntax error, it return the following

`launcher.sh: 32: Syntax error: "}" unexpected
`

Any idea? or im missing something? thanks!

**Comment by cryinkfly** [comment]
Can you describe your problem better for me please? Or look here: https://unix.stackexchange.com/questions/45781/shell-script-fails-syntax-error-unexpected 🙂

**Comment by Samaniegomx** [comment]
#

> hello, i get an error when i try to run de launcher.sh inside de bin folder, is seems like it is a syntax error, it return the following
> 
> `launcher.sh: 32: Syntax error: "}" unexpected `
> 
> Any idea? or im missing something? thanks!

I have the same problem, when I try to run the launcher.sh, ./launcher.sh: 25: function: not found

![Captura de pantalla de 2022-12-18 02-36-44](https://user-images.githubusercontent.com/24280875/208288889-b8f8fbb5-8145-4342-a489-8c8ee21f429a.png)

**Comment by Samaniegomx** [comment]
> hello, i get an error when i try to run de launcher.sh inside de bin folder, is seems like it is a syntax error, it return the following
> 
> `launcher.sh: 32: Syntax error: "}" unexpected `
> 
> Any idea? or im missing something? thanks!

Try with bash launcher.sh, it works for me!
