### ISSUE TITLE
0138:err:module:import_dll Library not found when try to start box-run.sh

### ISSUE THREAD

**Issue by valqk** [cryinkfly/Autodesk-Fusion-360-for-Linux#286]
**Installed package on Debian 11 and can't run it after that.**
Debian 11 with installed pacakges:
ii  fonts-wine                          5.0.3-3
ii  libwine:i386                        5.0.3-3        
ii  libwine-development:amd64           4.2-4+b1       
ii  libwine-development:i386            4.2-4+b1       
ii  wine-staging                        7.20-bullseye-1
ii  wine-staging-amd64                  7.20-bullseye-1
ii  wine-staging-i386:i386              7.20-bullseye-1
ii  wine32:i386                         5.0.3-3        
ii  wine32-development:i386             4.2-4+b1       
ii  wine32-development-preloader:i386   4.2-4+b1       
ii  wine64-development                  4.2-4+b1       
ii  wine64-development-preloader        4.2-4+b1       
ii  winehq-staging                      7.20-bullseye-1
ii  winetricks                          0.0+20210206-2 

$ wine --version
wine-7.20 (Staging)

After installation selected 'Run' but app will not start.
Tried to ln -s $dll ${dl^^} (symlink to dll with upper case name) - nothing changed.

when running box-run.sh
I get:

002c:fixme:winediag:LdrInitializeThunk wine-staging 7.20 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

0098:err:ole:start_rpcss Failed to start RpcSs service
wine: Unhandled page fault on read access to 0000000000000000 at address 000000006B082848 (thread 0088), starting debugger...
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0108:fixme:imm:ImeSetActiveContext (0000000000020036, 0): stub
0108:fixme:imm:ImmReleaseContext (000000000002003E, 0000000000020036): stub
0124:fixme:imm:ImeSetActiveContext (000000000001005C, 1): stub
0124:fixme:imm:ImmReleaseContext (000000000003004A, 000000000001005C): stub
0138:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\Autodesk\\webdeploy\\production\\96a31d03bc575ff47e83b445639b5f6bf3c08c6f\\Qt5Gui.dll") not found
0138:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\Autodesk\\webdeploy\\production\\96a31d03bc575ff47e83b445639b5f6bf3c08c6f\\Qt5Gui.dll") not found
0138:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\Autodesk\\webdeploy\\production\\96a31d03bc575ff47e83b445639b5f6bf3c08c6f\\Fusion360.exe") not found
0138:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\Autodesk\\webdeploy\\production\\96a31d03bc575ff47e83b445639b5f6bf3c08c6f\\Qt5Gui.dll") not found
0138:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\Autodesk\\webdeploy\\production\\96a31d03bc575ff47e83b445639b5f6bf3c08c6f\\Qt5Gui.dll") not found

............. A LOT OF such lines for different dlls here ...................

0138:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\Autodesk\\webdeploy\\production\\96a31d03bc575ff47e83b445639b5f6bf3c08c6f\\Qt5Widgets.dll") not found
0138:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\Autodesk\\webdeploy\\production\\96a31d03bc575ff47e83b445639b5f6bf3c08c6f\\Qt5Widgets.dll") not found
0138:err:module:import_dll Library Qt5Widgets.dll (which is needed by L"C:\\Program Files\\Autodesk\\webdeploy\\production\\96a31d03bc575ff47e83b445639b5f6bf3c08c6f\\ClientDataUI.dll") not found
0138:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\Autodesk\\webdeploy\\production\\96a31d03bc575ff47e83b445639b5f6bf3c08c6f\\Qt5Gui.dll") not found
0138:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\Autodesk\\webdeploy\\production\\96a31d03bc575ff47e83b445639b5f6bf3c08c6f\\Qt5Gui.dll") not found
0138:err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Program Files\\Autodesk\\webdeploy\\production\\96a31d03bc575ff47e83b445639b5f6bf3c08c6f\\ClientDataUI.dll") not found
0138:err:module:import_dll Library ClientDataUI.dll (which is needed by L"C:\\Program Files\\Autodesk\\webdeploy\\production\\96a31d03bc575ff47e83b445639b5f6bf3c08c6f\\NuBase10.dll") not found
0138:err:module:import_dll Library NuBase10.dll (which is needed by L"C:\\Program Files\\Autodesk\\webdeploy\\production\\96a31d03bc575ff47e83b445639b5f6bf3c08c6f\\Fusion360.exe") not found
0138:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files\\Autodesk\\webdeploy\\production\\96a31d03bc575ff47e83b445639b5f6bf3c08c6f\\Fusion360.exe" failed, status c0000135

**Comment by JoshuaS3** [comment]
This happens to me when I try to set a different install directory via the wizard than where the install script is. I suspect something to do with the WINEPREFIXES variable but I'm not sure, I just reinstalled without setting a custom install directory in the wizard.

**Comment by valqk** [comment]
I wasn't able to install in different directory AT ALL. Deleted everything and reinstalled with default prefix... contents are in ~/.fusion360/wineprefixes/ ...

**Comment by CarrollDiehl** [comment]
I have exactly the same problem. After reinstalling into the default directory, it wouldn't start again.
When running the box-run.sh I receive the same errors as mentioned above.

To uninstall, I manually removed $HOME/.fusion360 and $HOME/.local/share/applications/wine/Programs/Autodesk

The installation is using a preinstalled wine-staging (7.21).

When installing, it already rains errors like: 

`wine: could not open working directory L"unix\\home\\carro\\.fusion360\\wineprefixes\\default\\", starting in the Windows directory.
`

I'll attach the outputs of my install and the box-run.sh as files. If you need more information, I'll gladly provide them (: 
[Fusion360 outputs.zip](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/files/10003148/Fusion360.outputs.zip)

**Comment by CarrollDiehl** [comment]
Another thing I recognized: During the multiple installation attempts I performed (a scientist here - doing the same routine and still expecting a different result) the wine-preloader "unexpectedly stopped" during most of them.

So I tried reinstalling wine, but it unfortunately did not work as well.

**Comment by valqk** [comment]
Weird. I still have no luck getting it running. Same errors every time. How did you exactly did it?
