### ISSUE TITLE
How to update fusion 360?

### ISSUE THREAD

**Issue by Rafgas** [cryinkfly/Autodesk-Fusion-360-for-Linux#287]
### Discussed in https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/discussions/269

<div type='discussions-op-text'>

<sup>Originally posted by **rcludwick** September  6, 2022</sup>
When I run fusion 360 through the launcher, a dialog window pops trying to connect to a server.  

If I hit ok, it asks me if I want to update fusion 360.  

It then proceed to tell me the update has been skipped.  

I would rather not have to go through the process of reinstalling F360 for linux all over again.
</div>

**Comment by halldanielg** [comment]
in update.sh (located in /home/<user>/.fusion360/bin/)there is an error in lines 151 to 163. The logic is inverted, pressing OK will cancel the update and pressing cancel will trigger an update. Those lines should look like this;

`# The user will be asked if he wants to update or not.
function UP_QUESTION {
  yad --title="$UP_TITLE" --text="$UP_QUESTION_LABEL" --text-align=center --button=gtk-cancel:0 --button=gtk-ok:1

  answer=$?

  if [ "$answer" -eq 1 ]; then
    UP_GET_UPDATE
    UP_FUSION360_INSTALL_UPDATE_PROGRESS
  elif [ "$answer" -eq 0 ]; then
    UP_SKIP_INFO
  fi
}`
