### ISSUE TITLE
"stream can not open!!" after fusion is running for some time, project can not be saved

### ISSUE THREAD

**Issue by str0g** [cryinkfly/Autodesk-Fusion-360-for-Linux#299]
Fusion 360 2.0.15050 x86_64
archlinux + kde
error msg:
Error: D:\Stage\workspace\protein\release\2021.10.R2023\protein\src\libs\protein4\archiveadaptor.cpp(210)stream can not open!!

Reproduction:
1. Open project
2. modify something
3. leave it for 30minuts (don't know if screen saver is important or not)
4. add additional modification
5. try to save.

**Comment by str0g** [comment]
I've also tried to export project to somehow save changes, loading from exported project end up with

Initializing document manifest xml stream failed!
The file <removed...>stl/tools/object v1.f3d could not be loaded.

**Comment by str0g** [comment]
I've reproduce issue and try to refresh projects while being in this non saving state. Fusion was not able to connect so I've send thru terminal ctrl+c  don 't know if thous logs are helpful.


0a8c:fixme:system:NtUserDisplayConfigGetDeviceInfo Unimplemented packet type 11.
^C0788:fixme:console:default_ctrl_handler Terminating process 760 on event 0
01b4:fixme:console:default_ctrl_handler Terminating process 884 on event 0
0584:fixme:console:default_ctrl_handler Terminating process 7d8 on event 0
0508:fixme:console:default_ctrl_handler Terminating process 394 on event 0
14:29:04 Shutting down FremontJS [SIGINT]...
0508:err:virtual:virtual_setup_exception nested exception on signal stack addr 0x7f0cc5a75965 stack 0x67fadd90
0788:err:virtual:virtual_setup_exception nested exception on signal stack addr 0x7f5dc76a7965 stack 0xe1cdd90
14:29:04 ...Server disconnected
14:29:04 ...Commands of SDKInstance a745de38-33b1-444a-82d0-292b1d732d22:https://developer.api.autodesk.com/assetgraph:WU0gYmGqYfddBzpOWFK
r7q_L2C completed
14:29:04 ...SDKInstance a745de38-33b1-444a-82d0-292b1d732d22:https://developer.api.autodesk.com/assetgraph:WU0gYmGqYfddBzpOWFKr7q_L2C disp
osed
14:29:04 Exiting process
0174:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000011E340
Connection closed!
Unable to connect to 127.0.0.1:10146
Unable to connect to 127.0.0.1:10146
Unable to connect to 127.0.0.1:10146
[2696:2700:0202/142907.718:ERROR:network_service_instance_impl.cc(262)] Network service crashed, restarting service.
0170:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0170:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
SetProcessDPIAwareness failed. (Access denied.)
0170:fixme:heap:RtlSetHeapInformation handle 0000000000000000, info_class 1, info 0000000000000000, size 0 stub!
[1748:368:0202/142907.935:ERROR:dxva_video_decode_accelerator_win.cc(1399)] DXVAVDA fatal error: could not LoadLibrary: msmpeg2vdec.dll: M
odule not found. (0x7E)
[1748:368:0202/142907.937:ERROR:dxva_video_decode_accelerator_win.cc(1407)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: Modul
e not found. (0x7E)

**Comment by Eric8tF** [comment]
Yes, I can confirm, same issues!

**Comment by str0g** [comment]
![image](https://user-images.githubusercontent.com/219793/220640291-ef8ad690-2fc9-4681-a1b0-e62d4eafa62b.png)

While your fusion is still working add dummy entries it probably solve that issue.

**Comment by str0g** [comment]
> Yes, I can confirm, same issues!

Insert sd card to mmc this will fix the issue. Problem is between kernel or wine.

**Comment by str0g** [comment]
> > > Yes, I can confirm, same issues!
> > 
> > 
> > Insert sd card to mmc this will fix the issue. Problem is between kernel or wine.
> 
> How would you do this?

My case is xmg laptop, laptops have mmc reader, I've did similar test with arm device and latest kernel results are the same.

Kernel  SCSI driver mapped /dev/sda with disk type, instead /dev/mmc with correct type for mmc.
Wine is trying to use this device which has no system partition. I've check this with udevadm info. When inserted sd card /dev/sda magically has system partition even if is still mmc device. No funny things happens if you go to wineprefix and ls -l on dosdevices  d->/dev/sda is being remapped as d->/dev/sda1 and newly introduced e drive is being link to /dev/sda.

**Comment by str0g** [comment]
kernel/SCSI drivers developers? Wine developers(not necessarily due to how mmc report itself in system but maybe there is flag some property to be checked)?  This bug has nothing to do with Fusion.

**Comment by kolomansell** [comment]
Hey. Sorry for posting on closed bug. I think I had similar issue which seems to not to appear if you go offline. Just wanna leave the info for anyone bumping into this as well.

**Comment by cryinkfly** [comment]
See this issue: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/330#issuecomment-1652254907
