### ISSUE TITLE
No internet connection possible. Cannot launch Fusion 360

### ISSUE THREAD

**Issue by Simonsaccount** [cryinkfly/Autodesk-Fusion-360-for-Linux#300]
**Describe the bug**
I successfully installed Fusion 360 with the Script on my machine. when starting I get the error that: "No Internet connection is possible. Check your network settings. You need to login with your Autodesk account to use Fusion360"

**To Reproduce**
Run the "box-run.sh" script.
Wait afor dark splashscreen
Afterwards the light screen containing the error message pops up.

**Expected behavior**
It is the first start after Installation so I guess I am supposed to be offered a login-screen

**Screenshots**
![image](https://user-images.githubusercontent.com/29257323/216670746-ebd16e89-3ab5-40d3-b27c-d6ce4c4fbfae.png)

**Desktop (please complete the following information):**
- Current Autodesk Fusion 360
- Intel
- Linux Mint 20.3
- Cinnamon 5.2.7
- wine staged. Tried both DXVK- or OpenGL-Mode. Same result

**Additional context**
Internet is connected and working fine outside wine.

**Comment by dhoerauf** [comment]
Im getting same error. I deleated all files and re installed and im getting the same error. i had working setup yesterday.

**Comment by dhoerauf** [comment]
sorry 
Arch linux
wine-staging
install from git clone today.

log file:
20230203T142035 I   .972 Version : 2.0.15293
20230203T142035 I   .972 OS Version : 5.2
20230203T142035 I   .972 UTC offset : -5
20230203T142035 I   .972 Loading configuration from:C:/Program Files/Autodesk/webdeploy/production/8610f314b0772d99da64266cf760a212d72992e8/Fusion 360.server.config
20230203T142035 D   1048 LaunchDarkly: [C:\Windows\Temp\releaser-project\src\user.c, 39] Setting user key to: 251e6056-5169-4fc0-87b1-41c15baefe53
20230203T142035 I   1048 PROXY: WindowsProxyOptionId set to Automatic
20230203T142035 W   1048 PROXY: failed to query IE proxy configuration - (12180) 
20230203T142035 I   1048 PROXY: proxy server set to DIRECT
20230203T142035 D   1028 LaunchDarkly: [C:\Windows\Temp\releaser-project\src\ldnet.c, 517] connecting to stream https://clientstream.launchdarkly.com/meval/eyJrZXkiOiIyNTFlNjA1Ni01MTY5LTRmYzAtODdiMS00MWMxNWJhZWZlNTMiLCJhbm9ueW1vdXMiOnRydWUsImVtYWlsIjoiIiwiY3VzdG9tIjp7ImVtYWlsRG9tYWluIjoiIiwiZnVzaW9uMzYwQnVpbGROdW1iZXIiOiIyLjAuMTUyOTMiLCJmdXNpb24zNjBPU1R5cGUiOiJ3aW5kb3dzIiwiZnVzaW9uMzYwT1NWZXJzaW9uIjoiNS4yIn19
20230203T142035 I   1028 LaunchDarkly client initialization process is finished successfully!		ThreadID: 1028, Function: Ns::LDCSDKWrapper::initLDCallback, Line: 472
20230203T142035 I   1048 LD CSDK for type Global was initialized with a total time of 0.000008 seconds		ThreadID: 1048, Function: Ns::CSDKLDFeatureFlagsManager::getFlagValue, Line: 148
20230203T142043 I   .972 Workflow start: CheckInternetConnectivity 1-63dd5e8a-2f13e70b9b894971a615180a
20230203T142043 E   1056 GET 77 https://ui-dls360.autodesk.com/fusion/version.txt dt=0.09 schannel: this version of Windows is too old to support certificate verification via CA bundle file.
20230203T142043 I   .972 GET 0 https://ui-dls360.autodesk.com/fusion/version.txt - workflow:CheckInternetConnectivity attempt:0 requestId:f360_CheckInternetConnectivity__1-63dd5e8a-2f13e70b9b894971a615180a dt=0.09
20230203T142043 E   1056 GET 77 https://ui-dls360.autodesk.com/fusion/version.txt dt=0.04 schannel: this version of Windows is too old to support certificate verification via CA bundle file.
20230203T142043 I   .972 GET 0 https://ui-dls360.autodesk.com/fusion/version.txt - workflow:CheckInternetConnectivity attempt:0 requestId:f360_CheckInternetConnectivity__1-63dd5e8a-2f13e70b9b894971a615180a dt=0.04
20230203T142043 E   1056 GET 77 https://ui-dls360.autodesk.com/fusion/version.txt dt=0.04 schannel: this version of Windows is too old to support certificate verification via CA bundle file.
20230203T142043 I   .972 GET 0 https://ui-dls360.autodesk.com/fusion/version.txt - workflow:CheckInternetConnectivity attempt:0 requestId:f360_CheckInternetConnectivity__1-63dd5e8a-2f13e70b9b894971a615180a dt=0.04
20230203T142043 I   .972 SLM: device id = 39e0eed2-0104-852f-9001-622acb2c663e
20230203T142043 I   .972 SLM: Initialized
20230203T142043 I   .972 Just loaded  Option Group BootstrapOptionsGroup  from file C:/users/darrell/AppData/Roaming/Autodesk/Neutron Platform/Options/NMachineSpecificOptions.xml successfully		ThreadID: 972, Function: Ns::OptionGroup::load, Line: 622
20230203T142043 I   .972 WorkflowTrackManager Initialized with:0 items
20230203T142043 I   .972 Just loaded  Option Group BootstrapOptionsGroup  from file C:/users/darrell/AppData/Roaming/Autodesk/Neutron Platform/Options/NMachineSpecificOptions.xml successfully		ThreadID: 972, Function: Ns::OptionGroup::load, Line: 622
20230203T142043 I   1128 Disk capacity: 4,545,676MB Disk free: 3,091,827MB Percentage free: 68 UIThread: no Time: 0.00056s
20230203T142043 I   .972 AnalyticItemCounts Initialized with:0 items
20230203T142043 I   .972 	searchAndLoad exec path: C:/Program Files/Autodesk/webdeploy/production/8610f314b0772d99da64266cf760a212d72992e8/Fusion360.exe
20230203T142043 I   .972 SYNHUB: Loading config files in directory C:/users/darrell/AppData/Roaming/Autodesk/Synergy

20230203T142043 I   .972 SYNHUB: Loading config file C:/users/darrell/AppData/Roaming/Autodesk/Synergy/NLauncher.syncfg

20230203T142046 I   .972 Load Feature Toggle Xml:C:/Program Files/Autodesk/webdeploy/production/8610f314b0772d99da64266cf760a212d72992e8/Fusion/Server/Fusion/Resources/FeatureToggle/FeatureToggle.xml
20230203T142046 W   .972 Not found updatestatus.json, path: C:\users\Public\Documents\Autodesk\Fusion360\updatestatus.json
20230203T142046 I   .972 Live update: disconnected or offline mode
20230203T142046 I   .972 Live update: StreamerHost allowUpdate False
20230203T142046 I   .972 Live update: FirstTimeHere
20230203T142047 I   .972 C:\Program Files\Autodesk\webdeploy\production\8610f314b0772d99da64266cf760a212d72992e8\Applications\Simulation\SimCommon10.dll		ThreadID: 972, Function: DllMain, Line: 22
20230203T142047 I   .972 Process attach		ThreadID: 972, Function: DllMain, Line: 23
20230203T142047 I   .972 Just loaded  Option Group BootstrapOptionsGroup  from file C:/users/darrell/AppData/Roaming/Autodesk/Neutron Platform/Options/NMachineSpecificOptions.xml successfully		ThreadID: 972, Function: Ns::OptionGroup::load, Line: 622
20230203T142047 I   .972 C:\Program Files\Autodesk\webdeploy\production\8610f314b0772d99da64266cf760a212d72992e8\Applications\CAM360\SimIdealizations10.dll		ThreadID: 972, Function: DllMain, Line: 16
20230203T142047 I   .972 Process attach		ThreadID: 972, Function: DllMain, Line: 17
20230203T142048 I   .972 Just loaded  Option Group CAMOptions  from file C:/users/darrell/AppData/Roaming/Autodesk/Neutron Platform/Options/NGlobalOptions.xml successfully		ThreadID: 972, Function: Ns::OptionGroup::load, Line: 622
20230203T142048 I   .972 Load Feature Toggle Xml:C:/Program Files/Autodesk/webdeploy/production/8610f314b0772d99da64266cf760a212d72992e8/FusionDoc/Server/FusionDoc/Resources/FeatureToggle/FeatureToggle.xml
20230203T142048 I   .972 Libeagle app mode: Hosted		ThreadID: 972, Function: Application::cEagleAppPrivate::Init, Line: 263
20230203T142050 I   .972 Not loaded Option Group ElectronOptionGroup  from file C:/users/darrell/AppData/Roaming/Autodesk/Neutron Platform/Options/electronoptiongroup_eagle.rc 		ThreadID: 972, Function: Ns::OptionGroup::load, Line: 625
20230203T142050 I   .972 Just loaded  Option Group NestingGeneralOptionGroup  from file C:/users/darrell/AppData/Roaming/Autodesk/Neutron Platform/Options/NGlobalOptions.xml successfully		ThreadID: 972, Function: Ns::OptionGroup::load, Line: 622
20230203T142050 I   .972 Just loaded  Option Group FeatRuleGeneralOptionGroup  from file C:/users/darrell/AppData/Roaming/Autodesk/Neutron Platform/Options/NGlobalOptions.xml successfully		ThreadID: 972, Function: Ns::OptionGroup::load, Line: 622
20230203T142050 I   .972 Just loaded  Option Group SheetMetalGeneralOptionGroup  from file C:/users/darrell/AppData/Roaming/Autodesk/Neutron Platform/Options/NGlobalOptions.xml successfully		ThreadID: 972, Function: Ns::OptionGroup::load, Line: 622
20230203T142050 I   .972 Toolbar loader: Stopping...
20230203T142050 I   .972 Toolbar loader: Stopped
20230203T142050 I   .972 ***startSession: BEGIN
20230203T142050 I   .972 getEntitlement
20230203T142050 I   .972 authenticate:begin
20230203T142050 I   .972 login start
20230203T142050 I   .972 login end 0
20230203T142050 E   .972 login failed 0.038478
20230203T142050 E   .972 MessageBox Error: Unable to connect to Internet

Please check your network connection. You need to sign into your Autodesk Account to use Fusion 360.
20230203T142143 I    668 Workflow start: CheckInternetConnectivity 1-63dd5ec7-d1eeee0798fd469783b78258

**Comment by freaky-m0** [comment]
Same problem for me. I installed a few hours ago on manjaro (KDE). Services seem to be running: https://health.autodesk.com/

**Comment by fraserws** [comment]
Same issue (Arch Linux)

**Comment by tynan** [comment]
Same issue

**Comment by cryinkfly** [comment]
## This is an error in the newest wine version!!!

**Comment by anilzeybek** [comment]
I have tried wine versions 7.12 and 8.1, but none of them worked.

**Comment by IsaacDias2020** [comment]
Same issue on Zorin 16.2 Pro, but Fusion 360 working ok on Arch Linux.

**Comment by crazylemmy** [comment]
> Same issue on Zorin 16.2 Pro, but Fusion 360 working ok on Arch Linux.

Hello, tell please what version of wine do you use on arch linux?

**Comment by IsaacDias2020** [comment]
Wine 8.1

Enviado do meu iPhone

Em 11 de fev. de 2023, à(s) 16:22, crazylemmy ***@***.***> escreveu:

﻿

Same issue on Zorin 16.2 Pro, but Fusion 360 working ok on Arch Linux.

Hello, tell please what version of wine do you use on arch linux?

**Comment by IsaacDias2020** [comment]
Working ok on Arch Linux (Wine 8.1).

![Captura de tela de 2023-02-11 19-21-21](https://user-images.githubusercontent.com/68559782/218283574-e33909ef-d511-4167-bb25-34a7de214c51.png)

**Comment by Eric8tF** [comment]
Tried different wine versions always the same issue, no internet connection... Any ideas why the old wine version causes trouble as well, that does not make sense, at least in my view.

**Comment by str0g** [comment]
fresh install end up with no internet connection.

community/vkd3d 1.6-1 [installed]
multilib/wine 8.1-1 [installed]
multilib/winetricks 20220411-1 [installed]

**Comment by dgarfias** [comment]
Same here. Arch Linux with Wine 8.1

**Comment by crazylemmy** [comment]
@IsaacDias2020  lucky guy with his archlinux
Isaac, maybe you are using an old version of fusion? I can't figure out why the program works for you... 🤔

**Comment by IsaacDias2020** [comment]
> @IsaacDias2020 lucky guy with his archlinux Isaac, maybe you are using an old version of fusion? I can't figure out why the program works for you... thinking

I'm using 2.0.15050 version.

**Comment by dhoerauf** [comment]
I get this right before it dies.
0370:fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.5" not implemented
0370:fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.5" not implemented
0370:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed

NETFramework,Version=v4.5
Wine Mono

both are installed.

**Comment by n3oney** [comment]
I've found a fix for it!
After looking in the error logs of Fusion, it outputs `20230220T221455 E    284 GET 77 https://ui-dls360.autodesk.com/fusion/version.txt dt=0.11 schannel: this version of Windows is too old to support certificate verification via CA bundle file.` a bunch of times.
After running `winecfg` in the Fusion360 prefix, you can change the Windows Version to Windows 10, like this:
![image](https://user-images.githubusercontent.com/30625554/220205691-9ec2b708-e46c-44e2-8bc1-355dd6adcfa7.png)

Afterwards, everything works fine.

**Comment by Eric8tF** [comment]
Thanks n3oney, that fixed the issue for me as well! Great Job!!!

Here the winecfg path and prefix to be copied:
```WINEPREFIX="$HOME/.fusion360/wineprefixes/default" winecfg```

**Comment by felixstorm** [comment]
Changing the Windows version using `winecfg` did not work for me - it had already been set to  "Windows 10" and even setting it to "Windows 11" did not help at all. Fusion 360 still seemed to detect the OS as Windows XP within its log files, could not connect to the internet and then quit with an error message stating that Windows 7 (!) was not supported anymore.

What did help for me though, was to do the follwing steps:
1. Kill all existing Wine processes, e.g `kill -9 $(ps aux |grep -i '\.exe' |awk '{print $2}'|tr '\n' ' ')`  
   This was important for me as otherwise the changes to `system.reg` would not become effective but instead got overwritten with the original values again!
2. Change the following values within `~/.fusion360/wineprefixes/default/system.reg`:
   ```
   [Software\\Microsoft\\Windows NT\\CurrentVersion] ...
   ...
   "CurrentBuild"="19045"
   "CurrentBuildNumber"="19045"
   "CurrentMajorVersionNumber"=dword:0000000a
   "CurrentMinorVersionNumber"=dword:00000000
   "CurrentType"="Multiprocessor Free"
   "CurrentVersion"="6.3"
   "ProductName"="Windows 10 Enterprise"
   ...
   ```
3. Start Fusion 360 by running `~/.fusion360/wineprefixes/default/box-run.sh`

I must admit that I find it quite strange that these steps were the ones that helped me because when using `regedit.exe` from within Wine, I did not get to see the values that I changed within `system.reg` but values that correspond to the Windows version that had been configured with `winecfg`, i.e. I was not able to find that values from `system.reg` with `regedit.exe` at all, but nevertheless Fusion 360 seemed to detect them and refused to work based on them (potentially through some Wine/Windows API call that directly accesses `system.reg` internally)...

**Comment by crazylemmy** [comment]
@n3oney , @Eric8tF 
Thank you guys so much, I also got the program working thanks to your advice!
(https://user-images.githubusercontent.com/35482653/220338585-9c9ef7a7-902b-452e-add0-c8b7ccb74493.png)

**Comment by cyberhuman** [comment]
I confirm that setting Windows version to 10 fixes it for me!

**Comment by str0g** [comment]
I've made fresh install and can not launch fusion also somehow working backup for fusion and wine configs also refused to work...

Please help.

```
modify ~/.fusion360/wineprefixes/default/system.reg // was window 10
modify ~/.wine2/system.reg // was window 7 
modify ~/wine/system.reg // was window 7 
```

to
```
"CurrentBuild"="19045"
"CurrentBuildNumber"="19045"
"ProductName"="Windows 10 Enterprise"
```
from logs can see
don't know if related 
```
0308:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
0308:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
0308:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
01b4:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
031c:fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.5" not implemented
031c:fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.5" not implemented
```

from fusion360 json dump

```
Build is correct os name does not :-)
❯ cat ./drive_c/users/user/AppData/Roaming/Autodesk/ADPSDK/JSON/Upload/dump_1.json
{
    "browser_platform": "Win32",
    "client_id": "192.168.1.2",
    "device_desc": "",
    "device_hw_display": "error",
    "device_hw_form": "Slate",
[...]
    "device_name": "XMG",
    "device_os_locale": "English - United States",
    "device_os_name": "Microsoft Windows 8.1 Pro",
    "device_os_type": "X64",
    "device_os_vendor": "Microsoft Inc",
    "device_os_version": "6.3.19045  Build19045",
    "device_os_video": "aticfx32.dll:30.0.14023.3004",
    "device_time": "2023-02-22T13:59:31.935922688+0100",
    "event_id": "9fce4221-4153-431f-9052-3fb522fc6911&2&2",
    "facets": [
        "product",
        "user",
        "device",
        "browser"
    ],
```

```
community/vkd3d 1.6-1 [installed]
community/wine-gecko 2.47.3-1 [installed]
community/wine-mono 7.4.0-1 [installed]
multilib/wine 8.1-1 [installed]
```

![image](https://user-images.githubusercontent.com/219793/220626371-a70c2b8a-d285-4499-8c52-10fb686e24a3.png)

**Comment by str0g** [comment]
> 

`bin/install.sh:445:  WINEPREFIX="$WP_DIRECTORY" sh "$SP_PATH/bin/winetricks" -q atmlib gdiplus corefonts cjkfonts dotnet452 msxml4 msxml6 vcrun2017 fontsmooth=rgb winhttp win10`

**Comment by Lanzo98** [comment]
> 

This solved for me

**Comment by n3oney** [comment]
> > 
> 
> `bin/install.sh:445: WINEPREFIX="$WP_DIRECTORY" sh "$SP_PATH/bin/winetricks" -q atmlib gdiplus corefonts cjkfonts dotnet452 msxml4 msxml6 vcrun2017 fontsmooth=rgb winhttp win10`

I believe this issue is actually [this](https://github.com/Winetricks/winetricks/pull/2025). Try downgrading cabextract to 1.9

**Comment by sathisse** [comment]
I was able to get past the no-internet error by editing the values in the system.reg file as described by felixstorm above. Note that I found and changed two sets of the values in the file.
