### ISSUE TITLE
ZwLoadDriver failed to create driver L (Help!) plz

### ISSUE THREAD

**Issue by TheRealAgentP** [cryinkfly/Autodesk-Fusion-360-for-Linux#302]
![Screenshot_20230206_103816_YouTube](https://user-images.githubusercontent.com/124620614/217056091-5601d066-15fe-4254-ae3e-2cc8a6ef46a4.jpg)
![Screenshot_20230206_122822](https://user-images.githubusercontent.com/124620614/217056185-2ab6c7ea-fff5-41bc-9b9f-c6f7bcdeb302.png)
![Screenshot_20230206_122944](https://user-images.githubusercontent.com/124620614/217056187-fc0a6a23-9a18-4ff8-8160-b7b34690acde.png)
![Screenshot_20230206_123007](https://user-images.githubusercontent.com/124620614/217056188-ea6d9c4a-efe4-4d67-b6be-1c9fc15b4a8b.png)
![Screenshot_20230206_123133](https://user-images.githubusercontent.com/124620614/217056190-516f59c4-4c79-4ff8-bce7-abc66489a290.png)
OK, i have been trying to get fusion 360 to install on my Kubuntu 22.04 machine. I followed the youtube video step by step and I didnt have an issue untill this command.

wine setup/streamer.exe -p deploy -g -f log.txt --quiet

afterwards I was greeted with exactly this and only this.

0074:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
0054:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\nsiproxy": c0000135
0098:err:rpc:RpcAssoc_BindConnection receive failed with error 1726

**Comment by dzervas** [comment]
Try to execute Fusion 360 Admin Install.exe with the same flags

**Comment by TroubledThinker** [comment]
Oh! Sorry, I didn't see this till today. I don't completely understand what you mean, could you elaborate a bit more please?

**Comment by dzervas** [comment]
yea sorry for the cryptic answer, I've been reversing Fusion for a while and I take too many info for granted. So:

`streamer.exe` is the installer of fusion that manages the updates/installs/etc. and is in `C:\Program Files\Autodesk\webdeploy\meta\<number>\`.
Passing `-p deploy -g -f log.txt --quiet` you tell it to do a global installation (as admin in `C:\Program Files` the `-g` flag), without GUI.

I couldn't get `streamer.exe` to play nice under wine so you can use [Fusion 360 Admin Install.exe](https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Admin%20Install.exe) which is the exact same executable just with everything built-in

**Comment by TroubledThinker** [comment]
Awesome! Thanks for your quick response! Because I still lack some understanding ( nothing on you, I'm not a very advanced user yet) would the command remain the same but instead of streamer.exe I replace it with Fusion360AdminInstall.exe?

**Comment by dzervas** [comment]
yeap, downloaded from the link in my previous comment  (nothing sketchy, it's the official Autodesk's installer for "batch installations" from the official autodesk website)

In other news, let me introduce [fusion360-streamer](https://github.com/dzervas/fusion360-streamer). It's still an infant but aims to re-implement the whole autodesk installer with support for older versions (and I've got many, many more features in mind but it remains to be seen).
@cryinkfly take a look!

**Comment by cryinkfly** [comment]
Are there any news?

**Comment by TroubledThinker** [comment]
I ended up switching to a different linux distro (manjaro) and the installation went smoothly. I am beginning to experience some graphical bugs but I'll put that into another report
