### ISSUE TITLE
Fusion 360 stops working after a while

### ISSUE THREAD

**Issue by zakutin** [cryinkfly/Autodesk-Fusion-360-for-Linux#310]
**Describe the bug**
The Fusion 360 works fine for some time, the parts can be modeled, everything works well. However, suddenly, for some reasons I cannot detect, the graphical area becomes gray with rendering glitches.
 
![Screenshot from 2023-03-20 14-01-11](https://user-images.githubusercontent.com/53969222/226349676-c5c97600-edeb-4ffc-b83d-f0926fbd966a.png)

When I try to open Preperences, firstly I get the message below, and then the Preferences are opened:

![image](https://user-images.githubusercontent.com/53969222/226351391-e5c3b986-9d81-432d-8208-4a611ea9f4e5.png)

When I try to save the file, I'm getting the dialog with corrupted visual elements:

![image](https://user-images.githubusercontent.com/53969222/226351634-b604deb7-37bb-4936-b7be-6514ac439248.png)

Also an error message appears in the bottom corner:

![image](https://user-images.githubusercontent.com/53969222/226351132-013914f7-407a-44f1-8fb9-3e281b4d2104.png)

And when I open the file, I get the message that the file is corrupt:

![Screenshot from 2023-03-20 14-04-55](https://user-images.githubusercontent.com/53969222/226352507-32078529-927e-4349-9b7a-7ab77e8d6386.png)

**To Reproduce**
1. Just use it as usual
2. Try to lock the screen
3. Leave the part opened for some time, 30 min or so
4. Try to save the part
5. Or open another one
6. Gray glitches may appear
7. Kill and restart Fusion
8. Everything works well again for some time

**Expected behavior**
No graphical issues. No interrupted workflow.

**Screenshots**
See above.

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360: 2.0.15509 x86_64
- Graphics card model + Graphics card driver (Version number): 
    - Vendor: Intel (0x8086)
    - Device: Mesa Intel(R) UHD Graphics 620 (KBL GT2) (0x5917)
    - Version: 22.3.7

- Operating system (OpenSUSE Leap 15.3, Fedora 34, ...): Fedora 37 Workstation
- Desktop environment (XFCE 4.16, Gnome 40, ...): GNOME 43.3
- DXVK- or OpenGL-Mode: both
- Wine 8.2, 8.4

**Additional context**
Probably the issue is somehow related to #299.

**Comment by wu5** [comment]
I have no problems with graphics, but after 30 minutes of work I get the same error when trying to save the project. STL model is not saved either. 

This is a very annoying bug! Imagine, you've been working on a model for a long time and then it turns out that you can't save your progress.

```
Error: D:\Stage\workspace\protein\release\2021.10.R2023\protein\src\libs\protein4\archiveadaptor.cpp(210)stream can not open!!
Error: ParaMeshBlobSerializer - createZipPartFromFile failed!
```

```
Error: Autodesk Translation Services failed to translate the current document to stl file!
Error: Translator failed to export data
```

OS: Manjaro
GPU: NVIDIA GeForce GTX 1650
Fusion 360: 2.0.15509
Wine: wine-staging 8.4
DXVK or OpenGL: both

**Comment by wu5** [comment]
> @wu5, did you try the workaround with an SD card, mentioned in #299?

It seems to be working with microSD card through a USB card reader. I kept Fusion 360 open for about an hour and the save did not show any errors.

**Comment by paukstelis** [comment]
I run into this issue even on a machine that does not have an SD card reader. It does have additionally mounted drives. wine-8.12.

**Comment by Howy-1** [comment]
I have testing in the Network-Settings of Fusion360 directly "no proxy" and "Server verification " i have changed to "No warning when accessing via an intermediate server".
I hope, this is the correct english Translation (in German: "Serververifizierung: Beim Zugriff über einen Zwischenserver keine Warnung ausgeben").
An that is the solution for me, on two different computers, even after a restart. I was working over 1 hour, with no crash and i can always save and export my work.

I have Zorin OS 16.3 (Ubuntu-based)

**Comment by madurani** [comment]
I can confirm that solution related with network setting work for me. I had mentioned issue immediately 1-2 minute after start of fusion, now i can save document without problem longer time after start.

**Comment by thenicnet** [comment]
I can confirm that I am still experiencing this issue. 

Fusion 2.0.19215 x86_64

**Comment by MostHated** [comment]
I am experiencing this issue, both graphical and inability to save after X minutes, every time I try and use it. It gives an error of:

```
Error: Got an unknown exception during persistence Protein Assets to a local file on disk!
Error: ParaMeshBlobSerializer - createZipPartFromFile failed!
Error: DesignConfigurationTableBlobSerializer::doSave - createZipPartFromFile failed!
```

I just found this thread, so going to test out some of the workarounds and report back if it fixes for me.

**Comment by cryinkfly** [comment]
Please check here: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/362#issuecomment-1889835832
