### ISSUE TITLE
Fusion 360 for Linux does not launch

### ISSUE THREAD

**Issue by dumbnerd08** [cryinkfly/Autodesk-Fusion-360-for-Linux#320]
**Describe the bug**
Fusion 360 does not launch either from my applications menu nor from the terminal.

**To Reproduce**
1. Go to 'Applications' (or whatever your distro's applications menu is)
2. Click on 'Fusion 360'
Does not load

OR

1. Go to ~/.fusion360/bin/
2. ./launcher.sh
3. Wait for script to exit, see error

**Expected behavior**

Fusion 360 will open and function.

**Screenshots**

**Desktop (please complete the following information):**
- Newest version as of 4/14/23
- GTX 1650 Max Q (Alongside Intel integrated graphics) + Nouveau driver 
- Fedora Linux 37 (6.2.9-200.fc37.x86_64)
- Gnome 43
- No idea

**Additional context**

Here is the output in console from when I run the script to when it exits:

```
--2023-04-14 21:26:42--  https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/build-version.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
Saving to: ‘/tmp/fusion360/build-version.txt’

build-version.txt   100%[===================>]      20  --.-KB/s    in 0s      

Last-modified header missing -- time-stamps turned off.
2023-04-14 21:26:42 (385 KB/s) - ‘/tmp/fusion360/build-version.txt’ saved [20/20]

Online Build-Version: 2.0.15027
Online Insider-Build-Version: 2.0.15277
The version.txt file not exist!
EN
find: ‘’: No such file or directory
wine: invalid directory  in WINEPREFIX: not an absolute path
```

**Comment by dumbnerd08** [comment]
Closed: Restarting my computer after installing dependencies fixed the issue. (Fedora Linux 37/38)

**Comment by Box-Bop** [comment]
In case anyone else comes across the same issue, you have to edit the `launcher.sh` file in your editor of choice and you'll find that you have to replace the bottom two `$WP_BOX` variables with wherever your Fusion360 wineprefix exists (should be the folder that you picked during installation).
