### ISSUE TITLE
Fusion gets stuck in Lauching process: QueryDisplayConfig

### ISSUE THREAD

**Issue by blam121** [cryinkfly/Autodesk-Fusion-360-for-Linux#321]
Hi all, 

Had a bit of trouble getting the install to go properly, but it the end it seems like it has gone well, but still having some issues when I want to open the program. When I use the env WINEPREFIX command, all starts fine, Fusion shows up in the System monitor as if it should be opening. But the Terminal just gets stuck with this: 
05b0:fixme:system:QueryDisplayConfig (00000002 000000000011DF44 0000000023832D90 000000000011DF48 0000000023832DE0 0000000000000000): semi-stub

Any ideas why it is getting suck here and how to fix it?  Thanks for the help!

Using Linux Mint 20.2

**Comment by cryinkfly** [comment]
So under the latest Linux Mint version Fusion 360 was running. See here: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/releases/tag/v7.6.9
