### ISSUE TITLE
Working with Proton GE 55

### ISSUE THREAD

**Issue by jonfive** [cryinkfly/Autodesk-Fusion-360-for-Linux#328]
Not sure where to say this, but i figure it's worth knowing.

I installed the last version from archive.org so i could log in and used Heroic to add an exe. 
Ran the installer as-is with gloriouseggroll's protonGE-55. (Installation is very slow.)

After, it launched and it ran great with just a few black flickers, probably from Nvidia being weird. 

There's still an issue where it doesn't _constantly_ render frames unless you're moving around.

**Comment by infinitevalence** [comment]
Any chance you can detail your steps so others can try to replicate?

**Comment by sigboe** [comment]
I tried yesterday, this also works to just do it in steam. Just add the installer as a non-steam game, make sure compatibility is set to Proton, I only tested it with `GE_Proton8_3-1`. After the install change the target to the `Fusion360.exe`  You will find it in `/home/${USER}/.steam/steam/steamapps/compatdata/${SOME_RANDOM_NUMBER}/pfx/drive_c/Program Files/Autodesk/webdeploy/production/${SOME_OTHER_RANDOM_NUMBER}/Fusion360.exe` Make sure the target file path is in quotes in the steam GUI.

Of course, the GUI of Fusion 360 doesn't properly work for me, but its not worse in Steam or Proton GE than other methods i've tried. Like floating menus I have a huge issue with. But again, if you don't have that issue, then maybe this method will be more suitable for you.

**Comment by Shmob1** [comment]
> I tried yesterday, this also works to just do it in steam. Just add the installer as a non-steam game, make sure compatibility is set to Proton, I only tested it with `GE_Proton8_3-1`. After the install change the target to the `Fusion360.exe` You will find it in `/home/${USER}/.steam/steam/steamapps/compatdata/${SOME_RANDOM_NUMBER}/pfx/drive_c/Program Files/Autodesk/webdeploy/production/${SOME_OTHER_RANDOM_NUMBER}/Fusion360.exe` Make sure the target file path is in quotes in the steam GUI.
> 
> Of course, the GUI of Fusion 360 doesn't properly work for me, but its not worse in Steam or Proton GE than other methods i've tried. Like floating menus I have a huge issue with. But again, if you don't have that issue, then maybe this method will be more suitable for you.

Can confirm, works out of the box with Steam, running proton-8.0-2

**Comment by jsanpe** [comment]
It installs for me using the Heroic Launcher trick above, but at least with proton-ge-8.3 is not really usable, lots of graphical glitches to the point it can't be used really. Any luck with other versions beyond getting it to install?

**Comment by kjkent** [comment]
Tried using @sigboe's method, but unfortunately stuck on at the login screen as Fusion 360 asks me to sign in but doesn't open any browser to do so.

**Comment by alecGraves** [comment]
I found this guide for installing with the latest installer without using the browser install thing. Apparently, you can give the argument `--quiet` to the installer and it will install (in the background, no GUI rendered). I am not sure if you can log in after that since I ran into another problem running the program after it installed.

https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Blank-Autodesk-Application-Streaming-when-installing-Autodesk-Fusion-360.html
