### ISSUE TITLE
Feature Request: Integrate Space Mouse

### ISSUE THREAD

**Issue by TheGreenMamba** [cryinkfly/Autodesk-Fusion-360-for-Linux#333]
I'm using fusion with this project since a while now and I also have a 3dconnexion mouse running in wine thanks to https://github.com/DD1984/SpaceMouse_Fusion360_Wine.

I think this would be a nice feature to integrate!

Thanks for the awesome work! I never have to use Windows again :heart:

**Comment by cryinkfly** [comment]
This is implemented in the new installer!
