### ISSUE TITLE
Bad EXE format for %1

### ISSUE THREAD

**Issue by erikjber** [cryinkfly/Autodesk-Fusion-360-for-Linux#337]
**Describe the bug**
Installation fails. 

During installation on two occasions a dialog with the text "Bad EXE format for %1" pops up. The install apparently continues when the dialogs are closed. 

After the "Connecting to server" dialog is closed the terminal shows the following message and the install terminates:

> The installation is completed!
wine client error:ec: 003c:fixme:ver:GetCurrentPackageId (0068FE9C 00000000): stub
TRUE
--2023-07-25 13:15:11--  https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/build-version.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
Saving to: ‘/tmp/fusion360/build-version.txt’

> build-version.txt                                           100%[========================================================================================================================================>]      20  --.-KB/s    in 0s      

> Last-modified header missing -- time-stamps turned off.
2023-07-25 13:15:12 (1,10 MB/s) - ‘/tmp/fusion360/build-version.txt’ saved [20/20]

> Online Build-Version: 2.0.15027
Online Insider-Build-Version: 2.0.15277
The version.txt file not exist!
mkdir: cannot create directory ‘/tmp/fusion360/logs’: File exists
EN
wine: could not open working directory L"unix\\home\\erikjber\\.fusion360\\bin\\", starting in the Windows directory.
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

**To Reproduce**
1. Run the install script.
2. Wait.

**Expected behavior**
The install completes without error.

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360: Latest as of today (2023-07-25)
- Graphics card model: Nvida GeForce RTX 3060 
- Graphics card driver: 535.86.05-0ubuntu0~gpu22.04.1
- Operating system: Xubuntu Jammy 22.04.2 LTS 
- Desktop environment: XFCE 
- DXVK- or OpenGL-Mode: I tried both, same result.

**Additional information**
I have retried this several times, always with the same result.

**Comment by erikjber** [comment]
The dialogs appear immediately after the download progress bar dialogs. 

The dialogs appear regardless of whether I use DXVK or OpenGL, and regardless of which Wine version I choose. 

There is nothing in the console output to indicate which file is causing the problem, this is what is printed immediately before the first dialog appears:

> Executing cp /home/erikjber/installs/fusion360/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.3K14nN8R/_reg_698305e4_206445.reg
Executing w_do_call unifont
unifont already installed, skipping
Using winetricks 20230212-next - sha256sum: be4196ba3358be7c68cb58e7a7cbe9b37418e12e92beb88876e119998f438532 with wine-8.13 (Staging) and WINEARCH=win32
Executing w_do_call win10
Executing load_win10 
Executing wine winecfg -v win10
wine: could not open working directory L"unix\\home\\erikjber\\installs\\fusion360\\", starting in the Windows directory.
wine: could not open working directory L"unix\\home\\erikjber\\installs\\fusion360\\", starting in the Windows directory.
0208:fixme:ver:GetCurrentPackageId (0074FE9C 00000000): stub
0200:fixme:ver:GetCurrentPackageId (0069FE9C 00000000): stub
> ------------------------------------------------------
> warning: Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/erikjber/installs/fusion360 terminate
> ------------------------------------------------------
> 002c:fixme:winediag:LdrInitializeThunk wine-staging 8.13 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0094:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0094:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0094:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0094:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0094:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0094:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0034:fixme:ver:GetCurrentPackageId (0068FE9C 00000000): stub
002c:fixme:ver:GetCurrentPackageId (0066FE9C 00000000): stub
wine: could not open working directory L"unix\\home\\erikjber\\installs\\fusion360\\", starting in the Windows directory.
wine: could not open working directory L"unix\\home\\erikjber\\installs\\fusion360\\", starting in the Windows directory.
0130:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0130:fixme:seh:WerSetFlags (2) stub
0130:fixme:heap:RtlSetHeapInformation HEAP_INFORMATION_CLASS 1 not implemented!
0140:fixme:process:SetProcessShutdownParameters (00000380, 00000000): partial stub.
0140:fixme:ntdll:WinSqmIsOptedIn (): stub
0140:fixme:service:QueryServiceConfig2W Level 6 not implemented
0140:fixme:service:QueryServiceConfig2W Level 6 not implemented
0140:fixme:service:QueryServiceConfig2W Level 6 not implemented
0140:fixme:service:QueryServiceConfig2W Level 6 not implemented
0140:fixme:service:QueryServiceConfig2W Level 6 not implemented

**Comment by stuckj** [comment]
I saw this as well. I was mistakenly using WINARCH=win32. If you're doing the same, leave WINARCH off. This needs to be 64-bit. Also, if you created the wine prefix with WINARCH=win32 you need to delete it and start over with WINARCH off. You can't convert it to 64-bit after creation.

**Comment by erikjber-kognic** [comment]
> I saw this as well. I was mistakenly using WINARCH=win32. If you're doing the same, leave WINARCH off. This needs to be 64-bit. Also, if you created the wine prefix with WINARCH=win32 you need to delete it and start over with WINARCH off. You can't convert it to 64-bit after creation.

That solved it. Thanks so much!

**Comment by erikjber** [comment]
> I saw this as well. I was mistakenly using WINARCH=win32. If you're doing the same, leave WINARCH off. This needs to be 64-bit. Also, if you created the wine prefix with WINARCH=win32 you need to delete it and start over with WINARCH off. You can't convert it to 64-bit after creation.

That solved it. Thanks so much!
