### ISSUE TITLE
Install script can break an arch install *Solved*

### ISSUE THREAD

**Issue by AdamHitchen** [cryinkfly/Autodesk-Fusion-360-for-Linux#339]
**Describe the bug**
The install script runs a command along the lines of `pacman -Sy --needed {deps}`, which is [unadvised](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported). This command causes a partial upgrade - meaning the packages listed in the command will be installed  to the latest version available but all other packages on the system will remain out of date. This is a pretty serious issue, because it means any package depending on an older version of an updated library will no longer run. As an example, if openssl gets updated in the repositories and ppp is installed by this command, openssl will be upgraded and pacman along with other programs will no longer function

**To Reproduce**
Hard to reproduce, it requires a specific system state where local packages are out of date and specific packages are updated remotely.  Then running the install script could trigger it.

**Expected behavior**
Packages should be installed with -Su or -Syu

**Desktop (please complete the following information):**
Any arch-based distro

**Comment by cryinkfly** [comment]
Thank you for this tip! :+1:
