### ISSUE TITLE
[Question] Incorrect GPU?

### ISSUE THREAD

**Issue by zakutin** [cryinkfly/Autodesk-Fusion-360-for-Linux#340]
Someone may be familiar with the following behaviour — I have an incorrect GPU device shown in Fusion Graphics Diagnostics for DirectX 9, but it shows a correct GPU for OpenGL and DirectX 11.

Is it normal? Should it be so? Where does it come from?

**Expected behavior**
Proper GPU for Directx 9.

**Screenshots**
DirectX 9:
![Screenshot from 2023-08-08 18-12-48](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/53969222/9fb616de-52de-4e65-9e84-b4bab0276481)

DirectX11:
![Screenshot from 2023-08-08 18-23-55](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/53969222/a8c559c7-b4b8-4a51-ad8d-13b37f496749)

OpenGL:
![image](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/53969222/6aaf7273-257f-4a18-8e81-6e7350ca840f)

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360: 2.0.16761 x86_64
- Graphics card model + Graphics card driver (Version number): Device: Mesa Intel(R) UHD Graphics 620 (KBL GT2) Version: 23.1.5, Kernel driver in use: i915
- Operating system (OpenSUSE Leap 15.3, Fedora 34, ...): Fedora 38
- Desktop environment (XFCE 4.16, Gnome 40, ...): Gnome 44.3
- DXVK- or OpenGL-Mode: both
- Wine 8.13

**Comment by cryinkfly** [comment]
This is a special issue. Some linux distros can give the correct gpu information to wine and some not.
