### ISSUE TITLE
Exported .f3d Files Unable to be Opened

### ISSUE THREAD

**Issue by NewoIsTaken** [cryinkfly/Autodesk-Fusion-360-for-Linux#344]
When trying to import a `.f3d` file, I get an error that says `Initializing document manefest xml stream failed!`.

**To Reproduce**
1. Export a Fusion 360 file as an `.f3d`
2. Attempt to open it

**Expected behavior**
The file should open.

**Screenshots**
![image](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/18237567/3ac6d1fd-e3fe-4eaf-94ba-416939fb4675)

**Desktop (please complete the following information):**
- Version: Unsure (Help > About not working)
- Graphics card model + Graphics card driver: 2070 Super/
- Operating system: Manjaro
- Desktop environment: KDE Plasma 5.27.7
- DXVK-9

**Additional context**

**Comment by cryinkfly** [comment]
Any news here?

**Comment by NewoIsTaken** [comment]
That's good to hear! I haven't checked in on this bug recently but glad to hear that it seems to be resolved. I'll give it a test when I get a sec.

**Comment by cryinkfly** [comment]
You can, but on some system you must activate the virtual desktop in wine!

**Comment by NewoIsTaken** [comment]
> You can, but on some system you must activate the virtual desktop in wine!

@cryinkfly, could you clarify what you mean by the virtual desktop in wine? I haven't heard of this feature/option before.

**Comment by cryinkfly** [comment]
Run this command in the terminal if you have installed Fusion 360 with my newest installer script:

    WINEPREFIX="$HOME/.autodesk_fusion/wineprefixes/default" winecfg

... and then switch into  the Graphics tab and there you can configure the thing.
