### ISSUE TITLE
Getting Edge-Update-Installer Error

### ISSUE THREAD

**Issue by baldisos** [cryinkfly/Autodesk-Fusion-360-for-Linux#350]
**Describe the bug**
While Installing i always get the Edge-Update-Installer Error shown in the Screenshot.
The Error message says that an Error occurred during install.
Is this to be expected?

**To Reproduce**
Run the install script.

**Expected behavior**
No error to be thrown.

**Screenshots**
![grafik](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/76702976/3c254d93-8e72-4699-a371-9f03a8e1201b)

**Desktop (please complete the following information):**
- openSUSE Tumbleweed 20230926 x86_64
- Gnome 45
- Kernel 6.5.4-1-default

**Comment by baldisos** [comment]
Oh i haven't noticed the install is running through even with that error, i always cancelled it because i thought this was needed to login after install. Like you said i just closed it, and ignored it and the install went though. Thank you.

**Comment by ffpp2003** [comment]
I tried to close the pop up window using the X at the top left, and it seems that nothing was installed. When running the .desktop file on terminal, i get this:
```
--2024-01-27 13:21:24--  https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/build-version.txt
Resolviendo raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Conectando con raw.githubusercontent.com (raw.githubusercontent.com)[185.199.111.133]:443... fpp@fpp-g42:~$ conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 20 [text/plain]
Grabando a: «/tmp/fusion360/build-version.txt»

build-version.txt                                100%[=========================================================================================================>]      20  --.-KB/s    en 0s

Falta la cabecera de fecha de la última modificación -- marcas de tiempo desactivadas.
2024-01-27 13:21:24 (503 KB/s) - «/tmp/fusion360/build-version.txt» guardado [20/20]

Online Build-Version: 2.0.17228
Online Insider-Build-Version: 2.0.17228
The version.txt file not exist!
ES

(yad:3863): Gdk-CRITICAL **: 13:21:25.049: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed

(yad:3873): Gdk-CRITICAL **: 13:21:27.621: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed
The applicacion could not be executed, or there is no application associated with the specified file.
ShellExecuteEx failed: File not found

```

After inspecting the wineprefixes c drive, i wasnt able to find anything that looked like Fusion360 installed, only some "autodesk" folders with subfolders that are empty or have no executable files
