### ISSUE TITLE
Installer: Use /etc/os-release to determine distribution *solved*

### ISSUE THREAD

**Issue by Nold360** [cryinkfly/Autodesk-Fusion-360-for-Linux#353]
**Is your feature request related to a problem? Please describe.**
I was wondering why you are asking the user, which distri he is using. AFAIK every major distri should have `/etc/os-release` which should be `source`able

**Describe the solution you'd like**
Drop the userinput and just use /etc/os-release (if available?)

**Describe alternatives you've considered**
idk.. there are multiple files, but again afaik it's the standard now.

**Additional context**
-

**Comment by Kreyren** [comment]
No written standard -> It's not standard

`/etc/os-release` is not mentioned in FHS-3.0 so it's not required for distributions to provide these to be certified. It's an agreed practice by mostly mainstream distros -> relying on it will break detection of the OS on some linux systems.
