### ISSUE TITLE
Ubuntu 22.04.3: Stuck "Connecting to the server..." while launching *solved*

### ISSUE THREAD

**Issue by Ryanf55** [cryinkfly/Autodesk-Fusion-360-for-Linux#363]
**Describe the bug**

After a supposedly successful installation using Ubuntu 22.04, I found the launch command from another issue. 

When running the launcher, there is a popup for connecting to the server, but it never goes away. Fusion360 never starts. If I click the green check, the startup script stops with no errors, but the application never starts.

**To Reproduce**
1. `sudo apt install yad`
1. `mkdir -p "$HOME/.fusion360/bin" && cd "$HOME/.fusion360/bin" && wget -N https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/install.sh && chmod +x install.sh && ./install.sh`
1.` /home/ryan/.fusion360/wineprefixes/default/box-run.sh`
1. See hung launcher with no logs
![image](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/25047695/c330ce53-56bb-42a6-b89f-c28d75857db1)

**Expected behavior**

Fusion 360 would start and open the application.

**Screenshots**

Launch Logs: 
```
$ /home/ryan/.fusion360/wineprefixes/default/box-run.sh
--2023-11-19 17:01:04--  https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/build-version.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
Saving to: ‘/tmp/fusion360/build-version.txt’

build-version.txt                                                    100%[=====================================================================================================================================================================>]      20  --.-KB/s    in 0s      

Last-modified header missing -- time-stamps turned off.
2023-11-19 17:01:04 (3.18 MB/s) - ‘/tmp/fusion360/build-version.txt’ saved [20/20]

Online Build-Version: 2.0.17228
Online Insider-Build-Version: 2.0.17228
The version.txt file not exist!
EN
```

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360: Unknown, it's not yet running. Ran the setup script on Nov 19, 2023
- Graphics card model + Graphics card driver (Version number): NVIDIA RTX3060ti
- Operating system: Ubuntu 22.04.3
- Desktop environment: Wayland
- DXVK- or OpenGL-Mode

**Comment by heschlie** [comment]
I'm seeing this exact issue as well.

**Desktop (please complete the following information):**

-   Version number of Autodesk Fusion 360: Unknown, it's not yet running. Ran the setup script on Nov 19, 2023
-   Graphics card model + Graphics card driver (Version number): AMD 6900XT
-   Operating system: Arch
-   Desktop environment: KDE (Wayland)
-   DXVK- or OpenGL-Mode: whatever the default script installs

**Comment by heschlie** [comment]
So I was suspicious of how quickly it installed, looking more closely when I tried again it was trying to install winetricks, but the flags given to it were causing it to save to a bad location. this command:

```
wget -NPc "$SP_PATH/bin" https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
```

the `c` is being captured by the `-NP` as the path and thus saving it to `c/winetricks` instead of to `$HOME/.fusion360/bin/` I'm not sure if that was a typo or if the `c` is intentional, but removing it allowed me to get further along in the install though I have not been successful in getting it installed yet.

git blame for the line:
https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/blame/747fb64a012a9f4e1f01b5a252d2cce7a976c7b1/files/builds/stable-branch/bin/install.sh#L285

**Comment by Smegheid** [comment]
For what it's worth, `wget -NPc ...` appears a total of four times in the install script. Going on the version in the git blame link above,beyond line 285 this is also present in lines 311, 345 and 398. These are associated with 8afebaa.

Dropping the `c` entirely (is the `continue` flag for resuming downloads really that important?) gets to the point where a fusion 360 splash screen is displayed, at which point `streamer.exe` and `wineserver` consume significant CPU time and then quiet down.

There is also a dialogue box titled `YAD` showing "Autodesk Fusion 360 will be installed on your system ..." with a progress bar that's about 20% full.

A burst of messages then happen in the terminal where the install script was run, the dialogue progress bar moves to about 75% and a second splash screen (i.e. there are two displayed simultaneously). More CPU usage is then seen on the part of the two processes mentioned, and after a shorter wait a dialogue for plugin selection is shown.

Selected plugins install one after the other, then a dialogue is shown indicating that installation completed, with a checkbox to launch fusion 360. Selecting this and then dismissing the dialogue then results in the "Connecting to the server ..." dialogue being displayed. Again, there is significant CPU usage `streamer.exe` and `wineserver`. However, this dialogue box has an "OK" button, and pressing that results in another splash screen, at which point the whole thing stops.

There is a message at the tail end:
``Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:9766

However, while opening this in a browser does appear to show an Autodesk sign in prompt by way of a clickable "Inspectable pages" intermediate page, this is displayed in Chrome's debugger and does not appear to be something that can be interacted with - there doesn't appear to be a way to enter an email address and hit "next".

The trick at this point appears to be to kill off the `streamer.exe` process (or just `xkill` the splash screen) and start the application again with `.fusion360/wineprefixes/default/box-run.sh`. At this point, the splash screen was followed by a login dialogue, which I was able to use to sign in and then get to the main UI.

I'm now personally in lapsed edu subscription territory and the "expired: subscribe now" button does not open up a browser to sort that out. I can probably live with getting that going from Windows.

**Comment by Aus-gez** [comment]
Thanks @heschlie , @Smegheid , @Ryanf55. I ran in to this same problem, and found your posts. You all gave me the info I needed to post fix to the code #364.

**Comment by jakobvinkas** [comment]
I ran the installation today (for the first time) and seem to get stuck at the same issue. Is it still present? Thanks!

**Comment by jakobvinkas** [comment]
Running: 
`.fusion360/wineprefixes/default/box-run.sh`
I get the same result output as in the original post but if I instead run:
`.fusion360/bin/launcher.sh`
I get the following error:
`
Online Build-Version: 2.0.17228
Online Insider-Build-Version: 2.0.17228
The version.txt file not exist!
EN
find: ‘’: No such file or directory
wine: invalid directory  in WINEPREFIX: not an absolute path
`
In case it helps.

**Comment by Aus-gez** [comment]
@jakobvinkas I'll check this a little later. In the meantime, can you please check the following path in your home directory? `~/.fusion360/bin`

Is the winetricks file in that folder or in a subfolder labelled `c`?

Did you use the default location for the wineprefix?

**Comment by jakobvinkas** [comment]
I used the default location from what I could tell and its located directly in bin.

**Comment by Aus-gez** [comment]
After some googling and troubleshooting, I found that the wine invalid directory errors are a red herring. A side-effect of using the winetricks `sandbox` verb. 

I wiped everything and tried the full install (including fusion download) and this time I successfully got all the way through to the fusion360 login prompt.

I set OpenGL as my graphics mode and the default location of the wineprefix.

I can't tell if the seemingly intermittent nature of this issue is due to a timing issue or something upstream? Anyone with ideas?

@jakobvinkas : let me know the outcome if you try another full install. Good luck!

**Comment by jakobvinkas** [comment]
No that still does not work for me, some notes from my installation.

In the "preferences" alternative you can select OpenGL but when pressing it again it goes back to the top alternative. Are you sure that the selected alternative are actually used?

I encountered a warning window in the middle of the installation: 
![Screenshot from 2023-12-06 08-04-41](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/43340911/12ef07f6-2c4d-4f7a-b2ba-48fc800414bc)
But I still got a "successfully installed" window at the end. Here is the system information from the error text:
```
System information:
    Wine build: wine-6.0 (Ubuntu 6.0+repack-1ubuntu1)
    Platform: x86_64
    Version: Windows 10
    Host system: Linux
    Host version: 6.2.0-37-generic
```
