### ISSUE TITLE
Question : when exporting .3mf, where can I get the file back ? *Solved*

### ISSUE THREAD

**Issue by rozennrd** [cryinkfly/Autodesk-Fusion-360-for-Linux#368]
I need to export a file from autodesk and get it to cura. Where can I find my .3mf file that I registered to Downloads ? How to export file for future use and sharing ?

**Comment by poon-holder** [comment]
check out closed issue #312

This is normal behaviour.

your files will be here;

/home/user/.fusion360/wineprefixes/default/drive_c/users/user/Downloads/

user is your username, users is a file within the wineprefixes you will see it when navigating through.

Also lookup the 'find' command for lunix machines. By exporting a body from fusion and then searching in terminal for it you will find its extension.
type 'man find' in terminal for its manual. or a quick search will through something up on itsfoss or another likewise website.

Hope this helps,
Take care.

Remember to support Mr Zabka if his linux work around helps you out!

**Comment by nadnerb33** [comment]
I found my files in `~/.fusion360/bin/drive_c/users/<myuser>/Downloads`
