### ISSUE TITLE
Can't Install on Distrobox Arch

### ISSUE THREAD

**Issue by DragonflyRobotics** [cryinkfly/Autodesk-Fusion-360-for-Linux#369]
**Describe the bug**
I installed YAD and the rest of the dependencies listed on the Github documentation for Arch but I get the following error.

![image](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/85193239/8658c334-f4f9-494a-9009-c547be2dbfe8)

I am using a Distrobox Arch Machine with GPU passthrough. I am not sure what logs or information you need to debug this so please let me know what I can provide to help resolve this.

**Comment by bytedream** [comment]
It should be fine if you ignore and just `Close` it, see #350

**Comment by DragonflyRobotics** [comment]
Indeed, I just proceeded and waited for quite some time and it seemed to work, albeit a little slow, just fine. Thank you !

**Comment by DragonflyRobotics** [comment]
Indeed, I just proceeded and waited for quite some time, and it seemed to work, albeit a little slow, just fine. Thank you!
