### ISSUE TITLE
Webview2 required *Solved*

### ISSUE THREAD

**Issue by deece** [cryinkfly/Autodesk-Fusion-360-for-Linux#373]
**Describe the bug**
On installing, Fusion 360 pops a dialog saying that it needs WebView2 to continue.

**To Reproduce**
1. Follow the install process, default options, no extensions selected
2. Launch Fusion 360
3. Click "Sign In"
![Screenshot from 2024-01-06 09-47-38](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/1862055/2d837ca1-6548-4155-86d6-9129dd47a0e5)

**Expected behavior**
The Fusion 360 login is displayed

**Screenshots**

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360: Unknown
- NVidia RTX3090, 535.129.03-0ubuntu0.23.10.1
- Ubuntu 23.10
- Gnome 45
- DXVK

**Additional context**
Download the installer from:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH#download

**Comment by FricoRico** [comment]
I was able to install WebView2 but it does not allow me to log in anyway. When logging in through Firefox, it does not redirect me back into the application. Haven't found a workaround yet.

**Comment by lazytesting** [comment]
I have the same problem and tried the following things so far (which did not help):
- configure the browser in wine. The command ```wine www.google.com``` works. But the Fusion360 still shows the same error.
- tried installing the webview2 manually => same result

**Comment by dukenukemx** [comment]
Same problem here.

**Comment by 0BL1V10N5-PH03N1X** [comment]
Same issue here, the login in web browser can be bypassed by setting `fusion_idsdk=false` in the fusion environment variables. instructions for setting an environment variable can be found here: https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Setting-Environment-Variables-for-use-in-Fusion-360.html

**Comment by AndBondStyle** [comment]
I tried to set she `FUSION_IDSDK` variable directly in the windows cmd prompt, and somehow it worked. I think maybe @cryinkfly's launch script or wine itself doesn't set the windows env var properly.

```
(linux) $ WINEPREFIX="$HOME/.fusion360/wineprefixes/default" wine cmd
C:\windows> set FUSION_IDSDK=false
C:\windows> start "" "../users/Public/Desktop/Autodesk Fusion 360.lnk"
```
