### ISSUE TITLE
Error 404 - Repository missing or readme pointing to the wrong repository? *Solved*

### ISSUE THREAD

**Issue by Grumium** [cryinkfly/Autodesk-Fusion-360-for-Linux#379]
The repository "Autodesk-Fusion-360-for-Linux" in [alextrical's Github](https://github.com/alextrical) does not longer exist. Thus, there is no install script at 
[https://raw.githubusercontent.com/alextrical/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/install.sh](https://raw.githubusercontent.com/alextrical/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/install.sh)
as introduced per commit https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/commit/80892008d87c927b189b66179944ce2e80027171

Please provide the correct install script and adapt the documentation accordingly.

**Comment by alextrical** [comment]
Sorry about that. I didn't think there where any legacy scripts that relied upon my repo. I did a cleanup a month ago of some repos that weren't being actively developed by myself (and where falling behind upstream)

**Comment by Grumium** [comment]
Thanks. As long as both scripts are consistent, only the URL in the docs needs an adjustment.
