### ISSUE TITLE
[INFO] New link for Fusion Admin Install *Solved*

### ISSUE THREAD

**Issue by zakutin** [cryinkfly/Autodesk-Fusion-360-for-Linux#380]
FYI, due to the [branding name change](https://www.autodesk.com/products/fusion-360/blog/january-2024-product-update-whats-new/) from "Fusion 360" to "Fusion" the admin installation link is not working anymore.

The new link is however could be obtained by removing "360":
`https://dl.appstreaming.autodesk.com/production/installers/Fusion%20Admin%20Install.exe`

@cryinkfly, could you please change all instances and places where this link is used? (For example in [Documentation](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/wiki/Documentation#installation-of-autodesk-fusion-360))

Extra info [here](https://forums.autodesk.com/t5/fusion-support/new-links-for-fusion-admin-install/td-p/12529057).

**Comment by JurgenCruz** [comment]
I think the URL is now `https://dl.appstreaming.autodesk.com/production/installers/Fusion%20Client%20Downloader.exe` because I was not able to download the `Fusion%20Admin%20Install.exe`.
