### ISSUE TITLE
Font is miss rendered with dpi=96 works fine when changed to dpi=97

### ISSUE THREAD

**Issue by Farouk123456** [cryinkfly/Autodesk-Fusion-360-for-Linux#384]
After launching f360, some texts appear miss rendered i.e. irregular spacing between characters and missing characters such as capital I

with dpi = 96 (Notice Missing I on "MODIFY" and "CONFIGURE"

![pp](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/60853263/a8d59df9-2d9e-4206-9726-0ca4739a45e0)

with dpi = 97

![pp2](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/60853263/ca7df4ea-bcc0-4d4f-be6c-4b654eb12965)

latest version of fusion360 with new fixes from issue #381 
Integrated Vega 8 AMD GPU && using OpenGL core
Kali Linux
gnome

**Comment by aedancullen** [comment]
Random shot in the dark, but you could try `winetricks fontsmooth=rgb`.

**Comment by Farouk123456** [comment]
Wow, thanks while this did work on the main menu it doesn't work everywhere, for example in preferences:

![Screenshot_20240204_191110](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/60853263/1aeff758-d594-429f-b9bb-80e6bd19a1e1)

Capital W's are cutoff (IDK if this is implementable, but maybe antialiasing support could be added)
Somehow setting dpi to something other than 96 fixes this completely, maybe this is an optimization gone wrong or something

**Comment by str0g** [comment]
> After launching f360, some texts appear miss rendered i.e. irregular spacing between characters and missing characters such as capital I
> 
> with dpi = 96 (Notice Missing I on "MODIFY" and "CONFIGURE"
> 
> ![pp](https://private-user-images.githubusercontent.com/60853263/302114363-a8d59df9-2d9e-4206-9726-0ca4739a45e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTcxOTUsIm5iZiI6MTcwNzExNjg5NSwicGF0aCI6Ii82MDg1MzI2My8zMDIxMTQzNjMtYThkNTlkZjktMmQ5ZS00MjA2LTk3MjYtMGNhNDczOWE0NWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA3MDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3YmE0YWViZDlhYWFhODkzZmViYTQxZmNmMzc2ZTVjZmJkNjViMGMxNTU5NGM0NzQzODFkNTJhOTExMTY1ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qo-kWPrI8Y5QFclr3djxHhj7o-lyicIAErlCF_2dBQQ)
> 
> with dpi = 97
> 
> ![pp2](https://private-user-images.githubusercontent.com/60853263/302114393-ca7df4ea-bcc0-4d4f-be6c-4b654eb12965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTcxOTUsIm5iZiI6MTcwNzExNjg5NSwicGF0aCI6Ii82MDg1MzI2My8zMDIxMTQzOTMtY2E3ZGY0ZWEtYmNjMC00ZDRmLWJlNmMtNGI2NTRlYjEyOTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA3MDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5MGRkZWNkYWU5NWMyYzRhMzEwMzBmNmJlMzZiNDY3NTI3NDNkZWQwYmQ5MWZlOTM0OTkwODllNzQwNjk0OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XpPuPg1xhxUaLk5UJ6Tc5GiaZ8HXf3q5Ah68i97ve1I)
> 
> latest version of fusion360 with new fixes from issue #381 Integrated Vega 8 AMD GPU && using OpenGL core Kali Linux gnome

On amd go with galliumnine and set fusion to use dx9. You will see things which was not drawn previously ;-)

**Comment by cryinkfly** [comment]
@str0g I will look to galliumnine... THX :+1:

**Comment by cryinkfly** [comment]
I have configured the installer so, that directx9 also works now with amd gpus!
