### ISSUE TITLE
no more webview error, but still not getting into the application

### ISSUE THREAD

**Issue by RainaMatthews** [cryinkfly/Autodesk-Fusion-360-for-Linux#385]
**Describe the bug**
I've downloaded the most recent installer, ensured I have wine-9.1(staging) running, yet still can't actually get into the application

installation appears to complete successfully, and the WebView component also appears to install correctly.

however when I click the 'Sign In' button on the initial welcome to Fusion screen, nothing actually happens from that point.

as I understand it, my browser is supposed to open up and I'm then taken to the login. but neither chrome, nor firefox open and so no further action can be taken.

I'm currently on mint 21, fresh install

when running from a terminal, I do see a 'Connection Reset by Peer error after clicking the login button, but nothing further.  it does appear as if it's 'TRYING' to do something, but even leaving it for a while to see if something times out etc doesn't really seem to make much difference.

**To Reproduce**info:  DXGI: Hiding actual GPU, reporting vendor ID 0x1002, device ID 73df
BUG OptionAdapter UseEagleRc called before setting callbacks.EagleAPI.Version = 0.1.2
BUG OptionAdapter UseEagleRc called before setting callbacks.BUG OptionAdapter UseEagleRc called before setting callbacks.QString::arg: 1 argument(s) missing in %1/scripts
QString::arg: 1 argument(s) missing in %1/scripts
BUG OptionAdapter UseEagleRc called before setting callbacks.QString::arg: 1 argument(s) missing in %1/ulps
QString::arg: 1 argument(s) missing in %1/ulps
BUG OptionAdapter UseEagleRc called before setting callbacks.QString::arg: 1 argument(s) missing in %1/design rules
QString::arg: 1 argument(s) missing in %1/design rules
BUG OptionAdapter UseEagleRc called before setting callbacks.QString::arg: 1 argument(s) missing in %1/spice
QString::arg: 1 argument(s) missing in %1/spice
Registering module:  "uiHelper"
EnableNonClientDpiScaling() failed for HWND 0x40212 (120) (Call not implemented.)
"11:58::33.561" MAGWorkControllerClientConnection  cmd sent  "auth"
"11:58::33.562" MAGWorkClientControllerConnection  cmd sent  "auth"
MAGWorkControllerClientConnection  cmd received  "auth"
"11:58::33.563" MAGWorkControllerClientConnection  cmd sent  "authok"
MAGWorkClientControllerConnection  cmd received  "auth"
"11:58::33.563" MAGWorkClientControllerConnection  cmd sent  "authok"
MAGWorkClientControllerConnection  cmd received  "authok"
MAGWorkControllerClientConnection  cmd received  "authok"
Connecting to controller server
Controller server info:  QHostAddress("127.0.0.1") : 44667
host connected QHostAddress("127.0.0.1") : 38210
"11:58::33.570" MAGWorkControllerHostConnection  cmd sent  "auth"
"11:58::33.571" MAGWorkHostControllerConnection  cmd sent  "auth"
MAGWorkControllerHostConnection  cmd received  "auth"
"11:58::33.572" MAGWorkControllerHostConnection  cmd sent  "authok"
MAGWorkHostControllerConnection  cmd received  "auth"
"11:58::33.572" MAGWorkHostControllerConnection  cmd sent  "authok"
MAGWorkHostControllerConnection  cmd received  "authok"
Controller connected
Sending max processes:  12
"11:58::33.573" MAGWorkHostControllerConnection  cmd sent  "ready"
MAGWorkControllerHostConnection  cmd received  "authok"
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:9766
MAGWorkControllerHostConnection  cmd received  "ready"
[40229:40229:0205/115857.233670:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)

**Comment by gnrgui** [comment]
Mine is hanging on the splash screen forever, fresh install using the latest script

**Comment by joshuazick1** [comment]
browser window is crashing when called on
```
ProblemType: Crash
Architecture: amd64
CrashCounter: 1
Date: Thu Feb  8 02:02:07 2024
DistroRelease: Ubuntu 23.10
ExecutablePath: /opt/google/chrome/chrome
ExecutableTimestamp: 1707171572
ProcAttrCurrent: /opt/google/chrome/chrome (unconfined)
ProcCmdline: /opt/google/chrome/chrome\ https://developer.api.autodesk.com/authentication/v2/authorize?client_id=W4OzUBRrCUtlVRIgARbv5rRIKMHe7dXp&response_type=code&response_mode=query&scope=user-profile%3Aread%20user%3Aread%20user%3Awrite%20viewables%3Aread%20data%3Aread%20data%3Awrite%20data%3Acreate%20data%3Asearch%20bucket%3Acreate%20bucket%3Aread%20bucket%3Aupdate%20bucket%3Adelete%20code%3Aall%20account%3Aread%20account%3Awrite%20openid%20device_sso&redirect_uri=https%3A%2F%2Faccounts.autodesk.com%2Fidmgr%2Fcallback&code_challenge_method=S256&code_challenge=$THISISPROBABLYSUPERSECRET
ProcCwd: /home/user/.fusion360/wineprefixes/default/drive_c/Program Files/Autodesk/webdeploy/production/57cd45aa09be2d79663784069561ec17eda99ca8/Autodesk Identity Manager
```

I was able to grab the URL from the crash log and log in, however I was never able to return to the program.  This persisted even after updating the .desktop to properly point towards 57cd45aa09be2d79663784069561ec17eda99ca8 instead of 99249ee497b13684a43f5bacd5f1f09974049c6b.

even when the id manager is called directly from the command line

```
user@1:~$ env WINEPREFIX="/home/user/.fusion360/wineprefixes/default" wine /home/user/.fusion360/wineprefixes/default/drive_c/Program Files/Autodesk/webdeploy/production/57cd45aa09be2d79663784069561ec17eda99ca8/Autodesk Identity Manager/AdskIdentityManager.exe /login?code=$ALSOPROBABLYSECRET
[1] 13749
user@1:~$ wine: could not open working directory L"unix\\home\\user\\", starting in the Windows directory.
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

06a0:fixme:ver:GetCurrentPackageId (000000000021FEB0 0000000000000000): stub

[1]+  Exit 1                  env WINEPREFIX="/home/user/.fusion360/wineprefixes/default" wine /home/user/.fusion360/wineprefixes/default/drive_c/Program Files/Autodesk/webdeploy/production/57cd45aa09be2d79663784069561ec17eda99ca8/Autodesk Identity Manager/AdskIdentityManager.exe /login?code=$ALSOPROBABLYSECRET
```

This is all ran on a fresh Ubuntu 23.10 VM with only winehq-staging installed.

**Comment by robert-stevenson-1** [comment]
When proceeding to log in, the login page appears in Firefox, however I can't get it to redirect back to fusion.
I also tried calling ID manager, like @joshuazick1, but was also unsuccessful and have to manually kill fusion (or wait a really long time for it to eventually prompt a force quit) as it freezes at this point and can't be closed in any other ways.

**Comment by Sjgharib** [comment]
I tried changing the registry keys to point to the native firefox browser, but I still get the error about the Microsoft WebView2 component error.
I've tried installing the webview component with wine, but the installation hangs.  
How have others gotten past this stage?

**Comment by Gamoid786** [comment]
I am also having a issue logging into Fusion 360 while using arch with hyprland as when i click the login button, firefox does open and then the prompt to take me to log me into the app does appear and after clicking yes use adskidmgr scheme handler nothing else happens and i still am not logged in

PS: im a linux noob

**Comment by shprota** [comment]
I had (have) the same issue. The browser would  crash trying to open the login URL and the Fusion was stuck not receiving the browser launch confirmation.
I could overcome this with the following steps and now have a working setup:

1. Create a simple shell script with the following contents and name it `fakebrowser.sh`:
```bash
#!/bin/bash

echo args: $* >> ~/fakebrowser.log
```
2. Create `fakebrowser.desktop` file in ~/.local/share/applications (change the executable path as appropriate): 
```ini
[Desktop Entry]
Type=Application
Name=Fakebrowser
MimeType=MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;video/webm;application/x-xpinstall;
Exec=<Path to>/fakebrowser.sh %u
NoDisplay=false
StartupNotify=true
```

3. Refresh your system launcher menu (in KDE I just open the menu editor and make sure the `fakebrowser` app is there, then click on Save).

4. Open settings for applications association and in "Default Applications" select `fakebrowser` as Web browser.

5. Issue the following command from terminal:
```bash
tail -f ~/fakebrowser.log
```
6. Launch Fusion and click on the login button
7. The URL it wants to open will appear in the `tail` output
8. Open that URL in your preferred browser and perform the login
9. (Optional) In case your browser cannot open the Fusion AdskIdMgr or the Fusion doesn't react on opening external link from your browser, restart Fusion (re-start at step 6) and in your browser instead of clicking on the button to open external app, just copy the button link URL and then go to your terminal to perform the following commands:
```bash
export WINEPREFIX=~/.fusion360/wineprefixes/default 
export ADSKIDMGR=$(find $WINEPREFIX -name "AdskIdentityManager.exe")
wine "$ADSKIDMGR" "<paste the button URL here>"
```

Hope that helps.

**Comment by cryinkfly** [comment]
Solved.
