### ISSUE TITLE
No windows, fusion won't launch

### ISSUE THREAD

**Issue by Vanilla009** [cryinkfly/Autodesk-Fusion-360-for-Linux#388]
**Describe the bug**
After installing, either start the launcer via command line via the `.fusion360/wineprefixes/default/box-run.sh` command

**To Reproduce**
Run `sudo apt install wine64`
Run `sudo apt install yad`
Run `mkdir -p "$HOME/.fusion360/bin"
cd "$HOME/.fusion360/bin"
wget -N https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/install.sh
chmod +x install.sh
./install.sh`
Select Wine (staging)
Try to run fusion
Nothing appears and you get an error that says `The version.txt file does not exist!`

**Expected behavior**
Fusion to start and run or a window of any sort to appear

**Screenshots**

**Desktop (please complete the following information):**
- Latest version of fusion
- Integrated graphics Inspiron 5482
- Ubuntu 22.04
- Desktop environment (XFCE 4.16, Gnome 40, ...)
- DXVK- or OpenGL-Mode

**Additional context**
This is a fresh install.

**Comment by ligmaSec** [comment]
same here

**Comment by JoeyAW** [comment]
Did you try hitting the preferences button when you run the install script? I found out that my driver was set to DXVK and it needed to be changed to opengl before installing.
