### ISSUE TITLE
Unable to login with Brave

### ISSUE THREAD

**Issue by mtthw-meyer** [cryinkfly/Autodesk-Fusion-360-for-Linux#389]
**Describe the bug**
When Brave is the default browser the login screen is never redirected to. 

**To Reproduce**
1. Install
2. Start fusion360
3. Click sign in

**Expected behavior**
Brave window opens for login

**Desktop (please complete the following information):**
- Linux Mint 21.2
- Cinnamon
- OpenGL-Mode

**Additional context**
When I switch the default browser to firefox it works. Until the other login bug prevents the token from working correctly.

**Comment by raina343** [comment]
it MAY be an issue with all Chromium based browsers.  I've not been able to login for weeks, until I saw your post.  Switched from Chrome as default to firefox, and it worked like a charm.

**Comment by cristianogregnanin** [comment]
same problem but don't works with chrome and firefox in debian 12

**Comment by dukenukemx** [comment]
Doesn't even work for me in FireFox.  It says it redirects but Fusion windows seems frozen.

**Comment by poon-holder** [comment]
its near impossible to get the fusion file from autodesk on brave i find. Unchecking the use defualt always rechecks its self when im redirected from the log in windows. 

Would be good to have an updated DL link on here. Am i missing something in have to reinstall everything each time this breaks?

**Comment by netsatan** [comment]
Same issue here on Ubuntu 22.04, neither Firefox nor other browser work.

**Comment by cryinkfly** [comment]
With firefox it works now. See new alpha version of the installer.
