### ISSUE TITLE
Cant login on flatpak version

### ISSUE THREAD

**Issue by TRMiner1** [cryinkfly/Autodesk-Fusion-360-for-Linux#393]
**Describe the bug**
Cant sign in on flatpak version

**To Reproduce**
download bottles from kde software center
create bottle
add fusion360
run
click sign in
"check your web browser to sign in"
web browser is unchanged

**Expected behavior**
my web browser should probably open

**Screenshots**
n/a

**Desktop:**
- Version number of Autodesk Fusion 360: i have no idea how to find out but whatever was in the install programs menu of bottles at the time of posing this
- Graphics card model: AMD APU 0405 + Graphics card driver (Version number): i dont know
- Operating system: Arch(Steam deck Steamos)
- Desktop environment: kde plasma 5.27.5
- DXVK- or OpenGL-Mode: it says dxvk-2.3

**Additional context**
i am using firefox
i started using linux less than 2 months ago and i might not know what i am doing

**Comment by daranto** [comment]
I have the same issue.

**Comment by bigblzrd** [comment]
Same issue here also, tried the normal install and had the same problem, managed to fix that but it wasn't running well so thought I'd try bottles.

**Comment by TRMiner1** [comment]
update: i have tried it with a different computer and it still does not work
Desktop: 
Graphics card model: NVIDIA GTX 750 ti + Graphics card driver (Version number): i still dont know
Operating system: Kubuntu 23.10 (ubuntu but with kde)
DXVK- or OpenGL-Mode: it says dxvk-2.3

**Comment by DragonflyRobotics** [comment]
I am having the same issue. The application crashes when I click the login button.

**Comment by Hoeze** [comment]
Same issue here. It does not crash, but it also does not open any browser window.
I even tried installing firefox in the bottle.

**Comment by Cxmrykk** [comment]
I am using Debian 12 (Gnome) Flatpak Bottles, the browser login window opens for me if I use `sys-wine-9.0` as the runner, however the link does not redirect to Fusion360 after logging in - "There are no available apps that can open this link `adskidmgr:/login?code=(code)`". My browser is Firefox

**Comment by desmotronic** [comment]
Same issue here.  Tried native Firefox browser and also chrome based browser.  None of the browsers open when clicking sign in button on Fusion flatpak.

**Comment by Matt2D3** [comment]
for me, running through bottles opens the Linux native browser to the sign in page, however, i am not redirected to fusion360 and am not logged in
caffe-8.21
ubuntu 23.10
firefox 123.0.1 (snap)

**Comment by Matt2D3** [comment]
I switched over to the deb version of firefox and got a new error message
wine: chdir to /home/matt2d2/.fusion360/wineprefixes/default : No such file or directory
I think that whatever is redirecting the link from firefox to Adskidentitymanager is redirecting to the default prefix, not the bottles prefix

**Comment by monte-monte** [comment]
> I am using Debian 12 (Gnome) Flatpak Bottles, the browser login window opens for me if I use `sys-wine-9.0` as the runner, however the link does not redirect to Fusion360 after logging in - "There are no available apps that can open this link `adskidmgr:/login?code=(code)`". My browser is Firefox

Add shortcut to "Program Files/Autodesk/webdeploy/production/*whatever_digits*/Autodesk Identity Manager/AdskIdentityManager.exe"
Then "Change Launch Options > Command Arguments > paste link from autodesk login page "adskidmgr:/login?code=*whatever numbers"
Launch it, fusion should proceed with login.

**Comment by Bombenscheck** [comment]
Have Tested this. it does not work.

> Add shortcut to "Program Files/Autodesk/webdeploy/production/_whatever_digits_/Autodesk Identity Manager/AdskIdentityManager.exe"
> Then "Change Launch Options > Command Arguments > paste link from autodesk login page "adskidmgr:/login?code=*whatever numbers"
> Launch it, fusion should proceed with login.
The Link I got is much longer, it looks a bit different: 
adskidmgr:/login?code=*whatever numbers"&state=*some other numbers*
I tried it with both the Complete Version by Setting the Command Arguments to:
%command%adskidmgr:/login?code=*whatever numbers"
and also with the Complete Link:
%command%adskidmgr:/login?code=*whatever numbers"&state=*some other numbers*
Did I do something wrong? Do i Need to only put in the Link without %command%

**Comment by monte-monte** [comment]
@Bombenscheck yes, you need to paste full link, ending with ``=``, put it in quotation marks without ``%command%`` like that:
![image](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/6649967/1acfefae-c64f-4928-bbba-883edf19428c)

Then I ran it in terminal, it print some output and main Fusion window then logs in, then you can close AdskIdentityManager. You need wine 9 or higher for this to work.

**Comment by Bombenscheck** [comment]
OK, my bad, did not add " at the Beginning and End
Thank you for the help
To sumarize for everyone facing the same Problem

1. Use Sys Wine (I used 9.0) and not a Wine instance downloaded over Bottles
2. Add shortcut to "Program Files/Autodesk/webdeploy/production/whatever_digits/Autodesk Identity Manager/AdskIdentityManager.exe" in Bottles (the login seems to have a Timeout later)
3. Lauch Fusion360 and press Login
4. Login should open in default Browser
5. Close Fusion (System Side Browser will not close)
6. Login Until the "Go to product" Links Shows
7. Copy Link 
8. Add "*Link*" to the Launch options of AdskIdentityManager
9. Launch AdskIdentityManager in Terminal
10. Relaunch Fusion360
Fusion Should now be logged in.

**Comment by monte-monte** [comment]
> 5\. Close Fusion (System Side Browser will not close)

You don't need to close fusion. Just launch AdskIdentityManager with current link and close it once Fusion window proceeds to load.

**Comment by TRMiner1** [comment]
alright so i kinda forgot that i posted this for 3 weeks
but after doing everything that was in the condensed version by Bombenscheck i have got it working sorta i think it might be a graphics driver/card issue because it starts and runs but the viewport is black and i cant see anything there, fullscreen breaks everything, when i move the window the menu at the left of the viewport(i have no idea what it is called but it has the bodies and stuff) lags and it stays visible  when i minimize the window 
i am working on fixing it right now(maybe downgrading drivers will help?)
thank you everyone for the responses

**Comment by TRMiner1** [comment]
alright update already it seems the browser(menu thing) renders above all other windows

**Comment by Bombenscheck** [comment]
> alright so i kinda forgot that i posted this for 3 weeks but after doing everything that was in the condensed version by Bombenscheck i have got it working sorta i think it might be a graphics driver/card issue because it starts and runs but the viewport is black and i cant see anything there, fullscreen breaks everything, when i move the window the menu at the left of the viewport(i have no idea what it is called but it has the bodies and stuff) lags and it stays visible when i minimize the window i am working on fixing it right now(maybe downgrading drivers will help?) thank you everyone for the responses

have you tried to set the graphics mode to "openGL Core"? fusion360 defaults to "Auto" which caused the same issiue on my install.

**Comment by monte-monte** [comment]
> alright update already it seems the browser(menu thing) renders above all other windows

That's not fixable at the moment, if it bothers you too much the only way is to use wine's virtual desktop, but then it has it's own drawbacks.

> have you tried to set the graphics mode to "openGL Core"? fusion360 defaults to "Auto" which caused the same issiue on my install.

In my experience if you use opengl, instead directx (via dxvk) it causes lines and points in sketch not highlighting when selected, very bad for productivity. I am using bottles with "kron4ek-wine-9.3-staging-tkg-amd64" build and dxvk-2.4 and it works both with AMD drivers and also with discrete nvidia card. At first I also had black screen, but fiddling with wine versions and setting somehow made everything work.

**Comment by Ameb** [comment]
> have you tried to set the graphics mode to "openGL Core"? fusion360 defaults to "Auto" which caused the same issiue on my install.

This improved my  issue #401 , thanks you.

**Comment by TRMiner1** [comment]
thank you everyone for the help. by changing graphics settings to opengl core it works i am seeing the weird highlighting things but this is way more usable than the web version(since creating the original issue i got educational access to see if the web version would work(it very much didn't)) and it is good enough for me to continue my projects

**Comment by Bbenno-UX** [comment]
I think i need to add something here. This issue didnt help me getting Fusion360 to work. monte-monte forgot to mention here that he changed the runner to "kron4ek-wine-9.3-staging-tkg-amd64" as he mentioned in Issue #319 https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/319#issuecomment-1988585332 it didnt work until installed the new runner.

**Comment by skarzzzz** [comment]
> OK, my bad, did not add " at the Beginning and End Thank you for the help To sumarize for everyone facing the same Problem
> 
> 1. Use Sys Wine (I used 9.0) and not a Wine instance downloaded over Bottles
> 2. Add shortcut to "Program Files/Autodesk/webdeploy/production/whatever_digits/Autodesk Identity Manager/AdskIdentityManager.exe" in Bottles (the login seems to have a Timeout later)
> 3. Lauch Fusion360 and press Login
> 4. Login should open in default Browser
> 5. Close Fusion (System Side Browser will not close)
> 6. Login Until the "Go to product" Links Shows
> 7. Copy Link
> 8. Add "_Link_" to the Launch options of AdskIdentityManager
> 9. Launch AdskIdentityManager in Terminal
> 10. Relaunch Fusion360
>     Fusion Should now be logged in.

sorry im new i used to have fusion working before the uodate 
what do you mean add shortcut? where can i find or do this please

**Comment by skarzzzz** [comment]
> > I am using Debian 12 (Gnome) Flatpak Bottles, the browser login window opens for me if I use `sys-wine-9.0` as the runner, however the link does not redirect to Fusion360 after logging in - "There are no available apps that can open this link `adskidmgr:/login?code=(code)`". My browser is Firefox
> 
> Add shortcut to "Program Files/Autodesk/webdeploy/production/_whatever_digits_/Autodesk Identity Manager/AdskIdentityManager.exe" Then "Change Launch Options > Command Arguments > paste link from autodesk login page "adskidmgr:/login?code=*whatever numbers" Launch it, fusion should proceed with login.

how do you add the shortcut to that address, clicking add shortcut brings up the local drive how do i navigate to that through linux?

**Comment by Ameb** [comment]
> how do i navigate to that through linux?

The "browse files" on bottles can show you where the  "C drive" is located (for me it is in `$HOME/.var/app/com.usebottles.bottles/data/bottles/bottles/<bottle_name>/drive_c/`)

![image](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/386567/669dc76b-b55d-4292-8ad2-5daeb3301b88)

**Comment by skarzzzz** [comment]
> > how do i navigate to that through linux?
> 
> The "browse files" on bottles can show you where the "C drive" is located (for me it is in `$HOME/.var/app/com.usebottles.bottles/data/bottles/bottles/<bottle_name>/drive_c/`)
> 
> ![image](https://private-user-images.githubusercontent.com/386567/316259702-669dc76b-b55d-4292-8ad2-5daeb3301b88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMTY2NjgsIm5iZiI6MTcxMTIxNjM2OCwicGF0aCI6Ii8zODY1NjcvMzE2MjU5NzAyLTY2OWRjNzZiLWI1NWQtNDI5Mi04YWQyLTVkYWViMzMwMWI4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QxNzUyNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmYyNzg5ZDY4NDAzOWU3OTIyNmU3YjYzYWViYTc1YzAzODU4ZmE2MTdmOGU4ZGZjZTE3ZTk4ZmViZDZkNjI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VXdyfuiT-XIG2EkkaKNy6323mYbMkhW3tnM7NGgVyLY)

thankyou i did think that was t4he case just wasnt sure as it wasnt very clear haha

**Comment by skarzzzz** [comment]
> OK, my bad, did not add " at the Beginning and End Thank you for the help To sumarize for everyone facing the same Problem
> 
> 1. Use Sys Wine (I used 9.0) and not a Wine instance downloaded over Bottles
> 2. Add shortcut to "Program Files/Autodesk/webdeploy/production/whatever_digits/Autodesk Identity Manager/AdskIdentityManager.exe" in Bottles (the login seems to have a Timeout later)
> 3. Lauch Fusion360 and press Login
> 4. Login should open in default Browser
> 5. Close Fusion (System Side Browser will not close)
> 6. Login Until the "Go to product" Links Shows
> 7. Copy Link
> 8. Add "_Link_" to the Launch options of AdskIdentityManager
> 9. Launch AdskIdentityManager in Terminal
> 10. Relaunch Fusion360
>     Fusion Should now be logged in.

Okay so ive done everything on this list, when opening Adsk via terminal it opens but then nothing seems to happen on the terminal? then launching fusion proceeds to still ask for the login

**Comment by skarzzzz** [comment]
Kinda forgot to put quotations, so ive got it working now but theres some graphical issues the ui has loaded but i cant see the white background and i cant actually open a file
![Screenshot_20240323_180548](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/47511052/19a2de4e-e8a2-461d-ac65-ea3ff24d97e4)

**Comment by Ameb** [comment]
Ensure you have quotes around the link `"`... While typing you got it solved, nice.
The background issue is related to the graphics mode, you can set it to openGL Core like in https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/401#issuecomment-1993855862 

First I would try to run on Dx9 with this combination of settings: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/401#issuecomment-2003639665. You will need to add the runners to Bottles first.

**Comment by skarzzzz** [comment]
So I tried to do those settings now it just crashes and I can’t access the program to revert the settings back, I don’t know where the Nmachine file is either as I don’t have a .fusion folder

**Comment by Ameb** [comment]
The settings file can be locate in the bottles windows path `drive_c/users/$USER/AppData/Roaming/Autodesk/Neutron Platform/Options/NMachineSpecificOptions.xml` 

You can edit that file to edit settings without running the program. In my case, the preference dialog doesn't open and using Dx9 crashed fusion until I changed the runner.

I suggested to first try the Bottle settings, without touching Fusion preferences. Which fusion's preferences did you changed which crashed fusion? Did you modified the Bottle's settings?

At this point, I think we should add a discussion thread about running Fusion on the Steamdeck with flatpak. @TRMiner1 got it working before, maybe he can help.

**Comment by skarzzzz** [comment]
I’ll have a look at that path, I did just delete the bottle and reinstall it but now it doesn’t allow me to open the preferences inside of fusion like it did the first time, I’m using wine 9.0 that’s the only setting I’ve changed in bottle then inside fusion I changed it to OpenGL but for some odd reason it wouldn’t let me to select some stuff so I tried DX9 and that crashed it so I tried cafe inside of wine and it made no difference

**Comment by skarzzzz** [comment]
So I reinstalled fusion with bottles, did the adsk link to get logged in then I changed the graphics to OpenGL, re opened and it wouldn’t let me open a file it would just not do anything, so closed it changed to caffe, that didn’t want to open, so changed it back to wine 9.0 and now it opens the splash screen but then it just shuts down it doesn’t open anymore?
