### ISSUE TITLE
Brave not redirecting on login

### ISSUE THREAD

**Issue by reneas** [cryinkfly/Autodesk-Fusion-360-for-Linux#396]
When clicking "Sign In" from the Fusion window it opens the login screen on Brave. After signing in, it never redirects back to Fusion.

**To Reproduce**
1. Start Fusion
2. Click on 'Sign in'
3. Brave Browser Tab opens 
4. Log into Autodesk Account
5. Nothing happens

**Expected behavior**
1. Start Fusion
2. Click on 'Sign in'
3. Brave Browser Tab opens 
4. Log into Autodesk Account
5. Redirection to Fusion with successful login

**Desktop:**
- Kubuntu 22.04
- KDE Plasma 5.24.7
- OpenGL-Mode

**Additional context**
when starting brave via konsole it give this error message:
```
wine: failed to open "C:\\rogram Files\\utodesk\\ebdeploy\\roduction\\a22ca515421cec8a3addbf5f00fde68499915d7\\utodesk Identity Manager\\dskIdentityManager.exe": c0000135
```

Doing the same thing with `firefox` as default browser works as expected as mentioned [here](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/389#issue-2128711009)

**Comment by michaelcadilhac** [comment]
Looks like backslashes in the `adskidmgr-opener.desktop` file need to be escaped: https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables

**Comment by dukenukemx** [comment]
I have this problem too and it's still stuck on Sign In.  I'm on Linux Mint with FireFox.

**Comment by sd1337** [comment]
I have had the same problem yesterday, it seems that webdeploy changes path on every update and then the .desktop file for for adskmgr link is broken. 
Open ~/.local/share/applications/adskidmgr-opener.desktop and look if the Exec Path matches the actual directory:
`Exec=env WINEPREFIX="/home/#USER#/.fusion360/wineprefixes/default" wine "C:\Program Files\Autodesk\webdeploy\production\#CHANGES#\Autodesk Identity Manager\AdskIdentityManager.exe" %u`
Navigate to your Wineprefix Directory and search for "AdskIdentityManager.exe"
`find . -name "AdskIdentityManager.exe"`
The result should be something like this:
`./drive_c/Program Files/Autodesk/webdeploy/production/#CHANGES#/Autodesk Identity Manager/AdskIdentityManager.exe`
Then replace the path in the .desktop file and try the sign in again

**Comment by waffi121** [comment]
@sd1337 Thank you! I was just able to log in with it under Linux Mint and Firefox. <3

**Comment by dukenukemx** [comment]
> I have had the same problem yesterday, it seems that webdeploy changes path on every update and then the .desktop file for for adskmgr link is broken. Open ~/.local/share/applications/adskidmgr-opener.desktop and look if the Exec Path matches the actual directory: `Exec=env WINEPREFIX="/home/#USER#/.fusion360/wineprefixes/default" wine "C:\Program Files\Autodesk\webdeploy\production\#CHANGES#\Autodesk Identity Manager\AdskIdentityManager.exe" %u` Navigate to your Wineprefix Directory and search for "AdskIdentityManager.exe" `find . -name "AdskIdentityManager.exe"` The result should be something like this: `./drive_c/Program Files/Autodesk/webdeploy/production/#CHANGES#/Autodesk Identity Manager/AdskIdentityManager.exe` Then replace the path in the .desktop file and try the sign in again

Holy crap that worked.  That seems like an easy mistake to make.

**Comment by PedroMTSilva** [comment]
> I have had the same problem yesterday, it seems that webdeploy changes path on every update and then the .desktop file for for adskmgr link is broken. Open ~/.local/share/applications/adskidmgr-opener.desktop and look if the Exec Path matches the actual directory: `Exec=env WINEPREFIX="/home/#USER#/.fusion360/wineprefixes/default" wine "C:\Program Files\Autodesk\webdeploy\production\#CHANGES#\Autodesk Identity Manager\AdskIdentityManager.exe" %u` Navigate to your Wineprefix Directory and search for "AdskIdentityManager.exe" `find . -name "AdskIdentityManager.exe"` The result should be something like this: `./drive_c/Program Files/Autodesk/webdeploy/production/#CHANGES#/Autodesk Identity Manager/AdskIdentityManager.exe` Then replace the path in the .desktop file and try the sign in again

This also worked for me! For anyone having trouble still, dont forget that the windows paths are with a backslash `\` instead of `/`, so you would need to replace all of them. Works like a charm!

**Comment by imrYder** [comment]
Hi, i'm currently trying to launch fusion360 but i've encountered the same issue. I tried changing the AdskIdentityManager path in the adskidmgr.desktop file, I even replaced slashes by back-slaches, it seems like firefox doesn't find any application to handle the thing that is going out of the autodesk connexion page. I tried changing the default system app firefox choose to open adskidmgr to "AdskIdentityManager.exe", with no results... can someone help me pls ?? Thanks

**Comment by michaelcadilhac** [comment]
@imrYder 
- Find the `AdskIdentityManager.exe` file
- When Firefox opens the identification website, authenticate yourself
- On the next page, look for the "try again" link.
- Right click, copy that link.  It should start with `adskidmgr:/login`
- Execute:

```
 $ env WINEPREFIX="/home/micha/.fusion360/wineprefixes/default" wine 'C:\Program Files\Autodesk\....\AdskIdentityManager.exe' 'adskidmgr:/login?...'
```

**Comment by reneas** [comment]
I am closing this issue since the original problem got solved by changing the following line in `/home/reneas/.local/share/applications/adskidmgr-opener.desktop`:

old:
```
Exec=env WINEPREFIX="/home/reneas/Programme/Fusion" wine "C:\Program Files\Autodesk\webdeploy\production\0a22ca515421cec8a3addbf5f00fde68499915d7\Autodesk Identity Manager\AdskIdentityManager.exe" %u
```

new: 
```
Exec=env WINEPREFIX="/home/reneas/Programme/Fusion" wine "C:\\Program Files\\Autodesk\\webdeploy\\production\\0a22ca515421cec8a3addbf5f00fde68499915d7\\Autodesk Identity Manager\\AdskIdentityManager.exe" %u
```
(just added an extra backslash `\`  to each existing backslash)
