### ISSUE TITLE
OrcaSlicer compiling on raspi OS

### ISSUE THREAD

**Issue by chietal** [cryinkfly/Autodesk-Fusion-360-for-Linux#404]
I try to compile the OrcaSlicer on a raspberry pi with raspi os bookworm 64bit and i get an error message. What can I do to solve it?

The folder src/osx/ dont exist!

Fehler: Anwendung des Patches fehlgeschlagen: src/msw/window.cpp:4773
Fehler: src/msw/window.cpp: Patch konnte nicht angewendet werden
PrÃ¼fe Patch src/osx/cocoa/dataview.mm...
Fehler: bei der Suche nach:
        if ( !dvc->GetEventHandler()->ProcessEvent(eventDV) )
            [super keyDown:event];
    }
    else
    {
        [super keyDown:event];  // all other keys
    }
}

//
// contextual menus
//
a
Fehler: Anwendung des Patches fehlgeschlagen: src/osx/cocoa/dataview.mm:1734
Fehler: src/osx/cocoa/dataview.mm: Patch konnte nicht angewendet werden
PrÃ¼fe Patch src/osx/cocoa/settings.mm...
Fehler: bei der Suche nach:
// ----------------------------------------------------------------------------

// Get a system metric, e.g. scrollbar size
int wxSystemSettingsNative::GetMetric(wxSystemMetric index, const wxWindow* WXUNUSED(win))
{
    int value;

Fehler: Anwendung des Patches fehlgeschlagen: src/osx/cocoa/settings.mm:224
Fehler: src/osx/cocoa/settings.mm: Patch konnte nicht angewendet werden
PrÃ¼fe Patch src/osx/cocoa/window.mm...
Fehler: bei der Suche nach:
- (BOOL)isEnabled;
- (void)setEnabled:(BOOL)flag;

- (void)setImage:(NSImage *)image;
- (void)setControlSize:(NSControlSize)size;

Fehler: Anwendung des Patches fehlgeschlagen: src/osx/cocoa/window.mm:190
Fehler: src/osx/cocoa/window.mm: Patch konnte nicht angewendet werden
make[3]: *** [CMakeFiles/dep_wxWidgets.dir/build.make:117: dep_wxWidgets-prefix/src/dep_wxWidgets-stamp/dep_wxWidgets-patch] Fehler 1
make[2]: *** [CMakeFiles/Makefile2:638: CMakeFiles/dep_wxWidgets.dir/all] Fehler 2
make[1]: *** [CMakeFiles/Makefile2:738: CMakeFiles/deps.dir/rule] Fehler 2
make: *** [Makefile:423: deps] Fehler 2

**Comment by barbecued** [comment]
Seems you are asking in the wrong place.  Try https://github.com/SoftFever/OrcaSlicer

**Comment by chietal** [comment]
yes, thank you, was the wrong projekt, please delete it! thx! :-)
