### ISSUE TITLE
Preference Window won't open

### ISSUE THREAD

**Issue by lukash3003** [cryinkfly/Autodesk-Fusion-360-for-Linux#417]
Whenever I try to open the preference window (by clicking on my profile picture -> preferences) nothing will happen.
After clicking on the button, fusion will be unresponsive and I have to kill the process.

I am using Debian 12 (stable) with wine version 9.8
Kde Plasma with xorg

**Comment by lockenkop** [comment]
It took about 30s-1m for it to open for me.
Maybe try watiting a bit.

**Comment by uatec** [comment]
I have also replicated this. It took 30 seconds to open, and now it's not responding. (Although the resize handles appear, so SOMETHING is clearly working.

**Comment by MostHated** [comment]
I have some examples seen below. It's weird. Menu items don't like to open from the main menus, but if I go about it in a roundabout way, they open just fine. I am not sure what, if anything can even be done about this?

Here, I try to open the parameters window, which doesn't open (sometimes I randomly see something flash, like it's trying to open but then doesn't?). If I add the parameters item to the main menu as it's own item, though, it does open.
[fusion_menu_items.webm](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/3442753/3ebb0a28-c746-4c6e-8ab1-5660e867048d)

Another is trying to open export/open windows with similar behavior. 
[export_menu.webm](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/3442753/671d40ec-174c-4853-87ac-aabfa100fdcd)

**Comment by cpm64** [comment]
Update: not perfect but it fixes the open/export and other menu dialogs. Run winecfg for your fusion360 prefix, go to "Graphics" disable "Allow window manager to control window".

**Comment by MostHated** [comment]
> Update: not perfect but it fixes the open/export and other menu dialogs. Run winecfg for your fusion360 prefix, go to "Graphics" disable "Allow window manager to control windows".

I am about to try this, but I found I can get to most menus if I click and *hold* the mouse button, then don't release it until you get to the item you want to open. It doesn't work every time, but 80% of the time, I would say.

**Comment by uatec** [comment]
> Update: not perfect but it fixes the open/export and other menu dialogs. Run winecfg for your fusion360 prefix, go to "Graphics" disable "Allow window manager to control windows".

Following this DOES allow the menu options to work, however pop-up windows (like the extrude dialog and 3d print dialog) cannot be clicked on; it appears that they are simply clicked through now.

Additionally, the preferences window still takes 10s of seconds to load, but it IS operable and does not hang for me any more.
