### ISSUE TITLE
Invalid directory in winepreprefix

### ISSUE THREAD

**Issue by Boyfinn** [cryinkfly/Autodesk-Fusion-360-for-Linux#425]
I get this output in the terminal after clicking the "Check for updates" dialog when launching the installation: 
```
❯ ./launcher.sh 
--2024-06-06 13:34:21--  https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/build-version.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘/tmp/fusion360/build-version.txt’ not modified on server. Omitting download.

Online Build-Version: 2.0.17228
Online Insider-Build-Version: 2.0.17228
The version.txt file not exist!
EN
find: ‘’: No such file or directory
wine: invalid directory  in WINEPREFIX: not an absolute path

```
The application won't launch beyond this dialog.
System:
OS: Linux Mint 21.3 x86_64
Kernel version: 6.5.0-1023
Desktop: Cinnamon 6.0.4
Hardware:
CPU: AMD Ryzen 7 7700X
GPU: AMD ATI Radeon 7900XTX
Memory: 32GB

**Comment by MostHated** [comment]
I just got this same thing as well, after installing on Ubuntu 23.10.

**Comment by Aus-gez** [comment]
Looks like this and #410 may be the same issue.

Did you set a custom wineprefix location during the install or go with the default?

What happens if you say you don't want to check for updates? Does it fail in the same way?

**Comment by MostHated** [comment]
I was able to get it working by removing the ~/.fusion360 folder and then reinstalled it without ever touching any of the settings buttons or dropdowns. As soon as I did, it would mess up the install as seen above. Ex. If I thought about using a non-default install location, and pressed it, but then decided to just stick with the default in the dropdown, even though default was selected, it messed it up.

**Comment by Boyfinn** [comment]
> Looks like this and #410 may be the same issue.
> 
> Did you set a custom wineprefix location during the install or go with the default?
> 
> What happens if you say you don't want to check for updates? Does it fail in the same way?

If I cancel the install, and then run the install script as sudo instead, it works. However, the login seems to be broken, as it does take me to autodesk's login page with my default browser, but doesn't react in any way when trying to open the submitted form after login.
