### ISSUE TITLE
Unable to login with Ubuntu 24.04 *solved*

### ISSUE THREAD

**Issue by bereldhuin** [cryinkfly/Autodesk-Fusion-360-for-Linux#428]
With Ubuntu 24.04, when clicking on the signin button, nothing happens : no browser opens.

I tried the following things without success: 
- setup Firefox as the default browser (it seems it's now installed through snap)
- change the .desktop file as suggested in other issues (use .\\drive_c\\...)

I also tried to uninstall everything but when lauching the unstall app and confirmed that i wanted to remove Fusion360, nothing happens (no terminal, no other progress window).

Thanks for your help,

Fred

**Comment by bereldhuin** [comment]
BTW, I won't be able to help solving much on this, but I can help for testing ;-)

**Comment by jublin** [comment]
Try copying the sign in link in browser 

Then go to your install directory/AutoDesk Identity Manager/ and run: 

`WINE_PREFEX=$pwd wine AdskIdentityManager.exe "LINK"` (use double quotes)

**Comment by rusk911** [comment]
Confirm. Both firefox and chrome (set as default browsers) not reacting to webview call. 

> Try copying the sign in link in browser
> 
> Then go to your install directory/AutoDesk Identity Manager/ and run:
> 
> `WINE_PREFEX=$pwd wine AdskIdentityManager.exe "LINK"` (use double quotes)

Don't understand. Where do I copy sign in link from? Browser is not opening the sign in page at all. Why do I need to create new wineprefix within identity manager folder? Did you mean WINEPREFIX instead of WINE_PREFEX? Any info on how to collect useful debug information to solve the issue?

**Comment by bereldhuin** [comment]
THank you @jublin, but from what I saw on other issues, the command you provided is for the case when he link opens in the browser but it doesn't redirect back to Fusion360, right ? 

As @rusk911 stated, he has the same problem as me : the link doesn't open in any browser.

**Comment by GamerGuy95953** [comment]
> Try copying the sign in link in browser
> 
> Then go to your install directory/AutoDesk Identity Manager/ and run:
> 
> `WINE_PREFEX=$pwd wine AdskIdentityManager.exe "LINK"` (use double quotes)

I tried it and I got the following errors:

When I first tried it:
```
00d0:fixme:netapi32:NetGetJoinInformation Semi-stub (null) 0053FCCC 0053FCD0
00d0:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 7AA42131, 42) stub
00d0:fixme:process:SetProcessShutdownParameters (00000280, 00000001): partial stub.
00d0:fixme:heap:RtlSetHeapInformation HEAP_INFORMATION_CLASS 1 not implemented!
00d0:fixme:userenv:GetProfileType 0053FE08
00dc:fixme:advapi:RegisterEventSourceW ((null),L"edgeupdate"): stub
00dc:fixme:advapi:ReportEventW (CAFE4242,0x0004,0x0000,0x00000000,00000000,0x0001,0x00000000,0199FCD8,00000000): stub
00dc:fixme:advapi:DeregisterEventSource (CAFE4242) stub
00d0:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0053FECC
00e4:fixme:netapi32:NetGetJoinInformation Semi-stub (null) 0053FCCC 0053FCD0
00e4:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 7AA42131, 42) stub
00e4:fixme:process:SetProcessShutdownParameters (00000280, 00000001): partial stub.
00e4:fixme:heap:RtlSetHeapInformation HEAP_INFORMATION_CLASS 1 not implemented!
00e4:fixme:userenv:GetProfileType 0053FE08
00e4:fixme:process:WTSGetActiveConsoleSessionId stub
00e4:fixme:wtsapi:WTSQuerySessionInformationW Unimplemented class 24
0118:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0118:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0118:fixme:file:NtLockFile I/O completion on lock not implemented yet
```

Afterwards:
```
019c:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
019c:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
019c:fixme:file:NtLockFile I/O completion on lock not implemented yet
```

**Comment by AlixANNERAUD** [comment]
Same thing on debian 12

**Comment by KozhaAkhmet** [comment]
I installed on Kubuntu 24.04
The problem was Firefox from snap, which prevents interactions with fusion. I just installed from apt (installing from apt by default, will automatically install from snap. Thus, you should visit the website to configure).

**Comment by AlixANNERAUD** [comment]
I'm running Debian (without Snap installed, obviously) with Firefox installed from the official Mozilla repositories, but I still encounter the following issue : 
![Capture d’écran du 2024-06-23 14-00-36](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/assets/44531068/d86d5581-4be7-4085-a20e-d5d20556dae0)
I tried to install manually [WebView2](https://developer.microsoft.com/fr-fr/microsoft-edge/webview2/?form=MA13LH#download-section) but still doesn't work.

**Comment by AlixANNERAUD** [comment]
> I'm running Debian (without Snap installed, obviously) with Firefox installed from the official Mozilla repositories, but I still encounter the following issue : ![Capture d’écran du 2024-06-23 14-00-36](https://private-user-images.githubusercontent.com/44531068/342106213-d86d5581-4be7-4085-a20e-d5d20556dae0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjc0MDcsIm5iZiI6MTcxOTE2NzEwNywicGF0aCI6Ii80NDUzMTA2OC8zNDIxMDYyMTMtZDg2ZDU1ODEtNGJlNy00MDg1LWEyMGUtZDVkMjA1NTZkYWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE4MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZDZiMzQxZTQ4NDZjMDUxZWU0M2M3YTEzNDJlZGI0ZjhmOGIxZGMxNWI5YTkwYmYxNzFjMDdiZjZkNDJlMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jlhZiTLMma8nXsAq7AHlicGFSatbpcxjjKx80wwZSA0) I tried to install manually [WebView2 (Evergreen installer)](https://developer.microsoft.com/fr-fr/microsoft-edge/webview2/?form=MA13LH#download-section) but still doesn't work.

I reinstalled WebView2 using the following command, and it seems to work now (the WebView2 executable was already present) :
```sh
WINEPREFIX=/home/user/.fusion360/wineprefixes/default wine 'C:\Users\user\Downloads\WebView2installer.exe'
```

**Comment by NoFr1ends** [comment]
I've installed Chrome as a normal deb and selected as the default browser, but for me Fusion still locks up as soon as I press on the signin button.

**Comment by juangomes376** [comment]
I installed it via "bottles" and I'm having trouble logging in. I installed everything, including the dependencies. It opens the browser, but after logging in it doesn't go back to fusion and gets stuck. Has anyone had this problem or can help me?
![Capture d’écran du 2024-07-24 00-34-13](https://github.com/user-attachments/assets/792e6708-1faa-449d-aa30-aef857f8f3eb)

**Comment by cryinkfly** [comment]
Please check this issue: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/434#issuecomment-2255881002

**Comment by cryinkfly** [comment]
Check the newest alpha version of the installer.
