### ISSUE TITLE
Update checker is completely non functional

### ISSUE THREAD

**Issue by spusuf** [cryinkfly/Autodesk-Fusion-360-for-Linux#430]
On launch the script asks if you would like to check for updates, if you press yes it says an update is found and you can press yes to update! Except there isnt an update. I had my ethernet cable unplugged from my dock. After wondering why everything else wasnt working but finding the issue was hardware, I replicated the situation to test the update checker and sure enough the update script defaults to "an update is found" even when there is no internet connection.

If the update script is non functional then why is there the two button press dialogs necessary to launch Fusion 360. I would personally prefer an update.sh file to use in case anything stops working, OR a part of the launch script that checks for updates in the background and notifies if there is an update, keeping the time to launch Fusion minimal.

The launch experience should be as similar to using it natively as possible, just launch it from your DE, fusion splash screen, (update notification if necessary), then software opens, no additional interaction needed.

**Comment by cryinkfly** [comment]
#413
