### ISSUE TITLE
cannot download installation file (403 error)

### ISSUE THREAD

**Issue by zmindless** [cryinkfly/Autodesk-Fusion-360-for-Linux#435]
**Describe the bug**
when executing:
wget https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Admin%20Install.exe -O Fusion360installer.exe

I get:
--2024-07-11 11:34:34--  https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Admin%20Install.exe
Resolving dl.appstreaming.autodesk.com (dl.appstreaming.autodesk.com)... 23.205.191.81
Connecting to dl.appstreaming.autodesk.com (dl.appstreaming.autodesk.com)|23.205.191.81|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://www.appstreaming.autodesk.com/message/NotFound [following]
--2024-07-11 11:34:37--  http://www.appstreaming.autodesk.com/message/NotFound
Resolving www.appstreaming.autodesk.com (www.appstreaming.autodesk.com)... 54.152.5.152, 52.207.41.219
Connecting to www.appstreaming.autodesk.com (www.appstreaming.autodesk.com)|54.152.5.152|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.autodesk.com:80/products/fusion-360/appstream [following]
--2024-07-11 11:34:38--  http://www.autodesk.com/products/fusion-360/appstream
Resolving www.autodesk.com (www.autodesk.com)... 104.96.129.176, 2a02:26f0:11a:480::4516, 2a02:26f0:11a:483::4516
Connecting to www.autodesk.com (www.autodesk.com)|104.96.129.176|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-07-11 11:34:38 ERROR 403: Forbidden.

**To Reproduce**
run wget command

**Expected behavior**
file downloaded

**Screenshots**

**Desktop (please complete the following information):**

**Comment by zmindless** [comment]
got it from here:
https://dl.appstreaming.autodesk.com/production/installers/Fusion%20Admin%20Install.exe?_ga=2.81640468.2034104390.1720686001-2017324359.1720686128

**Comment by Tony763** [comment]
Hi @zmindless there was change in naming, check #380 .
