### ISSUE TITLE
Stage does not render correctly above certain sized window

### ISSUE THREAD

**Issue by Sidesharks** [cryinkfly/Autodesk-Fusion-360-for-Linux#437]
**Describe the bug**
Stage does not render correctly with VEGA10 GPU

**To Reproduce**
1. Launch fusion

**Expected behavior**
Stage to render

**Screenshots**

![image](https://github.com/user-attachments/assets/aa5c2493-7cf6-47a7-a54e-4977398c1ea7)

**Desktop (please complete the following information):**
- VEGA56 + Mesa 24.1.0
- Fedora Linux
- KDE Plasma 5

**Additional context**
Due to issue #434 I am using wine-9.0, I have a feeling this might be problematic but am unsure why.
Seems to be very similar to  #128 but in this instance no amdgpu-pro driver is being used.
I have tried removing and then reinstalling drivers and making sure drivers are updated.

Apologies if this is a simple fix/ is very obvious! I'm trying to transition to Linux and am still in the process of learning!

**Relevent Info**
```
$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD Radeon RX Vega (radeonsi, vega10, LLVM 17.0.6, DRM 3.57, 6.8.12-200.fsync.fc39.x86_64) (0x687f)
    Version: 24.1.0
    Accelerated: yes
    Video memory: 8192MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 7296 MB, largest block: 7296 MB
    VBO free aux. memory - total: 7767 MB, largest block: 7767 MB
    Texture free memory - total: 7296 MB, largest block: 7296 MB
    Texture free aux. memory - total: 7767 MB, largest block: 7767 MB
    Renderbuffer free memory - total: 7296 MB, largest block: 7296 MB
    Renderbuffer free aux. memory - total: 7767 MB, largest block: 7767 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 16133 MB
    Currently available dedicated video memory: 7296 MB
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon RX Vega (radeonsi, vega10, LLVM 17.0.6, DRM 3.57, 6.8.12-200.fsync.fc39.x86_64)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.1.0
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.1.0
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 24.1.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by Ameb** [comment]
Try to modify the render engine of Fusion360 by locating the `NMachineSpecificOptions.xml` file and modifying the `driverOptionId` property.
Search those terms (the xml filename, the property) on other issues to help locating them. Can't do for you right now.

**Comment by Sidesharks** [comment]
> Try to modify the render engine of Fusion360 by locating the `NMachineSpecificOptions.xml` file and modifying the `driverOptionId` property. I think Fusion is trying to use Dx10/11 and OpenGL works better. Search those terms (the xml filename, the property) on other issues to help locating them. Can't do for you right now.

Thanks for the info! 

I've edited the `NMachineSpecificOptions.xml` file so that `driverOptionId = VirtualDeviceGLcore` (#21 helped a lot for this information) this makes the program more responsive but unfortunately the stage is still black, but can be seen when going full screen -> windowed but then when the window is used the stage returns to black.

When I get time I will try again on a fresh OS and feed back, I will also try to dig up an old gpu to test.

**Comment by Sidesharks** [comment]
Ok after some trial and error -  it works!

But only when windowed in a small window (looks like below 720 on my 1080 monitor) - I'm still looking to see if this is an issue with programs in wine in general but it is for now usable!

**Comment by Sidesharks** [comment]
Fresh Install of Nobara 39 - No change in issue
New GPU (old R7 260x) - No change in issue
Changing API - no change in issues but in graphics diagnostic driver is reported as 'Unknown' in openGL whereas correct driver is given in directX

More details on Issue:
Window can be stretched horizontally and still render correctly, stretching over  1/2 vertically causes stage to stop rendering.

Half solution - Setting my monitor to 1280x720 allows me to have fusion work correctly in full screen, seems to be some resolution limit bug?

**Comment by Sidesharks** [comment]
I have found a solution!

All of these issues are solved when in an x11 session rather than a Wayland session! - responsiveness is also greatly improved!
