### ISSUE TITLE
Missing Data Panel

### ISSUE THREAD

**Issue by CawHaven** [cryinkfly/Autodesk-Fusion-360-for-Linux#439]
**Describe the bug**
Data panel is missing

**To Reproduce**
After downloading a fresh install of fusion 360 via bottle.
Then adding a shortcut for identity manager to sign in.
It opens but the data panel is missing.

**Screenshots**
![2024-07-26_13-50](https://github.com/user-attachments/assets/a6ad63f1-fa00-4652-8659-f9608dbbfc0c)

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360
- Graphics card model + Graphics card driver: GA107M [GeForce RTX 3050 Ti Mobile]
- Operating system: POPOS
- Desktop environment: KDE Plasma
- DXVK-2.4

**Additional context**
Everything else is a default setup on bottles.

**Comment by thisiscam** [comment]
Same here. I suspect it's a cloud service issue because the wine application also crashes if you try to save a design into the cloud.

**Comment by thisiscam** [comment]
I followed this comment https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues?q=loading+additional+modules#issuecomment-2138799923 and the data panel appears! Not sure how long this will last though

**Comment by cryinkfly** [comment]
With the OpenGL driver option in Autodesk Fusion the panel comes back. And you must do this step: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/421#issuecomment-2138799923
