### ISSUE TITLE
Installer script installed wine-staging although I selected the non-staging one.

### ISSUE THREAD

**Issue by tomcass240** [cryinkfly/Autodesk-Fusion-360-for-Linux#442]
When you get to the point where it asks what version of wine you want to use, there was 2 options, wine staging and just normal wine. I selected normal wine which it recognised as being already installed but then it went on to install wine-staging anyway. Is this supposed to happen?

**Comment by cryinkfly** [comment]
My new script installer (alpha version) detect the wine version and when the correct version exists then continued with the installation of Autodesk Fusion.
