### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by CawHaven** [cryinkfly/Autodesk-Fusion-360-for-Linux#446]
**Describe the bug**
Whenever I try to save, Fusion 360 gives 2 errors:
1. Got an unknown exception during persistence Protein Assets to a local disk!
2. DesignConfigurationTableBlobSerializer::doSave - createZipPartFromFile failed!

**To Reproduce**
1. Use install.sh script to install Fusion 360
2. Import a component to a file
3. Attempt to save the file

**Screenshots**
![2024-07-31_01-45](https://github.com/user-attachments/assets/bc43e87a-7587-4ecd-aeeb-ce1ca497d704)

**Desktop (please complete the following 
- Version number of Autodesk Fusion 360: Recent Install
- Graphics card model + Graphics card driver: GA107M [GeForce RTX 3050 Ti Mobile]
- Operating system: POPOS 22.04 LTS
- Desktop environment: KDE
- DXVK-(Unknown): Recent Install via script

**Comment by caiobrg** [comment]
https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/362#issuecomment-1889835832 this solved it for me

**Comment by ThirtyThreeB** [comment]
I have this same issue and the linked solution did not work for me.  Looking to see if there's a way to set the directory in which files are saved.  Maybe the path is currently incorrect?  Seems crazy that the suggested solutions in the other thread relate to changing totally unrelated settings?

**Comment by cryinkfly** [comment]
With the latest Wine and Autodesk Fusion version I do not have this problem.
