### ISSUE TITLE
QtWebEngine crashes and data panel not working

### ISSUE THREAD

**Issue by Mootfrost777** [cryinkfly/Autodesk-Fusion-360-for-Linux#449]
**Describe the bug**
When launching f360  it throws 3 errors about QtWebEngine.exe crashed. Data panel and other feauther that require internet not working
**To Reproduce**
1. Install f360 using installation script
2. Edit hosts file like in documentation
3. Launch f360

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/e50af071-6764-4840-b277-1295deb4506f)

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360 - about section not working. One from release 2fcb7a6.
- NVIDIA GeForce GTX 1050 Ti + 555.58.02 nvidia drivers
- Arch linux
- KDE plasma 6.1.3
**Additional context**

Error details:
https://pastebin.com/zbF1xRtS

**Comment by Daniel-Chin** [comment]
Same issue here. It throws that same error ("qtWebEngineProcess.exe has encountered a serious problem") about 10 times within 1 minute after launching. 

- Autodesk-Fusion-360-for-Linux-7.6.12
- Garuda Linux x86_64
- Kernel: 6.11.1-zen1-1-zen
- KDE Plasma 6.1.5, KWin (Wayland)
