### ISSUE TITLE
Unable to export files

### ISSUE THREAD

**Issue by ThirtyThreeB** [cryinkfly/Autodesk-Fusion-360-for-Linux#450]
As in [218](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/218)  I am unable to access a file that has been exported.
In this case the workflow is to export a .3mf and then import it into PrusaSlicer.  I am now able to successfully save files, thanks to several suggestions made here, however they do not appear in the file tree as suggested in the linked issue.

**To Reproduce**
Choose 'export' in the file dropdown
Export a file as type 3MF files to C:/users/$USER/favorites via the export popup
 

**Expected behavior**
I expect top be able to browse to `/home/gabriel/.wine/drive_c/users/gabriel/Favorites` and see the file that was exported.

Here I see the file has been exported, in the wine file system.
![image](https://github.com/user-attachments/assets/9ed567de-af3d-4dd2-9bbd-aed94abb14ef)

But accessing that location is empty
![image](https://github.com/user-attachments/assets/faa0c0c2-052b-4e79-8e53-b615a4faa073)

Ubuntu 22.04
Fusion 2.0.19725 x86_64
NV137 / Mesa Intel® UHD Graphics 630 (CFL GT2)
Ubuntu 22.04
gnome 42.9
- DXVK- or OpenGL-Mode  -not sure

I understand there is some sandboxing around wine writing files to the host system, however I need to be able to access a file created in fusion from the separate slicer application.

**Comment by cryinkfly** [comment]
Autodesk Fusion runs a sandbox mode and so you must go in to your installed wineprefix! But I will create a Import/Export directory for the future.
