### ISSUE TITLE
Ubuntu 24.04 not an option

### ISSUE THREAD

**Issue by nomike** [cryinkfly/Autodesk-Fusion-360-for-Linux#451]
**Describe the bug**
The installer asks for the linux version to be able to install additional requirements.

I'm running Ubuntu 24.04 LTS. which is not an option. As it´s the current LTS release, I believe it should be.

Probably the logic behind could be the same as for Ubuntu 23.10. With a new LTS release they typically don't change that much from the previous non-LTS one.

**Comment by cryinkfly** [comment]
You can use my alpha version: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux#%EF%B8%8F-getting-started
