### ISSUE TITLE
Not installing on Linux Mint 22

### ISSUE THREAD

**Issue by SuperPi911** [cryinkfly/Autodesk-Fusion-360-for-Linux#453]
rares@msi-TOMAHAWK-X670E:~ curl -L https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/setup/autodesk_fusion_installer_x86-64.sh -o "autodesk_fusion_installer_x86-64.sh" && chmod +x autodesk_fusion_installer_x86-64.sh && ./autodesk_fusion_installer_x86-64.sh --install --default
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 60218  100 60218    0     0   168k      0 --:--:-- --:--:-- --:--:--  168k
grep: /etc/upstream-release: Is a directory
grep: /etc/upstream-release: Is a directory
Checking for required package: curl ...
Checking for required package: lsb-release ...
The required package (lsb-release) is not installed!
The installer will install the required packages for the installation!
Missing package: lsb-release
The installer doesn't support your current Linux distribution  at this time!
The installer has been terminated!
rares@msi-TOMAHAWK-X670E:~

![Screenshot from 2024-08-06 17-39-40](https://github.com/user-attachments/assets/1efeea92-f34c-4558-b172-526f6215f652)

**Comment by cryinkfly** [comment]
Solved now!

**Comment by SuperPi911** [comment]
is just the same after the "update"
![Screenshot from 2024-08-06 18-54-21](https://github.com/user-attachments/assets/5346e81e-9fb9-449f-8679-a9a4b852be9e)
