### ISSUE TITLE
Still not installing on Linux Mint 22

### ISSUE THREAD

**Issue by SuperPi911** [cryinkfly/Autodesk-Fusion-360-for-Linux#454]
Still not installing on Linux Mint 22 after the update 
![355518599-5346e81e-9fb9-449f-8679-a9a4b852be9e](https://github.com/user-attachments/assets/ba92f5a5-5d2d-400b-9403-e52917107cfd)

**Comment by cryinkfly** [comment]
Please check again. 😅 I must change the letters to lowercase and add other code. Sorry :100:
