### ISSUE TITLE
The total VRAM (Video RAM) is not greater than 1 GByte (7.43 GByte)

### ISSUE THREAD

**Issue by aapolipponen** [cryinkfly/Autodesk-Fusion-360-for-Linux#455]
**Describe the bug**

When installing Fusion trough the script, the install goes smootly until the script doesn't compare the VRAM and the storage of the computer right. The script shows that the computer has 7.43 Gigabytes of VRAM but the script still alerts the user of insufficient VRAM. After that the script also doesn't find the storage of the device and errors out completely.

**To Reproduce**
Kernel: Linux 6.9.12-200.fc40.x86_64

Install the [autodesk_fusion_installer_x86-64.sh](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/blob/main/files/setup/autodesk_fusion_installer_x86-64.sh) inside of files/setup/

Run the script in the Downloads folder (adding execution permissions first

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360
Not sure. The latest one? Probably doesn't matter since Fusion isn't installed yet.
- Graphics card model + Graphics card driver (Version number)

I'm on a Thinkpad E14 (Gen 3 I think). The CPU is i3-1215U and has integrated graphics (Intel UHD Graphics @ 1.10 GHz)

[aapo@aapon-thinkpad-e14 Lataukset]$ lspci -n -n -k | grep -A 2 -e VGA -e 3D
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-UP3 GT1 [UHD Graphics] [8086:46b3] (rev 0c)
	Subsystem: Lenovo Device [17aa:50a0]
	Kernel driver in use: i915
[aapo@aapon-thinkpad-e14 Lataukset]$ glxinfo | grep -e OpenGL.vendor -e OpenGL.renderer
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) Graphics (ADL GT2)
[aapo@aapon-thinkpad-e14 Lataukset]$ 

- Operating system (OpenSUSE Leap 15.3, Fedora 34, ...)
Fedora 40. I have installed the version of the script which has support for Fedora 40.
- Desktop environment (XFCE 4.16, Gnome 40, ...)
GNOME 46.3.1
- DXVK- or OpenGL-Mode
[aapo@aapon-thinkpad-e14 Lataukset]$ glxinfo | grep OpenGL
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) Graphics (ADL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.1.5
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.1.5
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 24.1.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

**Additional context**

Logs after running ./autodesk_fusion_installer_x86-64.sh --install:

Update completed.
Starting the installation process ...
Linux distribution: fedora 40
Selected option: --install
Selected directory: /root/.autodesk_fusion
Selected extensions: 
The total RAM (Random Access Memory) is greater than 4 GByte (7.43 GByte) and Autodesk Fusion will run more stable later!
Checking the GPU driver for the installer ...
The Intel GPU driver is installed!
The OpenGL GPU driver will be used for the installation!
./autodesk_fusion_installer_x86-64.sh: line 374: [: : integer expression expected
The total VRAM (Video RAM) is not greater than 1 GByte (7.43 GByte) and Autodesk Fusion may run unstable later with insufficient VRAM memory!
Are you sure you want to continue with the installation? (y/n)y
./autodesk_fusion_installer_x86-64.sh: line 380: ...: command not found
df: /root/.autodesk_fusion: No such file or directory
The free disk memory size is: 
There is not enough disk free memory to continue installing Fusion on your system!
Make more space in your selected disk or select a different hard drive.
The installer has been terminated!

**Comment by cryinkfly** [comment]
@aapolipponen THX for your help! :+1: 

I have solved the bugs now: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/commit/8e3d45f842d0e71887097f7c850310adce939979
