### ISSUE TITLE
Unable to log into Autodesk

### ISSUE THREAD

**Issue by Corvuscroft** [cryinkfly/Autodesk-Fusion-360-for-Linux#456]
Ive tried to install via the terminal and also via the flat pack. I run into the same problem. It starts up fine and then I get a pop up0x006fffdb271e31 qt6webenginecore+0x3d81e31: int3
Modules:
Module  Address                                 Debug info      Name (153 modules)
PE-Wine         785c0000-        78bae000       Deferred        opengl32
PE             140000000-       1400ac000       --none--        qtwebengineprocess
PE-Wine        180000000-       180002000       Deferred        usp10
PE-Wine     6fffd6760000-    6fffd67b8000       Deferred        winex11
PE-Wine     6fffd67d0000-    6fffd6817000       Deferred        msv1_0
PE-Wine     6fffd6830000-    6fffd6864000       Deferred        kerberos
PE-Wine     6fffd69e0000-    6fffd6a01000       Deferred        dhcpcsvc
PE          6fffd6a20000-    6fffd6a97000       Deferred        qt6positioning
PE          6fffd6ab0000-    6fffd6aed000       Deferred        qt6webchannel
PE-Wine     6fffd6b00000-    6fffd6b18000       Deferred        winusb
PE-Wine     6fffd6b30000-    6fffd6b65000       Deferred        hid
PE-Wine     6fffd6b80000-    6fffd6be4000       Deferred        dxva2
PE-Wine     6fffd6c00000-    6fffd6c1d000       Deferred        bluetoothapis
PE-Wine     6fffd6c30000-    6fffd6c42000       Deferred        bthprops.cpl
PE-Wine     6fffd6c60000-    6fffd6df8000       Deferred        d3d9
PE-Wine     6fffd6e10000-    6fffd6e42000       Deferred        wtsapi32
PE-Wine     6fffd6e60000-    6fffd70a3000       Deferred        wininet
PE-Wine     6fffd70c0000-    6fffd7349000       Deferred        urlmon
PE-Wine     6fffd7360000-    6fffd7389000       Deferred        ncrypt
PE-Wine     6fffd73a0000-    6fffd7417000       Deferred        propsys
PE-Wine     6fffd7430000-    6fffd7457000       Deferred        powrprof
PE-Wine     6fffd7470000-    6fffd748e000       Deferred        cfgmgr32
PE-Wine     6fffd74a0000-    6fffd74d6000       Deferred        pdh
PE          6fffd74f0000-    6fffdfc74000       --none--        qt6webenginecore
PE-Wine     6fffdfc90000-    6fffdfcc1000       Deferred        compstui
PE-Wine     6fffdfce0000-    6fffdfda9000       Deferred        winspool
PE-Wine     6fffdfdc0000-    6fffe032a000       Deferred        comctl32
PE-Wine     6fffe0340000-    6fffe05a1000       Deferred        comdlg32
PE          6fffe0920000-    6fffe0af8000       Deferred        qt6opengl
PE          6fffe0b10000-    6fffe0f7c000       Deferred        qt6qml
PE          6fffe0f90000-    6fffe1038000       Deferred        qt6qmlmodels
PE          6fffe1050000-    6fffe1545000       Deferred        qt6quick
PE-Wine     6ffff08f0000-    6ffff0be0000       Deferred        dbghelp
PE          6ffff2270000-    6ffff23c0000       Deferred        qt6network
PE-Wine     6ffff5180000-    6ffff5244000       Deferred        uxtheme
PE-Wine     6ffff5260000-    6ffff5284000       Deferred        dwmapi
PE-Wine     6ffff5880000-    6ffff5893000       Deferred        msvcp140_2
PE-Wine     6ffff58b0000-    6ffff5bd3000       Deferred        dwrite
PE-Wine     6ffff5bf0000-    6ffff7151000       Deferred        wined3d
PE-Wine     6ffff7170000-    6ffff72bb000       Deferred        dxgi
PE-Wine     6ffff72d0000-    6ffff75c0000       Deferred        d3d11
PE          6ffff75d0000-    6ffff7d94000       Deferred        qt6gui
PE-Wine     6ffff7db0000-    6ffff7dcc000       Deferred        msvcp140_1
PE-Wine     6ffff7de0000-    6ffff7e59000       Deferred        msacm32
PE-Wine     6ffff7e70000-    6ffff8020000       Deferred        winmm
PE-Wine     6ffff8030000-    6ffff80d9000       Deferred        netapi32
PE-Wine     6ffff80f0000-    6ffff810d000       Deferred        authz
PE-Wine     6ffff8120000-    6ffff8183000       Deferred        mpr
PE          6ffff81a0000-    6ffff872c000       Deferred        qt6core
PE-Wine     6ffff9a20000-    6ffff9de9000       Deferred        crypt32
PE-Wine     6ffff9e00000-    6ffff9eb3000       Deferred        secur32
PE-Wine     6ffffa570000-    6ffffa5d0000       Deferred        bcrypt
PE-Wine     6ffffa5e0000-    6ffffa5ff000       Deferred        version
PE-Wine     6ffffabf0000-    6ffffac26000       Deferred        vcruntime140_1
PE-Wine     6ffffac40000-    6ffffac59000       Deferred        vcruntime140
PE          6ffffac70000-    6ffffacfe000       Deferred        msvcp140
PE-Wine     6ffffb970000-    6ffffc71a000       Deferred        shell32
PE-Wine     6ffffc730000-    6ffffc781000       Deferred        shcore
PE-Wine     6ffffc7a0000-    6ffffc8b1000       Deferred        shlwapi
PE-Wine     6ffffc8d0000-    6ffffc8f4000       Deferred        nsi
PE-Wine     6ffffc910000-    6ffffc95c000       Deferred        dnsapi
PE-Wine     6ffffc970000-    6ffffca00000       Deferred        iphlpapi
PE-Wine     6ffffcc60000-    6ffffcfca000       Deferred        oleaut32
PE-Wine     6ffffcfe0000-    6ffffd027000       Deferred        jsproxy
PE-Wine     6ffffd040000-    6ffffd17c000       Deferred        winhttp
PE-Wine     6ffffd190000-    6ffffd1db000       Deferred        coml2
PE-Wine     6ffffd1f0000-    6ffffd379000       Deferred        combase
PE-Wine     6ffffd390000-    6ffffd74a000       Deferred        ole32
PE-Wine     6ffffd840000-    6ffffd8bf000       Deferred        imm32
PE-Wine     6ffffd8d0000-    6ffffd90e000       Deferred        win32u
PE-Wine     6ffffd920000-    6ffffdbeb000       Deferred        gdi32
PE-Wine     6ffffdc00000-    6ffffe1d8000       Deferred        user32
PE-Wine     6ffffe500000-    6ffffe52d000       Deferred        userenv
PE-Wine     6ffffe540000-    6ffffe723000       Deferred        setupapi
PE-Wine     6ffffe740000-    6ffffe9c2000       Deferred        rpcrt4
PE-Wine     6ffffe9e0000-    6ffffea90000       Deferred        ws2_32
PE-Wine     6ffffeaa0000-    6ffffee9a000       Deferred        ucrtbase
PE-Wine     6ffffeeb0000-    6ffffef38000       Deferred        sechost
PE-Wine     6ffffef50000-    6fffff2bd000       Deferred        msvcrt
PE-Wine     6fffff2d0000-    6fffff402000       Deferred        advapi32
PE-Wine     6fffff420000-    6fffffa60000       Deferred        kernelbase
PE-Wine     6fffffa70000-    6fffffc2d000       Dwarf-4         kernel32
PE-Wine     6fffffc40000-    6ffffffe8000       Dwarf-4         ntdll
ELF         7fea86b9e000-    7fea86ba4000       Deferred        dwrite.so
ELF         7fea86ba4000-    7fea86cd5000       Deferred        opengl32.so
ELF         7fea86cd5000-    7fea86cda000       Deferred        msv1_0.so
ELF         7fea86cda000-    7fea86ce0000       Deferred        netapi32.so
ELF         7fea86ce0000-    7fea86ce9000       Deferred        kerberos.so
ELF         7fea86ce9000-    7fea86cf4000       Deferred        secur32.so
ELF         7fea86cf4000-    7fea86cf9000       Deferred        dnsapi.so
ELF         7fea86cf9000-    7fea86d00000       Deferred        crypt32.so
ELF         7fea86d00000-    7fea86d26000       Deferred        libgpg-error.so.0
ELF         7fea86d26000-    7fea86e64000       Deferred        libgcrypt.so.20
ELF         7fea86e64000-    7fea86e6f000       Deferred        libcap.so.2
ELF         7fea86e6f000-    7fea86e8f000       Deferred        liblz4.so.1
ELF         7fea86e8f000-    7fea86f5e000       Deferred        libzstd.so.1
ELF         7fea86f5e000-    7fea86f6b000       Deferred        libffi.so.7
ELF         7fea86f6b000-    7fea87032000       Deferred        libsystemd.so.0
ELF         7fea87032000-    7fea87046000       Deferred        libresolv.so.2
ELF         7fea87046000-    7fea8704d000       Deferred        libkeyutils.so.1
ELF         7fea8704d000-    7fea870cf000       Deferred        libgmp.so.10
ELF         7fea870cf000-    7fea87117000       Deferred        libhogweed.so.6
ELF         7fea87117000-    7fea8715d000       Deferred        libnettle.so.8
ELF         7fea8715d000-    7fea87175000       Deferred        libtasn1.so.6
ELF         7fea87175000-    7fea8731f000       Deferred        libunistring.so.2
ELF         7fea8731f000-    7fea87340000       Deferred        libidn2.so.0
ELF         7fea87340000-    7fea874f2000       Deferred        libp11-kit.so.0
ELF         7fea874f2000-    7fea87540000       Deferred        libdbus-1.so.3
ELF         7fea87540000-    7fea8754e000       Deferred        libkrb5support.so.0
ELF         7fea8754e000-    7fea87554000       Deferred        libcom_err.so.2
ELF         7fea87554000-    7fea87583000       Deferred        libk5crypto.so.3
ELF         7fea87585000-    7fea87593000       Deferred        bcrypt.so
ELF         7fea87593000-    7fea8759a000       Deferred        ws2_32.so
ELF         7fea8759a000-    7fea87665000       Deferred        libkrb5.so.3
ELF         7fea87665000-    7fea87850000       Deferred        libgnutls.so.30
ELF         7fea87850000-    7fea87864000       Deferred        libavahi-client.so.3
ELF         7fea87864000-    7fea87872000       Deferred        libavahi-common.so.3
ELF         7fea87872000-    7fea878c6000       Deferred        libgssapi_krb5.so.2
ELF         7fea878c6000-    7fea87964000       Deferred        libcups.so.2
ELF         7fea87964000-    7fea8796a000       Deferred        winspool.so
ELF         7fea8798e000-    7fea87996000       Deferred        libxfixes.so.3
ELF         7fea87996000-    7fea879a2000       Deferred        libxcursor.so.1
ELF         7fea879a2000-    7fea879b6000       Deferred        libxi.so.6
ELF         7fea879b6000-    7fea879c3000       Deferred        libxrandr.so.2
ELF         7fea879c3000-    7fea879d0000       Deferred        libxrender.so.1
ELF         7fea879d0000-    7fea879dd000       Deferred        libmd.so.0
ELF         7fea879dd000-    7fea879f5000       Deferred        libbsd.so.0
ELF         7fea879fb000-    7fea87a00000       Deferred        libxcomposite.so.1
ELF         7fea87a00000-    7fea87a07000       Deferred        libxxf86vm.so.1
ELF         7fea87a07000-    7fea87a0c000       Deferred        libxinerama.so.1
ELF         7fea87a0c000-    7fea87a14000       Deferred        libxdmcp.so.6
ELF         7fea87a14000-    7fea87a1a000       Deferred        libxau.so.6
ELF         7fea87a1a000-    7fea87a44000       Deferred        libxcb.so.1
ELF         7fea87a44000-    7fea87b84000       Deferred        libx11.so.6
ELF         7fea87b84000-    7fea87b99000       Deferred        libxext.so.6
ELF         7fea87b99000-    7fea87c19000       Deferred        winex11.so
ELF         7fea87ce7000-    7fea87d18000       Deferred        libexpat.so.1
ELF         7fea87d18000-    7fea87d62000       Deferred        libfontconfig.so.1
ELF         7fea87d62000-    7fea87d85000       Deferred        libbrotlicommon.so.1
ELF         7fea87d85000-    7fea87da1000       Deferred        libz.so.1
ELF         7fea87da1000-    7fea87ddc000       Deferred        libpng16.so.16
ELF         7fea87ddc000-    7fea87ea4000       Deferred        libfreetype.so.6
ELF         7fea87ea4000-    7fea87f8b000       Deferred        libm.so.6
ELF         7fea87f8b000-    7fea87f94000       Deferred        libuuid.so.1
ELF         7fea87f94000-    7fea87fa2000       Deferred        libbrotlidec.so.1
ELF         7fea87fa2000-    7fea88148000       Deferred        win32u.so
ELF         7fea8859f000-    7fea885ca000       Deferred        liblzma.so.5
ELF         7fea885ca000-    7fea885e5000       Deferred        libunwind.so.8
ELF         7fea885e5000-    7fea886a2000       Export          ntdll.so
ELF         7fea886a4000-    7fea888cd000       Deferred        libc.so.6
ELF         7fea888e4000-    7fea888e9000       Deferred        bindtextdomain.so
ELF         7fea888eb000-    7fea88927000       Deferred        ld-linux-x86-64.so.2
ELF         7fea88927000-    7fea8892c000       Deferred        <wine-loader>
Threads:
process  tid      prio    name (all IDs are in hex)
00000038 services.exe
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	00000070    0     wine_rpcrt4_io
	00000084    0     wine_rpcrt4_io
	000000a4    0     wine_rpcrt4_io
	000000b4    0     wine_rpcrt4_io
	000000ec    0     wine_rpcrt4_io
	00000104    0     wine_rpcrt4_io
	00000120    0     
	0000012c    0     wine_rpcrt4_io
0000005c svchost.exe
	00000060    0     
	00000074    0     
	00000078    0     wine_sechost_service
00000064 MicrosoftEdgeUpdate.exe
	00000068    0     
	000000b8    0     wine_threadpool_worker
	000000bc    0     wine_threadpool_waitqueue
	000000c0    0     wine_threadpool_timer_queue
	000000c4    0     
0000007c winedevice.exe
	00000080    0     
	00000088    0     
	0000008c    0     wine_sechost_service
	00000090    0     
	00000094    0     
	00000098    0     
	00000118    0     
	0000011c    0     
0000009c winedevice.exe
	000000a0    0     
	000000a8    0     
	000000ac    0     wine_sechost_service
	000000b0    0     
	000000c8    0     
	000000cc    0     
	000000d0    0     
	000000d4    0     
	000000dc    0     
	000000e8    0     
000000e0 plugplay.exe
	000000e4    0     
	000000f0    0     
	000000f4    0     wine_sechost_service
	000000f8    0     wine_rpcrt4_server
	000002dc    0     wine_rpcrt4_io
	000002e4    0     wine_threadpool_worker
	000005fc    0     wine_rpcrt4_io
	00000604    0     wine_threadpool_worker
000000fc svchost.exe
	00000100    0     
	00000108    0     
	0000010c    0     wine_sechost_service
	00000110    0     
	0000014c    0     wine_rpcrt4_server
	00000150    0     wine_rpcrt4_server
00000124 rpcss.exe
	00000128    0     
	00000130    0     
	00000134    0     wine_sechost_service
	00000138    0     wine_rpcrt4_server
	0000013c    0     wine_rpcrt4_server
	00000188    0     wine_rpcrt4_io
	000006d4    0     wine_rpcrt4_io
0000015c start.exe
	00000160    0     
00000164 FusionLauncher.exe
	00000168    0     
0000016c Fusion360.exe
	00000170    0     CrBrowserMain
	0000018c    0     
	00000190    0     
	00000194    0     
	00000198    0     
	0000019c    0     
	000001a0    0     
	000001a4    0     
	000001a8    0     
	000001ac    0     
	000001b0    0     
	000001b4    0     
	000001b8    0     
	000001bc    0     
	000001c0    0     
	000001c4    0     
	000001c8    0     
	000001cc    0     
	000001d0    0     
	000001d4    0     
	000001d8    0     
	000001dc    0     
	000001e0    0     
	000001e4    0     
	000001e8    0     
	000001ec    0     
	000001f0    0     
	000001f4    0     
	000001f8    0     
	000001fc    0     
	00000200    0     
	00000208    0     
	00000228    0     
	00000234    0     
	00000268    0     
	00000288    0     BrokerEvent
	0000029c   -2     ThreadPoolSingleThreadCOMSTASharedBackgroundBlocking0
	000002a0    0     wine_threadpool_worker
	000002a4    0     wine_threadpool_waitqueue
	000002a8    0     ThreadPoolSingleThreadCOMSTASharedForeground1
	000002d4    0     wine_sechost_device_notify
	0000034c    0     
	00000350    0     
	00000378    0     
	0000037c    0     NetworkService
	00000384    0     ThreadPoolSingleThreadForegroundBlocking2
	00000390    0     wine_rpcrt4_server
	0000042c    0     
	00000434    0     
	00000438    0     
	0000043c    0     
	00000440    0     
	0000045c    0     
	00000460   -2     ThreadPoolSingleThreadSharedBackgroundBlocking3
	00000470    0     ThreadPoolSingleThreadCOMSTASharedForegroundBlocking4
00000174 explorer.exe
	00000178    0     
	0000017c    0     
	00000180    0     wine_explorer_display_settings_restorer
	00000184    0     wine_rpcrt4_server
0000022c adexmtsv.exe
	00000230    0     
	00000240    0     
	00000244    0     
00000238 conhost.exe
	0000023c    0     
00000498 start.exe
	0000049c    0     
000004a0 FusionLauncher.exe
	000004a4    0     
000004a8 Fusion360.exe
	000004ac    0     CrBrowserMain
	000004b0    0     
	000004b4    0     
	000004b8    0     
	000004bc    0     
	000004c0    0     
	000004c4    0     
	000004c8    0     
	000004cc    0     
	000004d0    0     
	000004d4    0     
	000004d8    0     
	000004dc    0     
	000004e0    0     
	000004e4    0     
	000004e8    0     
	000004ec    0     
	000004f0    0     
	000004f4    0     
	000004f8    0     
	000004fc    0     
	00000500    0     
	00000504    0     
	00000508    0     
	0000050c    0     
	00000510    0     
	00000514    0     
	00000518    0     
	0000051c    0     
	00000520    0     
	00000524    0     
	00000528    0     
	0000052c    0     
	00000530    0     
	00000534   15     
	00000538    0     
	0000054c    0     
	00000558    0     
	00000570    0     
	00000574    0     
	00000578    0     
	0000057c    0     
	00000584    0     
	00000598    0     
	000005a0    0     
	000005a4    0     BrokerEvent
	000005a8    0     ThreadPoolServiceThread
	000005ac    0     ThreadPoolForegroundWorker
	000005b0   -2     ThreadPoolBackgroundWorker
	000005b4    0     Chrome_IOThread
	000005b8   -2     ThreadPoolSingleThreadCOMSTASharedBackgroundBlocking0
	000005bc    0     wine_threadpool_worker
	000005c0    0     wine_threadpool_waitqueue
	000005c4    0     ThreadPoolSingleThreadCOMSTASharedForeground1
	000005c8    0     ThreadPoolForegroundWorker
	000005cc    0     ThreadPoolForegroundWorker
	000005d0    0     ThreadPoolForegroundWorker
	000005d4    0     ThreadPoolForegroundWorker
	000005d8    0     ThreadPoolForegroundWorker
	000005dc    0     ThreadPoolForegroundWorker
	000005e0    1     Chrome_InProcGpuThread
	000005e4    0     Chrome_ChildIOThread
	000005e8    0     CompositorTileWorker1
	000005f0    1     VizCompositorThread
	000005f4    0     wine_sechost_device_notify
	000005f8    0     VideoCaptureThread
	00000600    0     Chrome_DevToolsHandlerThread
	00000608   -1     
	0000060c   -1     
	00000610   -1     
	00000614   -1     
	00000618   -1     
	0000061c   -1     
	00000620   -1     
	00000624   -1     
	00000628   -1     
	0000062c   -1     
	00000630   -1     
	00000634   -1     
	00000638   -1     
	0000063c   -1     
	00000640   -1     
	00000644   -1     
	00000648   -1     
	0000064c   -1     
	00000650   -1     
	00000654   -1     
	00000658   -1     
	0000065c   -1     
	00000660   -1     
	00000664   -1     
	00000668   -1     
	0000066c    0     
	00000670    0     
	00000698    0     
	0000069c    0     NetworkService
	000006a0   -2     ThreadPoolBackgroundWorker
	000006a4    0     ThreadPoolSingleThreadForegroundBlocking2
	000006b0    0     wine_rpcrt4_server
	000006bc    0     
	000006c0    0     
	000006c4    0     
	00000718    0     
	0000071c    0     
	00000748    0     
	0000074c    0     
	00000750    0     MemoryInfra
	00000754   -2     ThreadPoolSingleThreadSharedBackgroundBlocking3
000006a8 (D) C:\Program Files\Autodesk\webdeploy\production\4826aec956713f599d57385857ff62484fd50dd3\QtWebEngineProcess.exe
	000006ac    0 <== CrRendererMain
	000006dc    0     ThreadPoolServiceThread
	000006e0    0     ThreadPoolForegroundWorker
	000006e4   -2     ThreadPoolBackgroundWorker
	000006e8    1     Chrome_ChildIOThread
	000006ec    0     wine_threadpool_worker
	000006f0    0     ThreadPoolForegroundWorker
	000006f4    0     wine_threadpool_waitqueue
	000006f8    0     GpuMemoryThread
	0000070c    0     
000006b4 explorer.exe
	000006b8    0     
	000006c8    0     
	000006cc    0     wine_explorer_display_settings_restorer
	000006d0    0     wine_rpcrt4_server
00000704 conhost.exe
	00000708    0     
System information:
    Wine build: wine-9.14
    Platform: x86_64 (guest: i386)
    Version: Windows 10
    Host system: Linux
    Host version: 5.15.0-117-generic
I'm a noob so if I did something wrong please tell me. I have a personal license with Autodesk. I've run Fusion for several years on windows. I have completely switched to linux about a month ago.

**Comment by cryinkfly** [comment]
It looks like something went wrong during installation or the Qt6WebEngineCore.dll was not patched!

Please take a look here: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/421

**Comment by cryinkfly** [comment]
@Corvuscroft Did you use my latest installer?
