### ISSUE TITLE
VRAM cant be detected because dmesg doesn't have sufficient permissions.

### ISSUE THREAD

**Issue by luunchbox13** [cryinkfly/Autodesk-Fusion-360-for-Linux#457]
I fortunately quickly figured out what the issue is but when running the script at this point:
```
Starting the installation process ...
Linux distribution: arch 
Selected option: --install
Selected directory: /home/silly/.autodesk_fusion
Selected extensions: 
The 'Window not responding' Dialog in GNOME will be disabled for 30 minutes!
The total RAM (Random Access Memory) is greater than 4 GByte (31.2552 GByte) and Autodesk Fusion will run more stable later!
dmesg: read kernel buffer failed: Operation not permitted
Could not determine VRAM size.
```

Here, the installation will fail because dmesg doesn't have permissions on some systems for the user. This isn't hard to fix and after running `sudo sysctl kernel.dmesg_restrict=0` you can run the installer just fine but I think its only appropriate that dmesg is run with elevated privileges by default here so this doesn't happen at all.

**To Reproduce**
1. Run: `sudo sysctl kernel.dmesg_restrict=1`, or run a linux system with this set to 1 by default
2. Run the installer script.
3. Install will fail

- Version number of Autodesk Fusion 360
- Graphics card model + Graphics card driver (Version number): NA
- Operating system (OpenSUSE Leap 15.3, Fedora 34, ...), Arch Linux
- Desktop environment (XFCE 4.16, Gnome 40, ...), Gnome 46
- DXVK- or OpenGL-Mode:

**Comment by cryinkfly** [comment]
So I have changed the code to this:

    GET_VRAM_MEGABYTES=$(glxinfo | grep -i "Video memory" | grep -Eo '[0-9]+MB' | grep -Eo '[0-9]+')

THX for your help! :+1:
