### ISSUE TITLE
error when installing on linux mint 22 (ram -> awk ; autodesk_fusion_launcher.sh: No such file or directory)

### ISSUE THREAD

**Issue by SuperPi911** [cryinkfly/Autodesk-Fusion-360-for-Linux#459]
this is my output , it says i have less than 3 gb of ram , i have 32 , amd ryzen 9 7950x, amd radeon rx 7800xt 

  ic annot paste all the outpu , here is the link to my output https://katb.in/owoyohatayi

**Comment by cryinkfly** [comment]
I read your log file. :+1:

**Comment by cryinkfly** [comment]
Can you check with this command if awk is installed on your system, please?

    awk --version

**Comment by cryinkfly** [comment]
And can you run this little code: [gpu_disk-test.sh.zip](https://github.com/user-attachments/files/16561722/gpu_disk-test.sh.zip)

**Comment by cryinkfly** [comment]
The issue your old wine version exists also here: https://forum.winehq.org/viewtopic.php?t=38703

**Comment by NiklasVoigt** [comment]
exact problem here. 

from @SuperPi911 log:

./autodesk_fusion_installer_x86-64.sh: line 925: /home/rares/.autodesk_fusion/bin/autodesk_fusion_launcher.sh: No such file or directory

there is no file in ~/.autodesk_fusion/bin/ folder

i manually downloaded the launcher using:

$ cd ~/.autodesk_fusion/bin/
$ wget https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/setup/data/autodesk_fusion_launcher.sh
$ chmod +x autodesk_fusion_launcher.sh

and start manually inside bin folder ./autodesk_fusion_launcher.sh

**Comment by cryinkfly** [comment]
@NiklasVoigt But Autodesk Fusion works?

**Comment by NiklasVoigt** [comment]
> @NiklasVoigt But Autodesk Fusion works?

Only with this fix, as i said, the bin folder is empty

**Comment by cryinkfly** [comment]
Okay! :+1: THX ... i check my script!

**Comment by cryinkfly** [comment]
I have found my issue. For example (old):

    curl -L https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/setup/data/autodesk_fusion_launcher.sh -o "$SELECTED_DIRECTORY/bin"

... and here the changed code:

    curl -L https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/setup/data/autodesk_fusion_launcher.sh -o "$SELECTED_DIRECTORY/bin/autodesk_fusion_launcher.sh"

**Comment by cryinkfly** [comment]
@NiklasVoigt Bug is solved in my installation script.

**Comment by NiklasVoigt** [comment]
> @NiklasVoigt Bug is solved in my installation script.
> 
> And do you also have problems with RAM detection, because I'm running Linux Mint 22 (KVM)?

No problems, im on manjaro

**Comment by SuperPi911** [comment]
We mae some progress , fusion opens now ,but no browser is opening to sign in , my output https://katb.in/jiwowujisob

**Comment by cryinkfly** [comment]
Which web browser is installed?

**Comment by SuperPi911** [comment]
> Which web browser is installed?

On my PC Firefox and chrome, on wine nothing

**Comment by cryinkfly** [comment]
This desktop actually takes care of that file:

`    cat >> $HOME/.local/share/applications/adskidmgr-opener.desktop << EOL
[Desktop Entry]
Type=Application
Name=adskidmgr Scheme Handler
Exec=sh -c 'env WINEPREFIX="$SELECTED_DIRECTORY/wineprefixes/default" wine "$(find $SELECTED_DIRECTORY/wineprefixes/default/ -name "AdskIdentityManager.exe" | head -1 | xargs -I '{}' echo {})" "%u"'
StartupNotify=false
MimeType=x-scheme-handler/adskidmgr;
EOL`

... and wine automatically accesses your standard web browser from Linux.

**Comment by SuperPi911** [comment]
> This desktop actually takes care of that file:
> 
> `    cat >> $HOME/.local/share/applications/adskidmgr-opener.desktop << EOL
> [Desktop Entry]
> Type=Application
> Name=adskidmgr Scheme Handler
> Exec=sh -c 'env WINEPREFIX="$SELECTED_DIRECTORY/wineprefixes/default" wine "$(find $SELECTED_DIRECTORY/wineprefixes/default/ -name "AdskIdentityManager.exe" | head -1 | xargs -I '{}' echo {})" "%u"'
> StartupNotify=false
> MimeType=x-scheme-handler/adskidmgr;
> EOL`
> 
> ... and wine automatically accesses your standard web browser from Linux.

But it didn't open any browser to log in

**Comment by cryinkfly** [comment]
Have you set your default web browser in your system? 

For example on XFCE:

![Bildschirmfoto_2024-08-09_18-34-33](https://github.com/user-attachments/assets/94756cbf-0404-4b0f-8a2b-2f9b55475dc4)

**Comment by SuperPi911** [comment]
Yes , chrome , i tried setting firefox , but still nothing , browsers closed , not opening , browsers open no login tab appearing

**Comment by cryinkfly** [comment]
In any case, the problem is not with the script, but rather something is set incorrectly in your system, which unfortunately I cannot understand.

**Comment by NiklasVoigt** [comment]
sidenote: i used chrome today without problems. one time on manjaro and one time on arch

**Comment by cryinkfly** [comment]
I have fixed the installer script! In order for the login to work under Linux Mint, xdg-utils had to be installed.

**Comment by cryinkfly** [comment]
I wish you a nice evening. :100:
