### ISSUE TITLE
POPOS 22 The installer doesn't support your current Linux distribution  at this time!

### ISSUE THREAD

**Issue by PudlatyPL** [cryinkfly/Autodesk-Fusion-360-for-Linux#463]
**Describe the bug**
I have OS: Pop!_OS 22.04 LTS x86_64 and when installing by script:
pudlaty@pop-os:~$ curl -L https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/setup/autodesk_fusion_installer_x86-64.sh -o "autodesk_fusion_installer_x86-64.sh" && chmod +x autodesk_fusion_installer_x86-64.sh && ./autodesk_fusion_installer_x86-64.sh --install --default
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 64793  100 64793    0     0   503k      0 --:--:-- --:--:-- --:--:--  506k
Checking for required package: curl ...
Checking for required package: lsb-release ...
The required package (lsb-release) is not installed!
The installer will install the required packages for the installation!
Missing package: lsb-release
The installer doesn't support your current Linux distribution  at this time!
The installer has been terminated!

**Comment by PudlatyPL** [comment]
pudlaty@pop-os:~$ neofetch
             /////////////                pudlaty@pop-os 
         /////////////////////            -------------- 
      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64 
    //////7676767676*//////////////       Host: B550 AORUS ELITE V2 
   /////76767//7676767//////////////      Kernel: 6.9.3-76060903-generic 
  /////767676///*76767///////////////     Uptime: 5 hours, 5 mins 
 ///////767676///76767.///7676*///////    Packages: 2597 (dpkg), 49 (flatpak) 
/////////767676//76767///767676////////   Shell: bash 5.1.16 
//////////76767676767////76767/////////   Resolution: 1920x1080 
///////////76767676//////7676//////////   DE: GNOME 42.9 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU: AMD Ryzen 7 5700X (16) @ 3.400GH 
    /////767676767676767676767/////       GPU: NVIDIA GeForce RTX 3060 Lite Has 
      ///////////////////////////         Memory: 5474MiB / 15893MiB 
         /////////////////////
             /////////////

**Comment by PudlatyPL** [comment]
pudlaty@pop-os:~$ sudo apt install lsb-release
[sudo] password for pudlaty: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
lsb-release is already the newest version (11.1.0ubuntu4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by cryinkfly** [comment]
Solved!
