### ISSUE TITLE
Ubuntu 24.04 install - winbind, ... issue

### ISSUE THREAD

**Issue by CedericN** [cryinkfly/Autodesk-Fusion-360-for-Linux#464]
**Describe the bug**
After intalling with the script. Fusion looks to be installed and can start up normally. But when logging in (through browser) a red square pops up and it hangs (can only be closed when killing the processes)

**To Reproduce**
1. Run install skript on ubuntu 24.04
2. run fusion executable (or let it automaticallybe started after installation
3. try tp sign in

**Expected behavior**
Default browser opens to sign in

**Screenshots**

**Desktop (please complete the following information):**
- latest (not sure what number)
- intel grafics + nvidia gtx 1060 
- Ubuntu 24.04
- Gnome 40
- OpenGL-Mode (I think)

**Additional context**
I cant check my computer atm but will check and complete once i can

**Comment by cryinkfly** [comment]
@CedericN 

`But when logging in (through browser) a red square pops up and it hangs (can only be closed when killing the processes)`

Which browser? Can you upload images here?

**Comment by cryinkfly** [comment]
The problem was that windbind not installed! The installer was updated for that now.

**Comment by cryinkfly** [comment]
The problem was actually awk!

Because the correct package is gawk and that contains awk.

However, the wrong package name awk skips the other packages and thus the minimum requirements are not installed!

I have adjusted the script again and will test it right away.

**Comment by ejfn** [comment]
Apart from those awk and winbind dependency issues. you need the deb version of the Firefox, the snap version won't work. see [this](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/471#issuecomment-2305281045)

**Comment by cryinkfly** [comment]
How to Install Firefox as DEB on Ubuntu (Not Snap): https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04
