### ISSUE TITLE
ShellExecuteEx failed: File not found.

### ISSUE THREAD

**Issue by aapolipponen** [cryinkfly/Autodesk-Fusion-360-for-Linux#466]
**Describe the bug**

[aapo@aapon-thinkpad-e14 bin]$ ./autodesk_fusion_launcher.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    20  100    20    0     0    288      0 --:--:-- --:--:-- --:--:--   289
Online Build-Version: 2.0.19725
Online Insider-Build-Version: 2.0.19941

002c:fixme:winediag:loader_init wine-staging 9.15 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
wine: could not open working directory L"unix\\home\\aapo\\.autodesk_fusion\\bin\\", starting in the Windows directory.
Application could not be started, or no application associated with the specifie
d file.
ShellExecuteEx failed: File not found.

**To Reproduce**
Install the program on Fedora 40.
Import the Wine 9.15 staging to dnf. ( See Issue #465 )

**Expected behavior**

Fusion should launch but it doesn't

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360
Latest probably
- Graphics card model + Graphics card driver (Version number)
Intel UHD Graphics @ 1.10 GHz [Integrated]
- Operating system (OpenSUSE Leap 15.3, Fedora 34, ...)
Fedora 40
- Desktop environment (XFCE 4.16, Gnome 40, ...)
Gnome 46.4
- DXVK- or OpenGL-Mode
Shouldn't matter

**Additional context**

<details>

<summary>Logs</summary>

Logs from install

Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_7c128405_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
068c:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_f8fa99ae_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
069c:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_b8bff3d7_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
06ac:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_69ffea68_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
06bc:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_783095d8_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
06cc:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_507f6951_22070.reg
Executing w_do_call fakekorean
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
warning: You appear to be using Wine's new wow64 mode. Note that this is EXPERIMENTAL and not yet fully supported. If reporting an issue, be sure to mention this.
------------------------------------------------------
Executing load_fakekorean 
Executing w_do_call sourcehansans
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
warning: You appear to be using Wine's new wow64 mode. Note that this is EXPERIMENTAL and not yet fully supported. If reporting an issue, be sure to mention this.
------------------------------------------------------
sourcehansans already installed, skipping
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
0814:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_cb132002_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
0028:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_c4c42df4_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
0024:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_45ac20d1_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
0118:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_e551b16e_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
0138:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_9b370ecd_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
0144:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_9d072056_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
0148:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_a30b874d_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
0168:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_cf573f83_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
0174:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_79d5898c_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
0178:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_6e1142a5_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
0198:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_64a11c9c_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
00b4:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_0f34a366_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
00bc:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_7bc7a0d0_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
01ac:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_9335c7d8_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
01e4:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_2b9a53c6_22070.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
01d0:err:environ:init_peb starting L"C:\\windows\\syswow64\\regedit.exe" in experimental wow64 mode
Executing wine C:\windows\regedit.exe /S C:\windows\Temp\_register-font-replacements.reg
Executing cp /home/aapo/.autodesk_fusion/wineprefixes/default/dosdevices/c:/windows/temp/_register-font-replacements.reg /tmp/winetricks.2CgNcscz/_reg_698305e4_22070.reg
Executing w_do_call unifont
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
warning: You appear to be using Wine's new wow64 mode. Note that this is EXPERIMENTAL and not yet fully supported. If reporting an issue, be sure to mention this.
------------------------------------------------------
unifont already installed, skipping
Executing cd /home/aapo/.autodesk_fusion/bin
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
warning: You appear to be using Wine's new wow64 mode. Note that this is EXPERIMENTAL and not yet fully supported. If reporting an issue, be sure to mention this.
------------------------------------------------------
Using winetricks 20240105-next - sha256sum: 0650b5b8b5b14818b057d91cb5a353d28d79b0e30f0f40442704011c082ee9a2 with wine-9.15 (Staging) and WINEARCH=win64
Executing w_do_call win11
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
warning: You appear to be using Wine's new wow64 mode. Note that this is EXPERIMENTAL and not yet fully supported. If reporting an issue, be sure to mention this.
------------------------------------------------------
Executing load_win11 
Executing wine winecfg -v win11
wine: could not open working directory L"unix\\home\\aapo\\.autodesk_fusion\\wineprefixes\\default\\", starting in the Windows directory.
wine: could not open working directory L"unix\\home\\aapo\\.autodesk_fusion\\wineprefixes\\default\\", starting in the Windows directory.
------------------------------------------------------
warning: Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/aapo/.autodesk_fusion/wineprefixes/default terminate
------------------------------------------------------
002c:fixme:winediag:loader_init wine-staging 9.15 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
wine: could not open working directory L"unix\\home\\aapo\\.autodesk_fusion\\wineprefixes\\default\\", starting in the Windows directory.
wine: could not open working directory L"unix\\home\\aapo\\.autodesk_fusion\\wineprefixes\\default\\", starting in the Windows directory.
reg: The operation completed successfully
wine: could not open working directory L"unix\\home\\aapo\\.autodesk_fusion\\wineprefixes\\default\\", starting in the Windows directory.
wine: could not open working directory L"unix\\home\\aapo\\.autodesk_fusion\\wineprefixes\\default\\", starting in the Windows directory.
reg: The operation completed successfully
wine: could not open working directory L"unix\\home\\aapo\\.autodesk_fusion\\wineprefixes\\default\\", starting in the Windows directory.
wine: could not open working directory L"unix\\home\\aapo\\.autodesk_fusion\\wineprefixes\\default\\", starting in the Windows directory.
reg: The operation completed successfully
wine: could not open working directory L"unix\\home\\aapo\\.autodesk_fusion\\wineprefixes\\default\\", starting in the Windows directory.
wine: could not open working directory L"unix\\home\\aapo\\.autodesk_fusion\\wineprefixes\\default\\", starting in the Windows directory.
reg: The operation completed successfully
wine: could not open working directory L"unix\\home\\aapo\\.autodesk_fusion\\wineprefixes\\default\\", starting in the Windows directory.
wine: could not open working directory L"unix\\home\\aapo\\.autodesk_fusion\\wineprefixes\\default\\", starting in the Windows directory.
reg: The operation completed successfully
cp: cannot stat '/home/aapo/.autodesk_fusion/wineprefixes/default/drive_c/users/aapo/Downloads/WebView2installer.exe': Not a directory
002c:fixme:winediag:loader_init wine-staging 9.15 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
wine: failed to open "/home/aapo/.autodesk_fusion/wineprefixes/default/drive_c/users/aapo/Downloads/WebView2installer.exe": c0000135
./autodesk_fusion_installer_x86-64.sh: line 826: cd: /home/aapo/.autodesk_fusion/wineprefixes/default/drive_c/users/aapo/Downloads: Not a directory
wine: failed to open "/home/aapo/.autodesk_fusion/wineprefixes/default/drive_c/users/aapo/Downloads/FusionClientInstaller.exe": c0000135
002c:fixme:winediag:loader_init wine-staging 9.15 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
wine: failed to open "/home/aapo/.autodesk_fusion/wineprefixes/default/drive_c/users/aapo/Downloads/FusionClientInstaller.exe": c0000135
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   395  100   395    0     0   1426      0 --:--:-- --:--:-- --:--:--  1431
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   395  100   395    0     0   5190      0 --:--:-- --:--:-- --:--:--  5266
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   395  100   395    0     0   6153      0 --:--:-- --:--:-- --:--:--  6171
The old Qt6WebEngineCore.dll file is located in the following directory: 
cp: cannot stat '': No such file or directory
The Qt6WebEngineCore.dll file is backed up as Qt6WebEngineCore.dll.bak!
Patching the Qt6WebEngineCore.dll file for Autodesk Fusion ...
cp: cannot create regular file '': No such file or directory
The Qt6WebEngineCore.dll file is patched successfully!
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 48575  100 48575    0     0   139k      0 --:--:-- --:--:-- --:--:--  139k
./autodesk_fusion_installer_x86-64.sh: line 742: /home/aapo/.local/share/applications/wine/Programs/Autodesk/Autodesk Fusion.desktop: Permission denied
Searching for the variable location of the Autodesk Fusion identity manager...
./autodesk_fusion_installer_x86-64.sh: line 779: /home/aapo/.local/share/applications/adskidmgr-opener.desktop: Permission denied
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5926  100  5926    0     0  17829      0 --:--:-- --:--:-- --:--:-- 17849
The 'Window not responding' Dialog in GNOME will be reset!
Starting Autodesk Fusion 360 ...
[25665, Main Thread] WARNING: Theme parsing error: gtk.css:6616:68: Invalid name of pseudo-class: 'glib warning', file /builddir/build/BUILD/firefox-128.0.3/toolkit/xre/nsSigHandlers.cpp:187

(org.mozilla.firefox:25665): Gtk-WARNING **: 13:00:21.822: Theme parsing error: gtk.css:6616:68: Invalid name of pseudo-class
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    20  100    20    0     0     53      0 --:--:-- --:--:-- --:--:--    53
Online Build-Version: 2.0.19725
Online Insider-Build-Version: 2.0.19941

002c:fixme:winediag:loader_init wine-staging 9.15 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
wine: could not open working directory L"unix\\home\\aapo\\.autodesk_fusion\\bin\\", starting in the Windows directory.
Application could not be started, or no application associated with the specifie
d file.
ShellExecuteEx failed: File not found.

Logs from trying to run the launcher

[aapo@aapon-thinkpad-e14 bin]$ ./autodesk_fusion_launcher.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    20  100    20    0     0    288      0 --:--:-- --:--:-- --:--:--   289
Online Build-Version: 2.0.19725
Online Insider-Build-Version: 2.0.19941

002c:fixme:winediag:loader_init wine-staging 9.15 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
wine: could not open working directory L"unix\\home\\aapo\\.autodesk_fusion\\bin\\", starting in the Windows directory.
Application could not be started, or no application associated with the specifie
d file.
ShellExecuteEx failed: File not found.

</details>

**Comment by ilyakatz** [comment]
what was the resolution to this? i'm getting the same error
