### ISSUE TITLE
lsb-release instead of lsb_release

### ISSUE THREAD

**Issue by MasterLegoYoda** [cryinkfly/Autodesk-Fusion-360-for-Linux#467]
I think instead of having lsb-release in the available package checker, it should check for lsb_release instead

**Comment by vcsaba91** [comment]
Yeah, changing all of lsb-release to lsb_release in autodesk_fusion_installer_x86-64.sh, and endeavouros to garuda made it work, at least for me.

**Comment by cryinkfly** [comment]
:+1:
