### ISSUE TITLE
Script installed Fusion 360 doesn't open up a browser to log in.

### ISSUE THREAD

**Issue by a-chilean-cyborg** [cryinkfly/Autodesk-Fusion-360-for-Linux#471]
**Describe the bug**
Even with the latest version of the installation available at the time of writing, I can't get to log into fusion 360.

**To Reproduce**
Install Fusion 360 through the wine script and attempt to log in.

**Expected behaviour**
After clicking into the login button, the program opens up a browser window where I can log in.

**Screenshots**

**Desktop (please complete the following information):**
- Latest at the time of writing
- Nvidia MX250 + nvidia driver 535
- LMDE 6
- Cinnamon
- DXVK

**Additional context**
Any help on how to resolve this issue would be greatly appreciated.

**Comment by Lexanger** [comment]
I was also having this issue with Ubuntu 24.04 but resolved it by making sure I had the deb version of Firefox installed. Not a expert but what browser are you using? And while it may not help me, attaching log files will be sure to help someone else help you.

**Comment by NoSadBeHappy** [comment]
I also have this issue on fedora 40, and intsalling the rpm version of firefox didn't fix it. Where are log files found?

**Comment by ejfn** [comment]
> I was also having this issue with Ubuntu 24.04 but resolved it by making sure I had the deb version of Firefox installed. Not a expert but what browser are you using? And while it may not help me, attaching log files will be sure to help someone else help you.

This is the answer!

**Comment by cryinkfly** [comment]
How to Install Firefox as DEB on Ubuntu (Not Snap): https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04
