### ISSUE TITLE
unable to install on Nobara linux 40

### ISSUE THREAD

**Issue by Pinkham21** [cryinkfly/Autodesk-Fusion-360-for-Linux#475]
after running script terminal out put \:

**curl -L https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/setup/autodesk_fusion_installer_x86-64.sh -o "autodesk_fusion_installer_x86-64.sh" && chmod +x autodesk_fusion_installer_x86-64.sh && ./autodesk_fusion_installer_x86-64.sh --install --default
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 72363  100 72363    0     0   333k      0 --:--:-- --:--:-- --:--:--  334k
Checking for required command: curl ...
The required command (curl) is available!
Checking for required command: lsb_release ...
The required command (lsb_release) is available!
Checking for required command: glxinfo ...
The required command (glxinfo) is available!
Checking for required command: pkexec ...
The required command (pkexec) is available!
Checking for required command: wget ...
The required command (wget) is available!
Checking for required command: xdg-open ...
The required command (xdg-open) is available!
Checking for required command: ls ...
The required command (ls) is available!
Checking for required command: cat ...
The required command (cat) is available!
Checking for required command: echo ...
The required command (echo) is available!
Checking for required command: awk ...
The required command (awk) is available!
Checking for required command: 7z ...
The required command (7z) is available!
Checking for required command: cabextract ...
The required command (cabextract) is available!
Checking for required command: samba ...
The required command (samba) is not available!
Checking for required command: wbinfo ...
The required command (wbinfo) is available!
The installer will install the required packages for the installation!
Missing package: wbinfo
The installer doesn't support your current Linux distribution  at this time!
The installer has been terminated!**

It would install on Nobara 39 after upgrade to 40 will not install.

**Comment by cryinkfly** [comment]
Solved.
