### ISSUE TITLE
Syntax error in the installation script

### ISSUE THREAD

**Issue by Choptius** [cryinkfly/Autodesk-Fusion-360-for-Linux#478]
I get this error executing installation command
```
./autodesk_fusion_installer_x86-64.sh: line 1112: syntax error near unexpected token `}'
./autodesk_fusion_installer_x86-64.sh: line 1112: `}'
```

**Comment by Lloir** [comment]
https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/f53d2f62f4ded9f87cb2685cb9f9117341b38c6b/files/setup/autodesk_fusion_installer_x86-64.sh

use that for now

**Comment by cryinkfly** [comment]
Solved
