### ISSUE TITLE
QtWebEngineProcces.exe has encoutered

### ISSUE THREAD

**Issue by cviper13** [cryinkfly/Autodesk-Fusion-360-for-Linux#479]
**To Reproduce**
1. Install fusion 360 for linux using yad
2. Just start, and issue

**Expected behavior**
Should work Normally

**Screenshots**
![image](https://github.com/user-attachments/assets/50d1bca3-1b22-438a-949a-6d92edb50474)

**Desktop (please complete the following information):**
- Cant verify since UI is unrepsonsive, latest
- GTX 1650ti - nvidia 560.35.03-5
- Arch Linux
- Kde Plasma

**Comment by jhf2442** [comment]
same here, just did a fresh install today

**Comment by jhf2442** [comment]
Solved by using the patched DLL as stated in https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/473

**Comment by cviper13** [comment]
#473 patched DLL worked
