### ISSUE TITLE
Autodesk Logo does not disapear, no 3D render of part

### ISSUE THREAD

**Issue by PhilippBleimund** [cryinkfly/Autodesk-Fusion-360-for-Linux#480]
**Describe the bug**

The Autodesk Logo does not disapear.
I am able to select the model but the model is not displayed.

I also noticed that opening the preferences seem to crash fusion.

**To Reproduce**
I installed with:
`curl -L https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/setup/autodesk_fusion_installer_x86-64.sh -o "autodesk_fusion_installer_x86-64.sh" && chmod +x autodesk_fusion_installer_x86-64.sh && ./autodesk_fusion_installer_x86-64.sh --install --default`
To get the login working i had to copy the code and pass it via terminal with:
`WINEPREFIX="/home/philippbleimund/.autodesk_fusion/wineprefixes/default" wine "/home/philippbleimund/.autodesk_fusion/wineprefixes/default/drive_c/Program Files/Autodesk/webdeploy/production/1a197c6e79bef01edef1dc4f317d9f597820e633/Autodesk Identity Manager/AdskIdentityManager.exe" "<login code>"`

After this i was able to start fusion with the .desktop file.

**Screenshots**
![image](https://github.com/user-attachments/assets/5a699612-eb42-4d80-9786-072a6b9a697f)

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360
  - cant open the about page
- Graphics card model + Graphics card driver (Version number)
 - GeForce RTX 3080, nvidia-driver-550
- Operating system (OpenSUSE Leap 15.3, Fedora 34, ...)
  - ubuntu 24.04.1 LTS
- Desktop environment (XFCE 4.16, Gnome 40, ...)
  - gnome
- DXVK- or OpenGL-Mode
  - DXVK

**Additional context**
I tried the .dll fix from https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/473#issuecomment-2329748393 but this does not seem to work

**Comment by FortMarinus** [comment]
I had the same problem, this helped. 

- Go to 'Preferences', it takes a while to load up, be patient, upwards of one minute. 
- Then, change the Graphics Driver under General to OpenGL Core Profile, and then follow the prompts to restart. 
- Then, you might have to open and close your document (not the program), or try to create a new sketch. 

![prefs1](https://github.com/user-attachments/assets/0fc8fda9-783f-43ee-a77c-c50391aebda3)

![preferences](https://github.com/user-attachments/assets/32dafd2b-6dd0-4e67-ab02-e58b788530cf)


*   Version number of Autodesk Fusion 360
    * About page doesn't open
* Graphics card model + Graphics card driver
    * GeForce RTX 4060 Ti 16Gb
    * Nvidia Driver (open kernel) metapackage from nvidia-driver-550-open (proprietary)
    * NVIDIA UNIX Open Kernel Module for x86_64  550.107.02
*   Operating system
    * Zorin OS 17.1 (~ Ubuntu 22.04 Jammy)
*  Desktop environment
    * GNOME 43.9

**Comment by PhilippBleimund** [comment]
@FortMarinus Thank you that was exactly it :)
