### ISSUE TITLE
Load Fusion without Wine Virtual Desktop

### ISSUE THREAD

**Issue by robert-stevenson-1** [cryinkfly/Autodesk-Fusion-360-for-Linux#481]
Not sure what is causing this and how I can change this, but in a previous installation i remember fusion loading up without a wine virtual desktop having to load up and contain the fusion window, and instead fusion appeared to look "native" with my OS.

I installed using the installer script from commit: ec0e484

Is there something i can do to get the old style application display, without having wine virtual desktop start up and containing the application?

**Comment by alansrobotlab2** [comment]
yeah man, I don't know why but sometimes when you run the install script it's configured for virtual desktop and other times it is not.  to disable virtual desktop:

1. export WINEPREFIX=(line 3 from logs/wineprefixes.log)
2. wineconfig
3. graphics tab->uncheck virtual desktop & save

**Comment by robert-stevenson-1** [comment]
> yeah man, I don't know why but sometimes when you run the install script it's configured for virtual desktop and other times it is not. to disable virtual desktop:
> 
> 1. export WINEPREFIX=(line 3 from logs/wineprefixes.log)
> 2. wineconfig
> 3. graphics tab->uncheck virtual desktop & save

This worked out.
Just a minor correction "wineconfig" => `winecfg`. Maybe they change the command between wine versions? (I'm not familiar with Wine, so not sure)

**Comment by robert-stevenson-1** [comment]
I'll leave the issue open for now, because if the virtual desktop is sometimes being used when installing but not all the time.

Perhaps there is a way to update the install script to lock it to one of the options? (preferable off, i would think)

**Comment by Knden** [comment]
> yeah man, I don't know why but sometimes when you run the install script it's configured for virtual desktop and other times it is not. to disable virtual desktop:
> 
>     1. export WINEPREFIX=(line 3 from logs/wineprefixes.log)
> 
>     2. wineconfig
> 
>     3. graphics tab->uncheck virtual desktop & save

I haven't found where logs are, but i used `export WINEPREFIX=$HOME/.autodesk_fusion/wineprefixes/default`  and then `winecfg` as robert said and it worked out. Thank you !

**Comment by ak1932** [comment]
wine: could not open working directory L"unix\\home\\ak\\", starting in the Windows directory. 
I am getting this error after trying to launch winecfg. It stalls here and no window opens up

**Comment by cryinkfly** [comment]
I have disabled this function in the installer by default. But we need this when we would like to safe or export our projects.
