### ISSUE TITLE
Cannot save designs - `createZipPartFromFile` Exception

### ISSUE THREAD

**Issue by sebadob** [cryinkfly/Autodesk-Fusion-360-for-Linux#483]
**Describe the bug**
After some time working in Fusion360 and creating designs or whatever, I cannot save my work anymore and I lose everything I did since it worked "the last time". In the beginning, saving works fine, but after a while I only ever get execptions and basically lose everything I did until then. There is no way to save data and the only thing I can do is to "close Fusion360 without saving".

`DesignConfigurationTableBlobSerializer::doSave - createZipPartFromFile failed!`

**To Reproduce**
1. Start working on a project
2. Save a first version, maybe just a simple sketch
3. Keep on working for "some time", I don't know any timing yet. It "just happens" after a while.
4. Try to save again and get an exception.

**Expected behavior**
This is pretty obivious. I would like to be able to save my work and not lose everything each time.

**Screenshots**
![image](https://github.com/user-attachments/assets/33641434-116b-4e75-876f-5d61e0601b40)

**Desktop (please complete the following information):**
- `Fusion 2.0.19983 x86_64`
- Graphics card model + Graphics card driver: Raedon RX7800XT with `amdgpu` from Kernel `6.10.10-200.fc40.x86_64`
- Operating system: Fedora 40 KDE Plasma spin
- Desktop environment: KDE Plasma `6.1.5`

**Comment by sebadob** [comment]
Update:

I did a few more tests and sometimes it starts to fail after 5 minutes of working, an other times I can open a new design and it still does not fail after 1 hour. So it does not depend on the time (though of something like autosave) or the amount of numbers I saved manually. Sometimes I can save once and the next save will fail 5 mintes later, while other times I can do 20 manual saves and the 21. fails after 10 mintes.

**Comment by Sebastian-gomezC** [comment]
That is a common issue, check  #[362 ](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/362#issuecomment-1889835832)

**Comment by sebadob** [comment]
> That is a common issue, check #362 

Thank you! I wasn't aware of this. It seems to be fixed for now by disabling proxy warnings.

It may make sense to add things like this to the wiki, because there were a few bugs I needed to fix manually like focussing and the login, but that's another topic.
