### ISSUE TITLE
Check if wine is available

### ISSUE THREAD

**Issue by Daniel-Chin** [cryinkfly/Autodesk-Fusion-360-for-Linux#486]
**Is your feature request related to a problem? Please describe.**
I selected "wine is already installed on the system" without wine. It led to a broken partial install.

**Describe the solution you'd like**
After the user selects "I have wine", check if `wine` is available. If not, error.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by cryinkfly** [comment]
You use the old installer!
