### ISSUE TITLE
QtWebEngineProcess.exe has found a serious problem and needs to close

### ISSUE THREAD

**Issue by ffpp2003** [cryinkfly/Autodesk-Fusion-360-for-Linux#505]
**Describe the bug**
10 to 20 popups like the ones in the photo appear right after launching Fusion360. Also, each time you try to open/close the data panel, new popups appear. When closing Fusion360, the same thing happens.

**To Reproduce**
1. Open Fusion360

**Expected behavior**
No popups appearing

**Screenshots**
![image](https://github.com/user-attachments/assets/971095f2-dbe6-4a99-91c3-b0233de02c32)

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360: Online Build-Version: 2.0.19994
Online Insider-Build-Version: 2.0.20220
System Build-Version: 2.0.20962

- Graphics card model + Graphics card driver (Version number): Nvidia GTX 1660 Super, Driver: NVIDIA 565.57.1
- Operating system (OpenSUSE Leap 15.3, Fedora 34, ...): Arch Linux
- Desktop environment (XFCE 4.16, Gnome 40, ...): Gnome 47
- DXVK- or OpenGL-Mode: Both (installed DXVK, but the same happens when choosing opengl mode on fusion)

**Additional context**
This is a brand new installation. Here are some logs:
[logs.zip](https://github.com/user-attachments/files/17940214/logs.zip)

**Comment by madurani** [comment]
Did you replaced patched file Qt6WebEngineCore.dll?

**Comment by ffpp2003** [comment]
No, I only installed fusion using YAD and that happened. Should I replace it by another .dll?

**Comment by madurani** [comment]
I have to replace only mentioned dll after fresh installation. Without it Fusion not work for me. I don't know what is "YAD"

**Comment by ffpp2003** [comment]
YAD is the other way of installing fusion360, it's on the [wiki](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/wiki/Documentation#installing-the-installer-package).

Can you please show me where to get the dll and how to replace it?

**Comment by madurani** [comment]
https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/blob/main/files/extras/patched-dlls/Qt6WebEngineCore.dll.7z

**Comment by ffpp2003** [comment]
That did it! Replacing the patched dll under $HOME/.fusion360/wineprefixes/default/drive_c/users/$USER/AppData/Local/Autodesk/webdeploy/production/<long_name_folder_with_other_dlls> and launching Fusion fixed the annoying popups
