### ISSUE TITLE
New electronics library errors *solved*

### ISSUE THREAD

**Issue by roboticsmick** [cryinkfly/Autodesk-Fusion-360-for-Linux#69]
I get a few warning errors popping up every few minutes when I'm in the "New Electronics Library".

`Can't open 'C:\Program Files\Autodesk\webdeploy\production\2719e3c6bed8896e3c7319fbb8bfbceff8f489a4\Applications\Electron\LibEagle\examples\scripts\examples\eagle.scr'
Too many open files`

And when I create a schematic:
![image](https://user-images.githubusercontent.com/70121687/131287788-3bb96304-c9f6-4fc0-93e1-2a377d35ac20.png)

**Comment by cryinkfly** [comment]
When I create a new one:

![1_electronics_library.png](https://raw.githubusercontent.com/cryinkfly/Fusion-360---Linux-Wine-Version-/main/images/electronics/%231_electronics_library.png)

![1.1_electronics_library.png](https://raw.githubusercontent.com/cryinkfly/Fusion-360---Linux-Wine-Version-/main/images/electronics/%231.1_electronics_library.png)

**Comment by cryinkfly** [comment]
@roboticsmick Can you give me more information about your system? 😊
